// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protocol.proto
// Protobuf Java Version: 4.33.2

package po;

@com.google.protobuf.Generated
public interface CreateQuestionReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:po.CreateQuestionReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 问题信息
   * </pre>
   *
   * <code>optional .po.QuestionInfo question = 1;</code>
   * @return Whether the question field is set.
   */
  boolean hasQuestion();
  /**
   * <pre>
   * 问题信息
   * </pre>
   *
   * <code>optional .po.QuestionInfo question = 1;</code>
   * @return The question.
   */
  po.QuestionInfo getQuestion();
  /**
   * <pre>
   * 问题信息
   * </pre>
   *
   * <code>optional .po.QuestionInfo question = 1;</code>
   */
  po.QuestionInfoOrBuilder getQuestionOrBuilder();
}
