// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protocol.proto
// Protobuf Java Version: 4.33.2

package po;

@com.google.protobuf.Generated
public interface CreatePeopleRspOrBuilder extends
    // @@protoc_insertion_point(interface_extends:po.CreatePeopleRsp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 创建失败的人员信息
   * </pre>
   *
   * <code>repeated .po.ErrInfo err = 1;</code>
   */
  java.util.List<po.ErrInfo> 
      getErrList();
  /**
   * <pre>
   * 创建失败的人员信息
   * </pre>
   *
   * <code>repeated .po.ErrInfo err = 1;</code>
   */
  po.ErrInfo getErr(int index);
  /**
   * <pre>
   * 创建失败的人员信息
   * </pre>
   *
   * <code>repeated .po.ErrInfo err = 1;</code>
   */
  int getErrCount();
  /**
   * <pre>
   * 创建失败的人员信息
   * </pre>
   *
   * <code>repeated .po.ErrInfo err = 1;</code>
   */
  java.util.List<? extends po.ErrInfoOrBuilder> 
      getErrOrBuilderList();
  /**
   * <pre>
   * 创建失败的人员信息
   * </pre>
   *
   * <code>repeated .po.ErrInfo err = 1;</code>
   */
  po.ErrInfoOrBuilder getErrOrBuilder(
      int index);
}
