// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protocol.proto
// Protobuf Java Version: 4.33.2

package po;

/**
 * <pre>
 * 创建家庭信息（管理员） - 回执
 * </pre>
 *
 * Protobuf type {@code po.CreatePeopleRsp}
 */
@com.google.protobuf.Generated
public final class CreatePeopleRsp extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:po.CreatePeopleRsp)
    CreatePeopleRspOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "CreatePeopleRsp");
  }
  // Use CreatePeopleRsp.newBuilder() to construct.
  private CreatePeopleRsp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CreatePeopleRsp() {
    errCardIds_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return po.ProtocolProto.internal_static_po_CreatePeopleRsp_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return po.ProtocolProto.internal_static_po_CreatePeopleRsp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            po.CreatePeopleRsp.class, po.CreatePeopleRsp.Builder.class);
  }

  public static final int ERRCARDIDS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList errCardIds_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * 创建失败的人员信息
   * </pre>
   *
   * <code>repeated string errCardIds = 1;</code>
   * @return A list containing the errCardIds.
   */
  public com.google.protobuf.ProtocolStringList
      getErrCardIdsList() {
    return errCardIds_;
  }
  /**
   * <pre>
   * 创建失败的人员信息
   * </pre>
   *
   * <code>repeated string errCardIds = 1;</code>
   * @return The count of errCardIds.
   */
  public int getErrCardIdsCount() {
    return errCardIds_.size();
  }
  /**
   * <pre>
   * 创建失败的人员信息
   * </pre>
   *
   * <code>repeated string errCardIds = 1;</code>
   * @param index The index of the element to return.
   * @return The errCardIds at the given index.
   */
  public java.lang.String getErrCardIds(int index) {
    return errCardIds_.get(index);
  }
  /**
   * <pre>
   * 创建失败的人员信息
   * </pre>
   *
   * <code>repeated string errCardIds = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the errCardIds at the given index.
   */
  public com.google.protobuf.ByteString
      getErrCardIdsBytes(int index) {
    return errCardIds_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < errCardIds_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, errCardIds_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < errCardIds_.size(); i++) {
        dataSize += computeStringSizeNoTag(errCardIds_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getErrCardIdsList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof po.CreatePeopleRsp)) {
      return super.equals(obj);
    }
    po.CreatePeopleRsp other = (po.CreatePeopleRsp) obj;

    if (!getErrCardIdsList()
        .equals(other.getErrCardIdsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getErrCardIdsCount() > 0) {
      hash = (37 * hash) + ERRCARDIDS_FIELD_NUMBER;
      hash = (53 * hash) + getErrCardIdsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static po.CreatePeopleRsp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static po.CreatePeopleRsp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static po.CreatePeopleRsp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static po.CreatePeopleRsp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static po.CreatePeopleRsp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static po.CreatePeopleRsp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static po.CreatePeopleRsp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static po.CreatePeopleRsp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static po.CreatePeopleRsp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static po.CreatePeopleRsp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static po.CreatePeopleRsp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static po.CreatePeopleRsp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(po.CreatePeopleRsp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 创建家庭信息（管理员） - 回执
   * </pre>
   *
   * Protobuf type {@code po.CreatePeopleRsp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:po.CreatePeopleRsp)
      po.CreatePeopleRspOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return po.ProtocolProto.internal_static_po_CreatePeopleRsp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return po.ProtocolProto.internal_static_po_CreatePeopleRsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              po.CreatePeopleRsp.class, po.CreatePeopleRsp.Builder.class);
    }

    // Construct using po.CreatePeopleRsp.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      errCardIds_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return po.ProtocolProto.internal_static_po_CreatePeopleRsp_descriptor;
    }

    @java.lang.Override
    public po.CreatePeopleRsp getDefaultInstanceForType() {
      return po.CreatePeopleRsp.getDefaultInstance();
    }

    @java.lang.Override
    public po.CreatePeopleRsp build() {
      po.CreatePeopleRsp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public po.CreatePeopleRsp buildPartial() {
      po.CreatePeopleRsp result = new po.CreatePeopleRsp(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(po.CreatePeopleRsp result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        errCardIds_.makeImmutable();
        result.errCardIds_ = errCardIds_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof po.CreatePeopleRsp) {
        return mergeFrom((po.CreatePeopleRsp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(po.CreatePeopleRsp other) {
      if (other == po.CreatePeopleRsp.getDefaultInstance()) return this;
      if (!other.errCardIds_.isEmpty()) {
        if (errCardIds_.isEmpty()) {
          errCardIds_ = other.errCardIds_;
          bitField0_ |= 0x00000001;
        } else {
          ensureErrCardIdsIsMutable();
          errCardIds_.addAll(other.errCardIds_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureErrCardIdsIsMutable();
              errCardIds_.add(s);
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringArrayList errCardIds_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureErrCardIdsIsMutable() {
      if (!errCardIds_.isModifiable()) {
        errCardIds_ = new com.google.protobuf.LazyStringArrayList(errCardIds_);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <pre>
     * 创建失败的人员信息
     * </pre>
     *
     * <code>repeated string errCardIds = 1;</code>
     * @return A list containing the errCardIds.
     */
    public com.google.protobuf.ProtocolStringList
        getErrCardIdsList() {
      errCardIds_.makeImmutable();
      return errCardIds_;
    }
    /**
     * <pre>
     * 创建失败的人员信息
     * </pre>
     *
     * <code>repeated string errCardIds = 1;</code>
     * @return The count of errCardIds.
     */
    public int getErrCardIdsCount() {
      return errCardIds_.size();
    }
    /**
     * <pre>
     * 创建失败的人员信息
     * </pre>
     *
     * <code>repeated string errCardIds = 1;</code>
     * @param index The index of the element to return.
     * @return The errCardIds at the given index.
     */
    public java.lang.String getErrCardIds(int index) {
      return errCardIds_.get(index);
    }
    /**
     * <pre>
     * 创建失败的人员信息
     * </pre>
     *
     * <code>repeated string errCardIds = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the errCardIds at the given index.
     */
    public com.google.protobuf.ByteString
        getErrCardIdsBytes(int index) {
      return errCardIds_.getByteString(index);
    }
    /**
     * <pre>
     * 创建失败的人员信息
     * </pre>
     *
     * <code>repeated string errCardIds = 1;</code>
     * @param index The index to set the value at.
     * @param value The errCardIds to set.
     * @return This builder for chaining.
     */
    public Builder setErrCardIds(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureErrCardIdsIsMutable();
      errCardIds_.set(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 创建失败的人员信息
     * </pre>
     *
     * <code>repeated string errCardIds = 1;</code>
     * @param value The errCardIds to add.
     * @return This builder for chaining.
     */
    public Builder addErrCardIds(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureErrCardIdsIsMutable();
      errCardIds_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 创建失败的人员信息
     * </pre>
     *
     * <code>repeated string errCardIds = 1;</code>
     * @param values The errCardIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllErrCardIds(
        java.lang.Iterable<java.lang.String> values) {
      ensureErrCardIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, errCardIds_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 创建失败的人员信息
     * </pre>
     *
     * <code>repeated string errCardIds = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearErrCardIds() {
      errCardIds_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 创建失败的人员信息
     * </pre>
     *
     * <code>repeated string errCardIds = 1;</code>
     * @param value The bytes of the errCardIds to add.
     * @return This builder for chaining.
     */
    public Builder addErrCardIdsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureErrCardIdsIsMutable();
      errCardIds_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:po.CreatePeopleRsp)
  }

  // @@protoc_insertion_point(class_scope:po.CreatePeopleRsp)
  private static final po.CreatePeopleRsp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new po.CreatePeopleRsp();
  }

  public static po.CreatePeopleRsp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreatePeopleRsp>
      PARSER = new com.google.protobuf.AbstractParser<CreatePeopleRsp>() {
    @java.lang.Override
    public CreatePeopleRsp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CreatePeopleRsp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreatePeopleRsp> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public po.CreatePeopleRsp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

