// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protocol.proto
// Protobuf Java Version: 4.33.2

package po;

@com.google.protobuf.Generated
public interface CreateStudyReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:po.CreateStudyReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 学习信息
   * </pre>
   *
   * <code>optional .po.StudyInfo studyInfo = 1;</code>
   * @return Whether the studyInfo field is set.
   */
  boolean hasStudyInfo();
  /**
   * <pre>
   * 学习信息
   * </pre>
   *
   * <code>optional .po.StudyInfo studyInfo = 1;</code>
   * @return The studyInfo.
   */
  po.StudyInfo getStudyInfo();
  /**
   * <pre>
   * 学习信息
   * </pre>
   *
   * <code>optional .po.StudyInfo studyInfo = 1;</code>
   */
  po.StudyInfoOrBuilder getStudyInfoOrBuilder();
}
