// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protocol.proto
// Protobuf Java Version: 4.33.2

package po;

@com.google.protobuf.Generated
public interface DelPeopleUpdateApplyReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:po.DelPeopleUpdateApplyReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 applyId = 1;</code>
   * @return Whether the applyId field is set.
   */
  boolean hasApplyId();
  /**
   * <code>optional int32 applyId = 1;</code>
   * @return The applyId.
   */
  int getApplyId();
}
