// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: entity.proto
// Protobuf Java Version: 4.33.2

package po;

@com.google.protobuf.Generated
public final class EntityProto extends com.google.protobuf.GeneratedFile {
  private EntityProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "EntityProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_po_UserInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_po_UserInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_po_NoticeInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_po_NoticeInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_po_UserReadNoticeInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_po_UserReadNoticeInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_po_UpdateInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_po_UpdateInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_po_QuestionInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_po_QuestionInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_po_QuestionHandlingInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_po_QuestionHandlingInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_po_NotifyUserInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_po_NotifyUserInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_po_StudyInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_po_StudyInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_po_UserStarStudyInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_po_UserStarStudyInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_po_PeopleInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_po_PeopleInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_po_PeopleUpdateApply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_po_PeopleUpdateApply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014entity.proto\022\002po\032\nbase.proto\"\263\002\n\010UserI" +
      "nfo\022\024\n\007userTel\030\001 \001(\005H\000\210\001\001\022\025\n\010userName\030\002 " +
      "\001(\tH\001\210\001\001\022\024\n\007userPwd\030\003 \001(\tH\002\210\001\001\022\025\n\010userTo" +
      "wn\030\004 \001(\tH\003\210\001\001\022&\n\tuserPower\030\005 \001(\0162\016.po.TU" +
      "serPowerH\004\210\001\001\022\033\n\016userCreateTime\030\006 \001(\003H\005\210" +
      "\001\001\022(\n\010flagType\030\007 \001(\0162\021.po.TUserFlagTypeH" +
      "\006\210\001\001B\n\n\010_userTelB\013\n\t_userNameB\n\n\010_userPw" +
      "dB\013\n\t_userTownB\014\n\n_userPowerB\021\n\017_userCre" +
      "ateTimeB\013\n\t_flagType\"\263\003\n\nNoticeInfo\022\025\n\010n" +
      "oticeId\030\001 \001(\005H\000\210\001\001\022(\n\nnoticeType\030\002 \001(\0162\017" +
      ".po.TNoticeTypeH\001\210\001\001\022\035\n\020noticeCreateTime" +
      "\030\003 \001(\003H\002\210\001\001\022\030\n\013noticeTitle\030\004 \001(\tH\003\210\001\001\022\032\n" +
      "\rnoticeContext\030\005 \001(\tH\004\210\001\001\022\026\n\twriterTel\030\006" +
      " \001(\005H\005\210\001\001\022\027\n\nwriterName\030\007 \001(\tH\006\210\001\001\022\022\n\005is" +
      "Top\030\010 \001(\010H\007\210\001\001\022\031\n\014isAcceptRead\030\t \001(\010H\010\210\001" +
      "\001\022\026\n\tnoticeAtt\030\n \001(\014H\t\210\001\001B\013\n\t_noticeIdB\r" +
      "\n\013_noticeTypeB\023\n\021_noticeCreateTimeB\016\n\014_n" +
      "oticeTitleB\020\n\016_noticeContextB\014\n\n_writerT" +
      "elB\r\n\013_writerNameB\010\n\006_isTopB\017\n\r_isAccept" +
      "ReadB\014\n\n_noticeAtt\"\226\001\n\022UserReadNoticeInf" +
      "o\022\017\n\002id\030\001 \001(\005H\000\210\001\001\022\024\n\007userTel\030\002 \001(\005H\001\210\001\001" +
      "\022\025\n\010noticeId\030\003 \001(\005H\002\210\001\001\022\025\n\010readTime\030\004 \001(" +
      "\003H\003\210\001\001B\005\n\003_idB\n\n\010_userTelB\013\n\t_noticeIdB\013" +
      "\n\t_readTime\"\321\002\n\nUpdateInfo\022\025\n\010updateId\030\001" +
      " \001(\005H\000\210\001\001\022\023\n\006infoId\030\002 \001(\003H\001\210\001\001\022*\n\010infoTy" +
      "pe\030\003 \001(\0162\023.po.TUpdateInfoTypeH\002\210\001\001\022\026\n\tbe" +
      "foreMsg\030\004 \001(\014H\003\210\001\001\022\025\n\010afterMsg\030\005 \001(\014H\004\210\001" +
      "\001\022\027\n\nupdateTime\030\006 \001(\003H\005\210\001\001\022\032\n\rupdateUser" +
      "Tel\030\007 \001(\005H\006\210\001\001\022\027\n\nupdateName\030\010 \001(\tH\007\210\001\001B" +
      "\013\n\t_updateIdB\t\n\007_infoIdB\013\n\t_infoTypeB\014\n\n" +
      "_beforeMsgB\013\n\t_afterMsgB\r\n\013_updateTimeB\020" +
      "\n\016_updateUserTelB\r\n\013_updateName\"\212\003\n\014Ques" +
      "tionInfo\022\027\n\nquestionId\030\001 \001(\005H\000\210\001\001\022+\n\014que" +
      "stionType\030\002 \001(\0162\020.po.QuestionTypeH\001\210\001\001\022\030" +
      "\n\013questionCtx\030\003 \001(\tH\002\210\001\001\022\027\n\nquestPhoto\030\004" +
      " \001(\014H\003\210\001\001\022\036\n\021questionWriterTel\030\005 \001(\005H\004\210\001" +
      "\001\022+\n\010nodeType\030\006 \001(\0162\024.po.QuestionNodeTyp" +
      "eH\005\210\001\001\022\027\n\nchoiceUser\030\007 \001(\005H\006\210\001\001\022\031\n\014quest" +
      "ionTime\030\010 \001(\003H\007\210\001\001B\r\n\013_questionIdB\017\n\r_qu" +
      "estionTypeB\016\n\014_questionCtxB\r\n\013_questPhot" +
      "oB\024\n\022_questionWriterTelB\013\n\t_nodeTypeB\r\n\013" +
      "_choiceUserB\017\n\r_questionTime\"\256\002\n\024Questio" +
      "nHandlingInfo\022\027\n\nhandlingId\030\001 \001(\005H\000\210\001\001\022\024" +
      "\n\007questId\030\002 \001(\005H\001\210\001\001\0223\n\014handlingType\030\003 \001" +
      "(\0162\030.po.QuestionHandlingTypeH\002\210\001\001\022\034\n\017han" +
      "dlingUserTel\030\004 \001(\005H\003\210\001\001\022\030\n\013handlingCtx\030\005" +
      " \001(\014H\004\210\001\001\022\031\n\014handlingTime\030\006 \001(\003H\005\210\001\001B\r\n\013" +
      "_handlingIdB\n\n\010_questIdB\017\n\r_handlingType" +
      "B\022\n\020_handlingUserTelB\016\n\014_handlingCtxB\017\n\r" +
      "_handlingTime\"_\n\016NotifyUserInfo\022!\n\007msgTy" +
      "pe\030\001 \001(\0162\013.po.MsgTypeH\000\210\001\001\022\023\n\006msgCtx\030\002 \001" +
      "(\014H\001\210\001\001B\n\n\010_msgTypeB\t\n\007_msgCtx\"\360\002\n\tStudy" +
      "Info\022\024\n\007studyId\030\001 \001(\005H\000\210\001\001\022%\n\tstudyType\030" +
      "\002 \001(\0162\r.po.StudyTypeH\001\210\001\001\022\034\n\017studyCreate" +
      "Time\030\003 \001(\003H\002\210\001\001\022\027\n\nstudyTitle\030\004 \001(\tH\003\210\001\001" +
      "\022\025\n\010studyTip\030\005 \001(\tH\004\210\001\001\022\031\n\014studyContent\030" +
      "\006 \001(\tH\005\210\001\001\022\023\n\006isOpen\030\007 \001(\010H\006\210\001\001\022\022\n\005isTop" +
      "\030\010 \001(\010H\007\210\001\001\022\026\n\treadCount\030\t \001(\005H\010\210\001\001B\n\n\010_" +
      "studyIdB\014\n\n_studyTypeB\022\n\020_studyCreateTim" +
      "eB\r\n\013_studyTitleB\013\n\t_studyTipB\017\n\r_studyC" +
      "ontentB\t\n\007_isOpenB\010\n\006_isTopB\014\n\n_readCoun" +
      "t\"w\n\021UserStarStudyInfo\022\023\n\006starId\030\001 \001(\005H\000" +
      "\210\001\001\022\024\n\007userTel\030\002 \001(\005H\001\210\001\001\022\024\n\007studyId\030\003 \001" +
      "(\005H\002\210\001\001B\t\n\007_starIdB\n\n\010_userTelB\n\n\010_study" +
      "Id\"\264\001\n\nPeopleInfo\022\031\n\014peopleCardId\030\001 \001(\tH" +
      "\000\210\001\001\022\027\n\npeopleName\030\002 \001(\tH\001\210\001\001\022\032\n\rpeopleH" +
      "ouseId\030\003 \001(\tH\002\210\001\001\022\026\n\tpeopleCtx\030\004 \001(\tH\003\210\001" +
      "\001B\017\n\r_peopleCardIdB\r\n\013_peopleNameB\020\n\016_pe" +
      "opleHouseIdB\014\n\n_peopleCtx\"\267\001\n\021PeopleUpda" +
      "teApply\022\024\n\007applyId\030\001 \001(\005H\000\210\001\001\022\030\n\013applyUs" +
      "erId\030\002 \001(\005H\001\210\001\001\022\034\n\017applyCreateTime\030\003 \001(\003" +
      "H\002\210\001\001\022\026\n\tnewPeople\030\004 \001(\014H\003\210\001\001B\n\n\010_applyI" +
      "dB\016\n\014_applyUserIdB\022\n\020_applyCreateTimeB\014\n" +
      "\n_newPeople*>\n\rTUserFlagType\022\020\n\014TUFT_DEF" +
      "AULT\020\000\022\014\n\010TUFT_BAN\020\001\022\r\n\tTUFT_FLAG\020\002*%\n\nT" +
      "UserPower\022\n\n\006TUP_CM\020\000\022\013\n\007TUP_CGM\020\001*M\n\013TN" +
      "oticeType\022\n\n\006TNT_TZ\020\000\022\n\n\006TNT_ZP\020\001\022\n\n\006TNT" +
      "_HD\020\002\022\014\n\010TNT_ZFXC\020\003\022\014\n\010TNT_GKZW\020\004*U\n\017TUp" +
      "dateInfoType\022\017\n\013TUIT_NOTICE\020\000\022\r\n\tTUIT_US" +
      "ER\020\001\022\017\n\013TUIT_PEOPLE\020\002\022\021\n\rTUIT_QUESTION\020\003" +
      "*M\n\020QuestionNodeType\022\014\n\010TQNT_PRE\020\000\022\014\n\010TQ" +
      "NT_MID\020\001\022\r\n\tTQNT_TAIL\020\002\022\016\n\nTQNT_CLOSE\020\003*" +
      "F\n\014QuestionType\022\014\n\010TQT_WSHJ\020\000\022\014\n\010TQT_LLJ" +
      "F\020\001\022\014\n\010TQT_JCSS\020\002\022\014\n\010TQT_GBZF\020\003*I\n\024Quest" +
      "ionHandlingType\022\014\n\010TQHT_END\020\000\022\022\n\016TQHT_HA" +
      "S_QUEST\020\001\022\017\n\013TQHT_CANNOT\020\002*C\n\tStudyType\022" +
      "\014\n\010TST_ZCJD\020\000\022\014\n\010TST_NJTG\020\001\022\014\n\010TST_JKYS\020" +
      "\002\022\014\n\010TST_FLCS\020\003B\023\n\002poB\013EntityProtoP\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          po.BaseProto.getDescriptor(),
        });
    internal_static_po_UserInfo_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_po_UserInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_po_UserInfo_descriptor,
        new java.lang.String[] { "UserTel", "UserName", "UserPwd", "UserTown", "UserPower", "UserCreateTime", "FlagType", });
    internal_static_po_NoticeInfo_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_po_NoticeInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_po_NoticeInfo_descriptor,
        new java.lang.String[] { "NoticeId", "NoticeType", "NoticeCreateTime", "NoticeTitle", "NoticeContext", "WriterTel", "WriterName", "IsTop", "IsAcceptRead", "NoticeAtt", });
    internal_static_po_UserReadNoticeInfo_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_po_UserReadNoticeInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_po_UserReadNoticeInfo_descriptor,
        new java.lang.String[] { "Id", "UserTel", "NoticeId", "ReadTime", });
    internal_static_po_UpdateInfo_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_po_UpdateInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_po_UpdateInfo_descriptor,
        new java.lang.String[] { "UpdateId", "InfoId", "InfoType", "BeforeMsg", "AfterMsg", "UpdateTime", "UpdateUserTel", "UpdateName", });
    internal_static_po_QuestionInfo_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_po_QuestionInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_po_QuestionInfo_descriptor,
        new java.lang.String[] { "QuestionId", "QuestionType", "QuestionCtx", "QuestPhoto", "QuestionWriterTel", "NodeType", "ChoiceUser", "QuestionTime", });
    internal_static_po_QuestionHandlingInfo_descriptor =
      getDescriptor().getMessageType(5);
    internal_static_po_QuestionHandlingInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_po_QuestionHandlingInfo_descriptor,
        new java.lang.String[] { "HandlingId", "QuestId", "HandlingType", "HandlingUserTel", "HandlingCtx", "HandlingTime", });
    internal_static_po_NotifyUserInfo_descriptor =
      getDescriptor().getMessageType(6);
    internal_static_po_NotifyUserInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_po_NotifyUserInfo_descriptor,
        new java.lang.String[] { "MsgType", "MsgCtx", });
    internal_static_po_StudyInfo_descriptor =
      getDescriptor().getMessageType(7);
    internal_static_po_StudyInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_po_StudyInfo_descriptor,
        new java.lang.String[] { "StudyId", "StudyType", "StudyCreateTime", "StudyTitle", "StudyTip", "StudyContent", "IsOpen", "IsTop", "ReadCount", });
    internal_static_po_UserStarStudyInfo_descriptor =
      getDescriptor().getMessageType(8);
    internal_static_po_UserStarStudyInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_po_UserStarStudyInfo_descriptor,
        new java.lang.String[] { "StarId", "UserTel", "StudyId", });
    internal_static_po_PeopleInfo_descriptor =
      getDescriptor().getMessageType(9);
    internal_static_po_PeopleInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_po_PeopleInfo_descriptor,
        new java.lang.String[] { "PeopleCardId", "PeopleName", "PeopleHouseId", "PeopleCtx", });
    internal_static_po_PeopleUpdateApply_descriptor =
      getDescriptor().getMessageType(10);
    internal_static_po_PeopleUpdateApply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_po_PeopleUpdateApply_descriptor,
        new java.lang.String[] { "ApplyId", "ApplyUserId", "ApplyCreateTime", "NewPeople", });
    descriptor.resolveAllFeaturesImmutable();
    po.BaseProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
