// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protocol.proto
// Protobuf Java Version: 4.33.2

package po;

/**
 * <pre>
 * 获取问题列表 - 回执
 * </pre>
 *
 * Protobuf type {@code po.ListQuestionRsp}
 */
@com.google.protobuf.Generated
public final class ListQuestionRsp extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:po.ListQuestionRsp)
    ListQuestionRspOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "ListQuestionRsp");
  }
  // Use ListQuestionRsp.newBuilder() to construct.
  private ListQuestionRsp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ListQuestionRsp() {
    infos_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return po.ProtocolProto.internal_static_po_ListQuestionRsp_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return po.ProtocolProto.internal_static_po_ListQuestionRsp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            po.ListQuestionRsp.class, po.ListQuestionRsp.Builder.class);
  }

  public static final int INFOS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<po.QuestionInfo> infos_;
  /**
   * <pre>
   * 问题列表
   * </pre>
   *
   * <code>repeated .po.QuestionInfo infos = 1;</code>
   */
  @java.lang.Override
  public java.util.List<po.QuestionInfo> getInfosList() {
    return infos_;
  }
  /**
   * <pre>
   * 问题列表
   * </pre>
   *
   * <code>repeated .po.QuestionInfo infos = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends po.QuestionInfoOrBuilder> 
      getInfosOrBuilderList() {
    return infos_;
  }
  /**
   * <pre>
   * 问题列表
   * </pre>
   *
   * <code>repeated .po.QuestionInfo infos = 1;</code>
   */
  @java.lang.Override
  public int getInfosCount() {
    return infos_.size();
  }
  /**
   * <pre>
   * 问题列表
   * </pre>
   *
   * <code>repeated .po.QuestionInfo infos = 1;</code>
   */
  @java.lang.Override
  public po.QuestionInfo getInfos(int index) {
    return infos_.get(index);
  }
  /**
   * <pre>
   * 问题列表
   * </pre>
   *
   * <code>repeated .po.QuestionInfo infos = 1;</code>
   */
  @java.lang.Override
  public po.QuestionInfoOrBuilder getInfosOrBuilder(
      int index) {
    return infos_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < infos_.size(); i++) {
      output.writeMessage(1, infos_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < infos_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, infos_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof po.ListQuestionRsp)) {
      return super.equals(obj);
    }
    po.ListQuestionRsp other = (po.ListQuestionRsp) obj;

    if (!getInfosList()
        .equals(other.getInfosList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getInfosCount() > 0) {
      hash = (37 * hash) + INFOS_FIELD_NUMBER;
      hash = (53 * hash) + getInfosList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static po.ListQuestionRsp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static po.ListQuestionRsp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static po.ListQuestionRsp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static po.ListQuestionRsp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static po.ListQuestionRsp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static po.ListQuestionRsp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static po.ListQuestionRsp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static po.ListQuestionRsp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static po.ListQuestionRsp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static po.ListQuestionRsp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static po.ListQuestionRsp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static po.ListQuestionRsp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(po.ListQuestionRsp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 获取问题列表 - 回执
   * </pre>
   *
   * Protobuf type {@code po.ListQuestionRsp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:po.ListQuestionRsp)
      po.ListQuestionRspOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return po.ProtocolProto.internal_static_po_ListQuestionRsp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return po.ProtocolProto.internal_static_po_ListQuestionRsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              po.ListQuestionRsp.class, po.ListQuestionRsp.Builder.class);
    }

    // Construct using po.ListQuestionRsp.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (infosBuilder_ == null) {
        infos_ = java.util.Collections.emptyList();
      } else {
        infos_ = null;
        infosBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return po.ProtocolProto.internal_static_po_ListQuestionRsp_descriptor;
    }

    @java.lang.Override
    public po.ListQuestionRsp getDefaultInstanceForType() {
      return po.ListQuestionRsp.getDefaultInstance();
    }

    @java.lang.Override
    public po.ListQuestionRsp build() {
      po.ListQuestionRsp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public po.ListQuestionRsp buildPartial() {
      po.ListQuestionRsp result = new po.ListQuestionRsp(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(po.ListQuestionRsp result) {
      if (infosBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          infos_ = java.util.Collections.unmodifiableList(infos_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.infos_ = infos_;
      } else {
        result.infos_ = infosBuilder_.build();
      }
    }

    private void buildPartial0(po.ListQuestionRsp result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof po.ListQuestionRsp) {
        return mergeFrom((po.ListQuestionRsp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(po.ListQuestionRsp other) {
      if (other == po.ListQuestionRsp.getDefaultInstance()) return this;
      if (infosBuilder_ == null) {
        if (!other.infos_.isEmpty()) {
          if (infos_.isEmpty()) {
            infos_ = other.infos_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureInfosIsMutable();
            infos_.addAll(other.infos_);
          }
          onChanged();
        }
      } else {
        if (!other.infos_.isEmpty()) {
          if (infosBuilder_.isEmpty()) {
            infosBuilder_.dispose();
            infosBuilder_ = null;
            infos_ = other.infos_;
            bitField0_ = (bitField0_ & ~0x00000001);
            infosBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetInfosFieldBuilder() : null;
          } else {
            infosBuilder_.addAllMessages(other.infos_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              po.QuestionInfo m =
                  input.readMessage(
                      po.QuestionInfo.parser(),
                      extensionRegistry);
              if (infosBuilder_ == null) {
                ensureInfosIsMutable();
                infos_.add(m);
              } else {
                infosBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<po.QuestionInfo> infos_ =
      java.util.Collections.emptyList();
    private void ensureInfosIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        infos_ = new java.util.ArrayList<po.QuestionInfo>(infos_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        po.QuestionInfo, po.QuestionInfo.Builder, po.QuestionInfoOrBuilder> infosBuilder_;

    /**
     * <pre>
     * 问题列表
     * </pre>
     *
     * <code>repeated .po.QuestionInfo infos = 1;</code>
     */
    public java.util.List<po.QuestionInfo> getInfosList() {
      if (infosBuilder_ == null) {
        return java.util.Collections.unmodifiableList(infos_);
      } else {
        return infosBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * 问题列表
     * </pre>
     *
     * <code>repeated .po.QuestionInfo infos = 1;</code>
     */
    public int getInfosCount() {
      if (infosBuilder_ == null) {
        return infos_.size();
      } else {
        return infosBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * 问题列表
     * </pre>
     *
     * <code>repeated .po.QuestionInfo infos = 1;</code>
     */
    public po.QuestionInfo getInfos(int index) {
      if (infosBuilder_ == null) {
        return infos_.get(index);
      } else {
        return infosBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * 问题列表
     * </pre>
     *
     * <code>repeated .po.QuestionInfo infos = 1;</code>
     */
    public Builder setInfos(
        int index, po.QuestionInfo value) {
      if (infosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInfosIsMutable();
        infos_.set(index, value);
        onChanged();
      } else {
        infosBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 问题列表
     * </pre>
     *
     * <code>repeated .po.QuestionInfo infos = 1;</code>
     */
    public Builder setInfos(
        int index, po.QuestionInfo.Builder builderForValue) {
      if (infosBuilder_ == null) {
        ensureInfosIsMutable();
        infos_.set(index, builderForValue.build());
        onChanged();
      } else {
        infosBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 问题列表
     * </pre>
     *
     * <code>repeated .po.QuestionInfo infos = 1;</code>
     */
    public Builder addInfos(po.QuestionInfo value) {
      if (infosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInfosIsMutable();
        infos_.add(value);
        onChanged();
      } else {
        infosBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * 问题列表
     * </pre>
     *
     * <code>repeated .po.QuestionInfo infos = 1;</code>
     */
    public Builder addInfos(
        int index, po.QuestionInfo value) {
      if (infosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInfosIsMutable();
        infos_.add(index, value);
        onChanged();
      } else {
        infosBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 问题列表
     * </pre>
     *
     * <code>repeated .po.QuestionInfo infos = 1;</code>
     */
    public Builder addInfos(
        po.QuestionInfo.Builder builderForValue) {
      if (infosBuilder_ == null) {
        ensureInfosIsMutable();
        infos_.add(builderForValue.build());
        onChanged();
      } else {
        infosBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 问题列表
     * </pre>
     *
     * <code>repeated .po.QuestionInfo infos = 1;</code>
     */
    public Builder addInfos(
        int index, po.QuestionInfo.Builder builderForValue) {
      if (infosBuilder_ == null) {
        ensureInfosIsMutable();
        infos_.add(index, builderForValue.build());
        onChanged();
      } else {
        infosBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 问题列表
     * </pre>
     *
     * <code>repeated .po.QuestionInfo infos = 1;</code>
     */
    public Builder addAllInfos(
        java.lang.Iterable<? extends po.QuestionInfo> values) {
      if (infosBuilder_ == null) {
        ensureInfosIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, infos_);
        onChanged();
      } else {
        infosBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * 问题列表
     * </pre>
     *
     * <code>repeated .po.QuestionInfo infos = 1;</code>
     */
    public Builder clearInfos() {
      if (infosBuilder_ == null) {
        infos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        infosBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 问题列表
     * </pre>
     *
     * <code>repeated .po.QuestionInfo infos = 1;</code>
     */
    public Builder removeInfos(int index) {
      if (infosBuilder_ == null) {
        ensureInfosIsMutable();
        infos_.remove(index);
        onChanged();
      } else {
        infosBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * 问题列表
     * </pre>
     *
     * <code>repeated .po.QuestionInfo infos = 1;</code>
     */
    public po.QuestionInfo.Builder getInfosBuilder(
        int index) {
      return internalGetInfosFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * 问题列表
     * </pre>
     *
     * <code>repeated .po.QuestionInfo infos = 1;</code>
     */
    public po.QuestionInfoOrBuilder getInfosOrBuilder(
        int index) {
      if (infosBuilder_ == null) {
        return infos_.get(index);  } else {
        return infosBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * 问题列表
     * </pre>
     *
     * <code>repeated .po.QuestionInfo infos = 1;</code>
     */
    public java.util.List<? extends po.QuestionInfoOrBuilder> 
         getInfosOrBuilderList() {
      if (infosBuilder_ != null) {
        return infosBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(infos_);
      }
    }
    /**
     * <pre>
     * 问题列表
     * </pre>
     *
     * <code>repeated .po.QuestionInfo infos = 1;</code>
     */
    public po.QuestionInfo.Builder addInfosBuilder() {
      return internalGetInfosFieldBuilder().addBuilder(
          po.QuestionInfo.getDefaultInstance());
    }
    /**
     * <pre>
     * 问题列表
     * </pre>
     *
     * <code>repeated .po.QuestionInfo infos = 1;</code>
     */
    public po.QuestionInfo.Builder addInfosBuilder(
        int index) {
      return internalGetInfosFieldBuilder().addBuilder(
          index, po.QuestionInfo.getDefaultInstance());
    }
    /**
     * <pre>
     * 问题列表
     * </pre>
     *
     * <code>repeated .po.QuestionInfo infos = 1;</code>
     */
    public java.util.List<po.QuestionInfo.Builder> 
         getInfosBuilderList() {
      return internalGetInfosFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        po.QuestionInfo, po.QuestionInfo.Builder, po.QuestionInfoOrBuilder> 
        internalGetInfosFieldBuilder() {
      if (infosBuilder_ == null) {
        infosBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            po.QuestionInfo, po.QuestionInfo.Builder, po.QuestionInfoOrBuilder>(
                infos_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        infos_ = null;
      }
      return infosBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:po.ListQuestionRsp)
  }

  // @@protoc_insertion_point(class_scope:po.ListQuestionRsp)
  private static final po.ListQuestionRsp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new po.ListQuestionRsp();
  }

  public static po.ListQuestionRsp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListQuestionRsp>
      PARSER = new com.google.protobuf.AbstractParser<ListQuestionRsp>() {
    @java.lang.Override
    public ListQuestionRsp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListQuestionRsp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListQuestionRsp> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public po.ListQuestionRsp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

