// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protocol.proto
// Protobuf Java Version: 4.33.2

package po;

@com.google.protobuf.Generated
public interface ListPeopleUpdateApplyReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:po.ListPeopleUpdateApplyReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 page = 1;</code>
   * @return Whether the page field is set.
   */
  boolean hasPage();
  /**
   * <code>optional int32 page = 1;</code>
   * @return The page.
   */
  int getPage();

  /**
   * <code>optional int32 size = 2;</code>
   * @return Whether the size field is set.
   */
  boolean hasSize();
  /**
   * <code>optional int32 size = 2;</code>
   * @return The size.
   */
  int getSize();

  /**
   * <code>optional int32 applyId = 3;</code>
   * @return Whether the applyId field is set.
   */
  boolean hasApplyId();
  /**
   * <code>optional int32 applyId = 3;</code>
   * @return The applyId.
   */
  int getApplyId();
}
