// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protocol.proto
// Protobuf Java Version: 4.33.2

package po;

/**
 * <pre>
 * 获取学习信息
 * </pre>
 *
 * Protobuf type {@code po.ListStudyReq}
 */
@com.google.protobuf.Generated
public final class ListStudyReq extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:po.ListStudyReq)
    ListStudyReqOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "ListStudyReq");
  }
  // Use ListStudyReq.newBuilder() to construct.
  private ListStudyReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ListStudyReq() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return po.ProtocolProto.internal_static_po_ListStudyReq_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return po.ProtocolProto.internal_static_po_ListStudyReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            po.ListStudyReq.class, po.ListStudyReq.Builder.class);
  }

  private int bitField0_;
  public static final int STUDYID_FIELD_NUMBER = 1;
  private int studyId_ = 0;
  /**
   * <pre>
   * 0则全部，一般进详情页掉这个，我会加阅读次数
   * </pre>
   *
   * <code>optional int32 studyId = 1;</code>
   * @return Whether the studyId field is set.
   */
  @java.lang.Override
  public boolean hasStudyId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * 0则全部，一般进详情页掉这个，我会加阅读次数
   * </pre>
   *
   * <code>optional int32 studyId = 1;</code>
   * @return The studyId.
   */
  @java.lang.Override
  public int getStudyId() {
    return studyId_;
  }

  public static final int PAGE_FIELD_NUMBER = 2;
  private int page_ = 0;
  /**
   * <code>optional int32 page = 2;</code>
   * @return Whether the page field is set.
   */
  @java.lang.Override
  public boolean hasPage() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional int32 page = 2;</code>
   * @return The page.
   */
  @java.lang.Override
  public int getPage() {
    return page_;
  }

  public static final int SIZE_FIELD_NUMBER = 3;
  private int size_ = 0;
  /**
   * <code>optional int32 size = 3;</code>
   * @return Whether the size field is set.
   */
  @java.lang.Override
  public boolean hasSize() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional int32 size = 3;</code>
   * @return The size.
   */
  @java.lang.Override
  public int getSize() {
    return size_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt32(1, studyId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt32(2, page_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeInt32(3, size_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, studyId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, page_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, size_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof po.ListStudyReq)) {
      return super.equals(obj);
    }
    po.ListStudyReq other = (po.ListStudyReq) obj;

    if (hasStudyId() != other.hasStudyId()) return false;
    if (hasStudyId()) {
      if (getStudyId()
          != other.getStudyId()) return false;
    }
    if (hasPage() != other.hasPage()) return false;
    if (hasPage()) {
      if (getPage()
          != other.getPage()) return false;
    }
    if (hasSize() != other.hasSize()) return false;
    if (hasSize()) {
      if (getSize()
          != other.getSize()) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasStudyId()) {
      hash = (37 * hash) + STUDYID_FIELD_NUMBER;
      hash = (53 * hash) + getStudyId();
    }
    if (hasPage()) {
      hash = (37 * hash) + PAGE_FIELD_NUMBER;
      hash = (53 * hash) + getPage();
    }
    if (hasSize()) {
      hash = (37 * hash) + SIZE_FIELD_NUMBER;
      hash = (53 * hash) + getSize();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static po.ListStudyReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static po.ListStudyReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static po.ListStudyReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static po.ListStudyReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static po.ListStudyReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static po.ListStudyReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static po.ListStudyReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static po.ListStudyReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static po.ListStudyReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static po.ListStudyReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static po.ListStudyReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static po.ListStudyReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(po.ListStudyReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 获取学习信息
   * </pre>
   *
   * Protobuf type {@code po.ListStudyReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:po.ListStudyReq)
      po.ListStudyReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return po.ProtocolProto.internal_static_po_ListStudyReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return po.ProtocolProto.internal_static_po_ListStudyReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              po.ListStudyReq.class, po.ListStudyReq.Builder.class);
    }

    // Construct using po.ListStudyReq.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    private int bitField0_;

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return po.ProtocolProto.internal_static_po_ListStudyReq_descriptor;
    }

    @java.lang.Override
    public po.ListStudyReq getDefaultInstanceForType() {
      return po.ListStudyReq.getDefaultInstance();
    }

    @java.lang.Override
    public po.ListStudyReq build() {
      po.ListStudyReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public po.ListStudyReq buildPartial() {
      po.ListStudyReq result = new po.ListStudyReq(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(po.ListStudyReq result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.studyId_ = studyId_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.page_ = page_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.size_ = size_;
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ |= to_bitField0_;
    }
    private int studyId_ ;

    public Builder mergeFrom(po.ListStudyReq other) {
      if (other == po.ListStudyReq.getDefaultInstance()) return this;
      if (other.hasStudyId()) {
        setStudyId(other.getStudyId());
      }
      if (other.hasPage()) {
        setPage(other.getPage());
      }
      if (other.hasSize()) {
        setSize(other.getSize());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }
    private int page_ ;

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              studyId_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              page_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              size_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int size_ ;

    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      studyId_ = 0;
      page_ = 0;
      size_ = 0;
      return this;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof po.ListStudyReq) {
        return mergeFrom((po.ListStudyReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    /**
     * <pre>
     * 0则全部，一般进详情页掉这个，我会加阅读次数
     * </pre>
     *
     * <code>optional int32 studyId = 1;</code>
     * @return Whether the studyId field is set.
     */
    @java.lang.Override
    public boolean hasStudyId() {
      return ((bitField0_ & 0x00000001) != 0);
    }

    /**
     * <pre>
     * 0则全部，一般进详情页掉这个，我会加阅读次数
     * </pre>
     *
     * <code>optional int32 studyId = 1;</code>
     * @return The studyId.
     */
    @java.lang.Override
    public int getStudyId() {
      return studyId_;
    }

    /**
     * <pre>
     * 0则全部，一般进详情页掉这个，我会加阅读次数
     * </pre>
     *
     * <code>optional int32 studyId = 1;</code>
     * @param value The studyId to set.
     * @return This builder for chaining.
     */
    public Builder setStudyId(int value) {

      studyId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 page = 2;</code>
     * @return Whether the page field is set.
     */
    @java.lang.Override
    public boolean hasPage() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 page = 2;</code>
     * @return The page.
     */
    @java.lang.Override
    public int getPage() {
      return page_;
    }
    /**
     * <code>optional int32 page = 2;</code>
     * @param value The page to set.
     * @return This builder for chaining.
     */
    public Builder setPage(int value) {

      page_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 page = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPage() {
      bitField0_ = (bitField0_ & ~0x00000002);
      page_ = 0;
      onChanged();
      return this;
    }

    /**
     * <pre>
     * 0则全部，一般进详情页掉这个，我会加阅读次数
     * </pre>
     *
     * <code>optional int32 studyId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStudyId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      studyId_ = 0;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 size = 3;</code>
     * @return Whether the size field is set.
     */
    @java.lang.Override
    public boolean hasSize() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 size = 3;</code>
     * @return The size.
     */
    @java.lang.Override
    public int getSize() {
      return size_;
    }
    /**
     * <code>optional int32 size = 3;</code>
     * @param value The size to set.
     * @return This builder for chaining.
     */
    public Builder setSize(int value) {

      size_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 size = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSize() {
      bitField0_ = (bitField0_ & ~0x00000004);
      size_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:po.ListStudyReq)
  }

  // @@protoc_insertion_point(class_scope:po.ListStudyReq)
  private static final po.ListStudyReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new po.ListStudyReq();
  }

  public static po.ListStudyReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListStudyReq>
      PARSER = new com.google.protobuf.AbstractParser<ListStudyReq>() {
    @java.lang.Override
    public ListStudyReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListStudyReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListStudyReq> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public po.ListStudyReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

