// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protocol.proto
// Protobuf Java Version: 4.33.2

package po;

@com.google.protobuf.Generated
public interface ListQuestionHandlingRspOrBuilder extends
    // @@protoc_insertion_point(interface_extends:po.ListQuestionHandlingRsp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 处理结果列表
   * </pre>
   *
   * <code>repeated .po.QuestionHandlingInfo infos = 1;</code>
   */
  java.util.List<po.QuestionHandlingInfo> 
      getInfosList();
  /**
   * <pre>
   * 处理结果列表
   * </pre>
   *
   * <code>repeated .po.QuestionHandlingInfo infos = 1;</code>
   */
  po.QuestionHandlingInfo getInfos(int index);
  /**
   * <pre>
   * 处理结果列表
   * </pre>
   *
   * <code>repeated .po.QuestionHandlingInfo infos = 1;</code>
   */
  int getInfosCount();
  /**
   * <pre>
   * 处理结果列表
   * </pre>
   *
   * <code>repeated .po.QuestionHandlingInfo infos = 1;</code>
   */
  java.util.List<? extends po.QuestionHandlingInfoOrBuilder> 
      getInfosOrBuilderList();
  /**
   * <pre>
   * 处理结果列表
   * </pre>
   *
   * <code>repeated .po.QuestionHandlingInfo infos = 1;</code>
   */
  po.QuestionHandlingInfoOrBuilder getInfosOrBuilder(
      int index);
}
