// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protocol.proto
// Protobuf Java Version: 4.29.3

package po;

public interface ListNoticeReadReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:po.ListNoticeReadReq)
    com.google.protobuf.MessageOrBuilder {
}
