// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protocol.proto
// Protobuf Java Version: 4.33.2

package po;

/**
 * <pre>
 * 获取已读 - 回执
 * </pre>
 *
 * Protobuf type {@code po.ListNoticeReadRsp}
 */
@com.google.protobuf.Generated
public final class ListNoticeReadRsp extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:po.ListNoticeReadRsp)
    ListNoticeReadRspOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "ListNoticeReadRsp");
  }
  // Use ListNoticeReadRsp.newBuilder() to construct.
  private ListNoticeReadRsp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ListNoticeReadRsp() {
    noticeList_ = emptyIntList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return po.ProtocolProto.internal_static_po_ListNoticeReadRsp_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return po.ProtocolProto.internal_static_po_ListNoticeReadRsp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            po.ListNoticeReadRsp.class, po.ListNoticeReadRsp.Builder.class);
  }

  public static final int NOTICELIST_FIELD_NUMBER = 1;
  // @@protoc_insertion_point(class_scope:po.ListNoticeReadRsp)
  private static final po.ListNoticeReadRsp DEFAULT_INSTANCE;
  /**
   * <pre>
   * 已读公告列表
   * </pre>
   *
   * <code>repeated int32 noticeList = 1;</code>
   * @return A list containing the noticeList.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
      getNoticeListList() {
    return noticeList_;
  }
  /**
   * <pre>
   * 已读公告列表
   * </pre>
   *
   * <code>repeated int32 noticeList = 1;</code>
   * @return The count of noticeList.
   */
  public int getNoticeListCount() {
    return noticeList_.size();
  }
  /**
   * <pre>
   * 已读公告列表
   * </pre>
   *
   * <code>repeated int32 noticeList = 1;</code>
   * @param index The index of the element to return.
   * @return The noticeList at the given index.
   */
  public int getNoticeList(int index) {
    return noticeList_.getInt(index);
  }
  private static final com.google.protobuf.Parser<ListNoticeReadRsp>
      PARSER = new com.google.protobuf.AbstractParser<ListNoticeReadRsp>() {
    @java.lang.Override
    public ListNoticeReadRsp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  static {
    DEFAULT_INSTANCE = new po.ListNoticeReadRsp();
  }
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getNoticeListList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(noticeListMemoizedSerializedSize);
    }
    for (int i = 0; i < noticeList_.size(); i++) {
      output.writeInt32NoTag(noticeList_.getInt(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < noticeList_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(noticeList_.getInt(i));
      }
      size += dataSize;
      if (!getNoticeListList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      noticeListMemoizedSerializedSize = dataSize;
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof po.ListNoticeReadRsp)) {
      return super.equals(obj);
    }
    po.ListNoticeReadRsp other = (po.ListNoticeReadRsp) obj;

    if (!getNoticeListList()
        .equals(other.getNoticeListList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getNoticeListCount() > 0) {
      hash = (37 * hash) + NOTICELIST_FIELD_NUMBER;
      hash = (53 * hash) + getNoticeListList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static po.ListNoticeReadRsp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static po.ListNoticeReadRsp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static po.ListNoticeReadRsp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static po.ListNoticeReadRsp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static po.ListNoticeReadRsp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static po.ListNoticeReadRsp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static po.ListNoticeReadRsp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static po.ListNoticeReadRsp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static po.ListNoticeReadRsp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static po.ListNoticeReadRsp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static po.ListNoticeReadRsp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static po.ListNoticeReadRsp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.IntList noticeList_ =
      emptyIntList();
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(po.ListNoticeReadRsp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  private int noticeListMemoizedSerializedSize = -1;
  private byte memoizedIsInitialized = -1;

  public static po.ListNoticeReadRsp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  public static com.google.protobuf.Parser<ListNoticeReadRsp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListNoticeReadRsp> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public po.ListNoticeReadRsp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

  /**
   * <pre>
   * 获取已读 - 回执
   * </pre>
   *
   * Protobuf type {@code po.ListNoticeReadRsp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:po.ListNoticeReadRsp)
      po.ListNoticeReadRspOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return po.ProtocolProto.internal_static_po_ListNoticeReadRsp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return po.ProtocolProto.internal_static_po_ListNoticeReadRsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              po.ListNoticeReadRsp.class, po.ListNoticeReadRsp.Builder.class);
    }

    private int bitField0_;
    private com.google.protobuf.Internal.IntList noticeList_ = emptyIntList();
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      noticeList_ = emptyIntList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return po.ProtocolProto.internal_static_po_ListNoticeReadRsp_descriptor;
    }

    @java.lang.Override
    public po.ListNoticeReadRsp getDefaultInstanceForType() {
      return po.ListNoticeReadRsp.getDefaultInstance();
    }

    @java.lang.Override
    public po.ListNoticeReadRsp build() {
      po.ListNoticeReadRsp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public po.ListNoticeReadRsp buildPartial() {
      po.ListNoticeReadRsp result = new po.ListNoticeReadRsp(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(po.ListNoticeReadRsp result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        noticeList_.makeImmutable();
        result.noticeList_ = noticeList_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof po.ListNoticeReadRsp) {
        return mergeFrom((po.ListNoticeReadRsp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(po.ListNoticeReadRsp other) {
      if (other == po.ListNoticeReadRsp.getDefaultInstance()) return this;
      if (!other.noticeList_.isEmpty()) {
        if (noticeList_.isEmpty()) {
          noticeList_ = other.noticeList_;
          noticeList_.makeImmutable();
          bitField0_ |= 0x00000001;
        } else {
          ensureNoticeListIsMutable();
          noticeList_.addAll(other.noticeList_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int v = input.readInt32();
              ensureNoticeListIsMutable();
              noticeList_.addInt(v);
              break;
            } // case 8
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureNoticeListIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                noticeList_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    // Construct using po.ListNoticeReadRsp.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    private void ensureNoticeListIsMutable() {
      if (!noticeList_.isModifiable()) {
        noticeList_ = makeMutableCopy(noticeList_);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <pre>
     * 已读公告列表
     * </pre>
     *
     * <code>repeated int32 noticeList = 1;</code>
     * @return A list containing the noticeList.
     */
    public java.util.List<java.lang.Integer>
        getNoticeListList() {
      noticeList_.makeImmutable();
      return noticeList_;
    }
    /**
     * <pre>
     * 已读公告列表
     * </pre>
     *
     * <code>repeated int32 noticeList = 1;</code>
     * @return The count of noticeList.
     */
    public int getNoticeListCount() {
      return noticeList_.size();
    }
    /**
     * <pre>
     * 已读公告列表
     * </pre>
     *
     * <code>repeated int32 noticeList = 1;</code>
     * @param index The index of the element to return.
     * @return The noticeList at the given index.
     */
    public int getNoticeList(int index) {
      return noticeList_.getInt(index);
    }
    /**
     * <pre>
     * 已读公告列表
     * </pre>
     *
     * <code>repeated int32 noticeList = 1;</code>
     * @param index The index to set the value at.
     * @param value The noticeList to set.
     * @return This builder for chaining.
     */
    public Builder setNoticeList(
        int index, int value) {

      ensureNoticeListIsMutable();
      noticeList_.setInt(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 已读公告列表
     * </pre>
     *
     * <code>repeated int32 noticeList = 1;</code>
     * @param value The noticeList to add.
     * @return This builder for chaining.
     */
    public Builder addNoticeList(int value) {

      ensureNoticeListIsMutable();
      noticeList_.addInt(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 已读公告列表
     * </pre>
     *
     * <code>repeated int32 noticeList = 1;</code>
     * @param values The noticeList to add.
     * @return This builder for chaining.
     */
    public Builder addAllNoticeList(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureNoticeListIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, noticeList_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 已读公告列表
     * </pre>
     *
     * <code>repeated int32 noticeList = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearNoticeList() {
      noticeList_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:po.ListNoticeReadRsp)
  }

}

