// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protocol.proto
// Protobuf Java Version: 4.33.2

package po;

/**
 * <pre>
 * 获取申请 - 回执
 * </pre>
 *
 * Protobuf type {@code po.ListPeopleUpdateApplyRsp}
 */
@com.google.protobuf.Generated
public final class ListPeopleUpdateApplyRsp extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:po.ListPeopleUpdateApplyRsp)
    ListPeopleUpdateApplyRspOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "ListPeopleUpdateApplyRsp");
  }
  // Use ListPeopleUpdateApplyRsp.newBuilder() to construct.
  private ListPeopleUpdateApplyRsp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ListPeopleUpdateApplyRsp() {
    apply_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return po.ProtocolProto.internal_static_po_ListPeopleUpdateApplyRsp_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return po.ProtocolProto.internal_static_po_ListPeopleUpdateApplyRsp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            po.ListPeopleUpdateApplyRsp.class, po.ListPeopleUpdateApplyRsp.Builder.class);
  }

  public static final int APPLY_FIELD_NUMBER = 1;
  // @@protoc_insertion_point(class_scope:po.ListPeopleUpdateApplyRsp)
  private static final po.ListPeopleUpdateApplyRsp DEFAULT_INSTANCE;
  /**
   * <pre>
   * 申请内容
   * </pre>
   *
   * <code>repeated .po.PeopleUpdateApply apply = 1;</code>
   */
  @java.lang.Override
  public java.util.List<po.PeopleUpdateApply> getApplyList() {
    return apply_;
  }
  private static final com.google.protobuf.Parser<ListPeopleUpdateApplyRsp>
      PARSER = new com.google.protobuf.AbstractParser<ListPeopleUpdateApplyRsp>() {
    @java.lang.Override
    public ListPeopleUpdateApplyRsp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };
  /**
   * <pre>
   * 申请内容
   * </pre>
   *
   * <code>repeated .po.PeopleUpdateApply apply = 1;</code>
   */
  @java.lang.Override
  public int getApplyCount() {
    return apply_.size();
  }
  /**
   * <pre>
   * 申请内容
   * </pre>
   *
   * <code>repeated .po.PeopleUpdateApply apply = 1;</code>
   */
  @java.lang.Override
  public po.PeopleUpdateApply getApply(int index) {
    return apply_.get(index);
  }
  /**
   * <pre>
   * 申请内容
   * </pre>
   *
   * <code>repeated .po.PeopleUpdateApply apply = 1;</code>
   */
  @java.lang.Override
  public po.PeopleUpdateApplyOrBuilder getApplyOrBuilder(
      int index) {
    return apply_.get(index);
  }

  static {
    DEFAULT_INSTANCE = new po.ListPeopleUpdateApplyRsp();
  }
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < apply_.size(); i++) {
      output.writeMessage(1, apply_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < apply_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, apply_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof po.ListPeopleUpdateApplyRsp)) {
      return super.equals(obj);
    }
    po.ListPeopleUpdateApplyRsp other = (po.ListPeopleUpdateApplyRsp) obj;

    if (!getApplyList()
        .equals(other.getApplyList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getApplyCount() > 0) {
      hash = (37 * hash) + APPLY_FIELD_NUMBER;
      hash = (53 * hash) + getApplyList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  @SuppressWarnings("serial")
  private java.util.List<po.PeopleUpdateApply> apply_;
  private byte memoizedIsInitialized = -1;

  public static po.ListPeopleUpdateApplyRsp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static po.ListPeopleUpdateApplyRsp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static po.ListPeopleUpdateApplyRsp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static po.ListPeopleUpdateApplyRsp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static po.ListPeopleUpdateApplyRsp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static po.ListPeopleUpdateApplyRsp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static po.ListPeopleUpdateApplyRsp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }

  public static po.ListPeopleUpdateApplyRsp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static po.ListPeopleUpdateApplyRsp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static po.ListPeopleUpdateApplyRsp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }

  public static po.ListPeopleUpdateApplyRsp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }

  public static po.ListPeopleUpdateApplyRsp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(po.ListPeopleUpdateApplyRsp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  public static po.ListPeopleUpdateApplyRsp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  public static com.google.protobuf.Parser<ListPeopleUpdateApplyRsp> parser() {
    return PARSER;
  }

  /**
   * <pre>
   * 申请内容
   * </pre>
   *
   * <code>repeated .po.PeopleUpdateApply apply = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends po.PeopleUpdateApplyOrBuilder>
      getApplyOrBuilderList() {
    return apply_;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListPeopleUpdateApplyRsp> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public po.ListPeopleUpdateApplyRsp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

  /**
   * <pre>
   * 获取申请 - 回执
   * </pre>
   *
   * Protobuf type {@code po.ListPeopleUpdateApplyRsp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:po.ListPeopleUpdateApplyRsp)
      po.ListPeopleUpdateApplyRspOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return po.ProtocolProto.internal_static_po_ListPeopleUpdateApplyRsp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return po.ProtocolProto.internal_static_po_ListPeopleUpdateApplyRsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              po.ListPeopleUpdateApplyRsp.class, po.ListPeopleUpdateApplyRsp.Builder.class);
    }

    private int bitField0_;
    private java.util.List<po.PeopleUpdateApply> apply_ =
      java.util.Collections.emptyList();
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (applyBuilder_ == null) {
        apply_ = java.util.Collections.emptyList();
      } else {
        apply_ = null;
        applyBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return po.ProtocolProto.internal_static_po_ListPeopleUpdateApplyRsp_descriptor;
    }

    @java.lang.Override
    public po.ListPeopleUpdateApplyRsp getDefaultInstanceForType() {
      return po.ListPeopleUpdateApplyRsp.getDefaultInstance();
    }

    @java.lang.Override
    public po.ListPeopleUpdateApplyRsp build() {
      po.ListPeopleUpdateApplyRsp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public po.ListPeopleUpdateApplyRsp buildPartial() {
      po.ListPeopleUpdateApplyRsp result = new po.ListPeopleUpdateApplyRsp(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(po.ListPeopleUpdateApplyRsp result) {
      if (applyBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          apply_ = java.util.Collections.unmodifiableList(apply_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.apply_ = apply_;
      } else {
        result.apply_ = applyBuilder_.build();
      }
    }

    private void buildPartial0(po.ListPeopleUpdateApplyRsp result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof po.ListPeopleUpdateApplyRsp) {
        return mergeFrom((po.ListPeopleUpdateApplyRsp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        po.PeopleUpdateApply, po.PeopleUpdateApply.Builder, po.PeopleUpdateApplyOrBuilder> applyBuilder_;

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              po.PeopleUpdateApply m =
                  input.readMessage(
                      po.PeopleUpdateApply.parser(),
                      extensionRegistry);
              if (applyBuilder_ == null) {
                ensureApplyIsMutable();
                apply_.add(m);
              } else {
                applyBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    // Construct using po.ListPeopleUpdateApplyRsp.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    private void ensureApplyIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        apply_ = new java.util.ArrayList<po.PeopleUpdateApply>(apply_);
        bitField0_ |= 0x00000001;
       }
    }

    public Builder mergeFrom(po.ListPeopleUpdateApplyRsp other) {
      if (other == po.ListPeopleUpdateApplyRsp.getDefaultInstance()) return this;
      if (applyBuilder_ == null) {
        if (!other.apply_.isEmpty()) {
          if (apply_.isEmpty()) {
            apply_ = other.apply_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureApplyIsMutable();
            apply_.addAll(other.apply_);
          }
          onChanged();
        }
      } else {
        if (!other.apply_.isEmpty()) {
          if (applyBuilder_.isEmpty()) {
            applyBuilder_.dispose();
            applyBuilder_ = null;
            apply_ = other.apply_;
            bitField0_ = (bitField0_ & ~0x00000001);
            applyBuilder_ =
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetApplyFieldBuilder() : null;
          } else {
            applyBuilder_.addAllMessages(other.apply_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    /**
     * <pre>
     * 申请内容
     * </pre>
     *
     * <code>repeated .po.PeopleUpdateApply apply = 1;</code>
     */
    public java.util.List<po.PeopleUpdateApply> getApplyList() {
      if (applyBuilder_ == null) {
        return java.util.Collections.unmodifiableList(apply_);
      } else {
        return applyBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * 申请内容
     * </pre>
     *
     * <code>repeated .po.PeopleUpdateApply apply = 1;</code>
     */
    public int getApplyCount() {
      if (applyBuilder_ == null) {
        return apply_.size();
      } else {
        return applyBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * 申请内容
     * </pre>
     *
     * <code>repeated .po.PeopleUpdateApply apply = 1;</code>
     */
    public po.PeopleUpdateApply getApply(int index) {
      if (applyBuilder_ == null) {
        return apply_.get(index);
      } else {
        return applyBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * 申请内容
     * </pre>
     *
     * <code>repeated .po.PeopleUpdateApply apply = 1;</code>
     */
    public Builder setApply(
        int index, po.PeopleUpdateApply value) {
      if (applyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureApplyIsMutable();
        apply_.set(index, value);
        onChanged();
      } else {
        applyBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 申请内容
     * </pre>
     *
     * <code>repeated .po.PeopleUpdateApply apply = 1;</code>
     */
    public Builder setApply(
        int index, po.PeopleUpdateApply.Builder builderForValue) {
      if (applyBuilder_ == null) {
        ensureApplyIsMutable();
        apply_.set(index, builderForValue.build());
        onChanged();
      } else {
        applyBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 申请内容
     * </pre>
     *
     * <code>repeated .po.PeopleUpdateApply apply = 1;</code>
     */
    public Builder addApply(po.PeopleUpdateApply value) {
      if (applyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureApplyIsMutable();
        apply_.add(value);
        onChanged();
      } else {
        applyBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * 申请内容
     * </pre>
     *
     * <code>repeated .po.PeopleUpdateApply apply = 1;</code>
     */
    public Builder addApply(
        int index, po.PeopleUpdateApply value) {
      if (applyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureApplyIsMutable();
        apply_.add(index, value);
        onChanged();
      } else {
        applyBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 申请内容
     * </pre>
     *
     * <code>repeated .po.PeopleUpdateApply apply = 1;</code>
     */
    public Builder addApply(
        po.PeopleUpdateApply.Builder builderForValue) {
      if (applyBuilder_ == null) {
        ensureApplyIsMutable();
        apply_.add(builderForValue.build());
        onChanged();
      } else {
        applyBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 申请内容
     * </pre>
     *
     * <code>repeated .po.PeopleUpdateApply apply = 1;</code>
     */
    public Builder addApply(
        int index, po.PeopleUpdateApply.Builder builderForValue) {
      if (applyBuilder_ == null) {
        ensureApplyIsMutable();
        apply_.add(index, builderForValue.build());
        onChanged();
      } else {
        applyBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 申请内容
     * </pre>
     *
     * <code>repeated .po.PeopleUpdateApply apply = 1;</code>
     */
    public Builder addAllApply(
        java.lang.Iterable<? extends po.PeopleUpdateApply> values) {
      if (applyBuilder_ == null) {
        ensureApplyIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, apply_);
        onChanged();
      } else {
        applyBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * 申请内容
     * </pre>
     *
     * <code>repeated .po.PeopleUpdateApply apply = 1;</code>
     */
    public Builder clearApply() {
      if (applyBuilder_ == null) {
        apply_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        applyBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 申请内容
     * </pre>
     *
     * <code>repeated .po.PeopleUpdateApply apply = 1;</code>
     */
    public Builder removeApply(int index) {
      if (applyBuilder_ == null) {
        ensureApplyIsMutable();
        apply_.remove(index);
        onChanged();
      } else {
        applyBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * 申请内容
     * </pre>
     *
     * <code>repeated .po.PeopleUpdateApply apply = 1;</code>
     */
    public po.PeopleUpdateApply.Builder getApplyBuilder(
        int index) {
      return internalGetApplyFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * 申请内容
     * </pre>
     *
     * <code>repeated .po.PeopleUpdateApply apply = 1;</code>
     */
    public po.PeopleUpdateApplyOrBuilder getApplyOrBuilder(
        int index) {
      if (applyBuilder_ == null) {
        return apply_.get(index);  } else {
        return applyBuilder_.getMessageOrBuilder(index);
      }
    }

    /**
     * <pre>
     * 申请内容
     * </pre>
     *
     * <code>repeated .po.PeopleUpdateApply apply = 1;</code>
     */
    public java.util.List<? extends po.PeopleUpdateApplyOrBuilder>
         getApplyOrBuilderList() {
      if (applyBuilder_ != null) {
        return applyBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(apply_);
      }
    }
    /**
     * <pre>
     * 申请内容
     * </pre>
     *
     * <code>repeated .po.PeopleUpdateApply apply = 1;</code>
     */
    public po.PeopleUpdateApply.Builder addApplyBuilder() {
      return internalGetApplyFieldBuilder().addBuilder(
          po.PeopleUpdateApply.getDefaultInstance());
    }
    /**
     * <pre>
     * 申请内容
     * </pre>
     *
     * <code>repeated .po.PeopleUpdateApply apply = 1;</code>
     */
    public po.PeopleUpdateApply.Builder addApplyBuilder(
        int index) {
      return internalGetApplyFieldBuilder().addBuilder(
          index, po.PeopleUpdateApply.getDefaultInstance());
    }
    /**
     * <pre>
     * 申请内容
     * </pre>
     *
     * <code>repeated .po.PeopleUpdateApply apply = 1;</code>
     */
    public java.util.List<po.PeopleUpdateApply.Builder>
         getApplyBuilderList() {
      return internalGetApplyFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        po.PeopleUpdateApply, po.PeopleUpdateApply.Builder, po.PeopleUpdateApplyOrBuilder>
        internalGetApplyFieldBuilder() {
      if (applyBuilder_ == null) {
        applyBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            po.PeopleUpdateApply, po.PeopleUpdateApply.Builder, po.PeopleUpdateApplyOrBuilder>(
                apply_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        apply_ = null;
      }
      return applyBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:po.ListPeopleUpdateApplyRsp)
  }

}

