// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protocol.proto
// Protobuf Java Version: 4.33.2

package po;

@com.google.protobuf.Generated
public interface ListNoticeReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:po.ListNoticeReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 公告ID，不填或填0代表拉去所有
   * </pre>
   *
   * <code>optional int32 noticeId = 1;</code>
   * @return Whether the noticeId field is set.
   */
  boolean hasNoticeId();
  /**
   * <pre>
   * 公告ID，不填或填0代表拉去所有
   * </pre>
   *
   * <code>optional int32 noticeId = 1;</code>
   * @return The noticeId.
   */
  int getNoticeId();

  /**
   * <pre>
   * 第几页
   * </pre>
   *
   * <code>optional int32 page = 2;</code>
   * @return Whether the page field is set.
   */
  boolean hasPage();
  /**
   * <pre>
   * 第几页
   * </pre>
   *
   * <code>optional int32 page = 2;</code>
   * @return The page.
   */
  int getPage();

  /**
   * <pre>
   * 几条
   * </pre>
   *
   * <code>optional int32 size = 3;</code>
   * @return Whether the size field is set.
   */
  boolean hasSize();
  /**
   * <pre>
   * 几条
   * </pre>
   *
   * <code>optional int32 size = 3;</code>
   * @return The size.
   */
  int getSize();
}
