// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protocol.proto
// Protobuf Java Version: 4.33.2

package po;

/**
 * <pre>
 * 登录
 * </pre>
 *
 * Protobuf type {@code po.LoginReq}
 */
@com.google.protobuf.Generated
public final class LoginReq extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:po.LoginReq)
    LoginReqOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "LoginReq");
  }
  // Use LoginReq.newBuilder() to construct.
  private LoginReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private LoginReq() {
    userPwd_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return po.ProtocolProto.internal_static_po_LoginReq_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return po.ProtocolProto.internal_static_po_LoginReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            po.LoginReq.class, po.LoginReq.Builder.class);
  }

  private int bitField0_;
  public static final int USERTEL_FIELD_NUMBER = 1;
  private long userTel_ = 0L;
  /**
   * <code>optional int64 userTel = 1;</code>
   * @return Whether the userTel field is set.
   */
  @java.lang.Override
  public boolean hasUserTel() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional int64 userTel = 1;</code>
   * @return The userTel.
   */
  @java.lang.Override
  public long getUserTel() {
    return userTel_;
  }

  public static final int USERPWD_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object userPwd_ = "";
  /**
   * <pre>
   * 用户密码
   * </pre>
   *
   * <code>optional string userPwd = 2;</code>
   * @return Whether the userPwd field is set.
   */
  @java.lang.Override
  public boolean hasUserPwd() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * 用户密码
   * </pre>
   *
   * <code>optional string userPwd = 2;</code>
   * @return The userPwd.
   */
  @java.lang.Override
  public java.lang.String getUserPwd() {
    java.lang.Object ref = userPwd_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userPwd_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 用户密码
   * </pre>
   *
   * <code>optional string userPwd = 2;</code>
   * @return The bytes for userPwd.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserPwdBytes() {
    java.lang.Object ref = userPwd_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userPwd_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt64(1, userTel_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, userPwd_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, userTel_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, userPwd_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof po.LoginReq)) {
      return super.equals(obj);
    }
    po.LoginReq other = (po.LoginReq) obj;

    if (hasUserTel() != other.hasUserTel()) return false;
    if (hasUserTel()) {
      if (getUserTel()
          != other.getUserTel()) return false;
    }
    if (hasUserPwd() != other.hasUserPwd()) return false;
    if (hasUserPwd()) {
      if (!getUserPwd()
          .equals(other.getUserPwd())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasUserTel()) {
      hash = (37 * hash) + USERTEL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserTel());
    }
    if (hasUserPwd()) {
      hash = (37 * hash) + USERPWD_FIELD_NUMBER;
      hash = (53 * hash) + getUserPwd().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static po.LoginReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static po.LoginReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static po.LoginReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static po.LoginReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static po.LoginReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static po.LoginReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static po.LoginReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static po.LoginReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static po.LoginReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static po.LoginReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static po.LoginReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static po.LoginReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(po.LoginReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 登录
   * </pre>
   *
   * Protobuf type {@code po.LoginReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:po.LoginReq)
      po.LoginReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return po.ProtocolProto.internal_static_po_LoginReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return po.ProtocolProto.internal_static_po_LoginReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              po.LoginReq.class, po.LoginReq.Builder.class);
    }

    // Construct using po.LoginReq.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    private int bitField0_;

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return po.ProtocolProto.internal_static_po_LoginReq_descriptor;
    }

    @java.lang.Override
    public po.LoginReq getDefaultInstanceForType() {
      return po.LoginReq.getDefaultInstance();
    }

    @java.lang.Override
    public po.LoginReq build() {
      po.LoginReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public po.LoginReq buildPartial() {
      po.LoginReq result = new po.LoginReq(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(po.LoginReq result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.userTel_ = userTel_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.userPwd_ = userPwd_;
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof po.LoginReq) {
        return mergeFrom((po.LoginReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(po.LoginReq other) {
      if (other == po.LoginReq.getDefaultInstance()) return this;
      if (other.hasUserTel()) {
        setUserTel(other.getUserTel());
      }
      if (other.hasUserPwd()) {
        userPwd_ = other.userPwd_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              userTel_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              userPwd_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private long userTel_ ;

    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      userTel_ = 0L;
      userPwd_ = "";
      return this;
    }
    /**
     * <code>optional int64 userTel = 1;</code>
     * @return Whether the userTel field is set.
     */
    @java.lang.Override
    public boolean hasUserTel() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int64 userTel = 1;</code>
     * @return The userTel.
     */
    @java.lang.Override
    public long getUserTel() {
      return userTel_;
    }
    /**
     * <code>optional int64 userTel = 1;</code>
     * @param value The userTel to set.
     * @return This builder for chaining.
     */
    public Builder setUserTel(long value) {

      userTel_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 userTel = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserTel() {
      bitField0_ = (bitField0_ & ~0x00000001);
      userTel_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object userPwd_ = "";
    /**
     * <pre>
     * 用户密码
     * </pre>
     *
     * <code>optional string userPwd = 2;</code>
     * @return Whether the userPwd field is set.
     */
    public boolean hasUserPwd() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * 用户密码
     * </pre>
     *
     * <code>optional string userPwd = 2;</code>
     * @return The userPwd.
     */
    public java.lang.String getUserPwd() {
      java.lang.Object ref = userPwd_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userPwd_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 用户密码
     * </pre>
     *
     * <code>optional string userPwd = 2;</code>
     * @return The bytes for userPwd.
     */
    public com.google.protobuf.ByteString
        getUserPwdBytes() {
      java.lang.Object ref = userPwd_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userPwd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 用户密码
     * </pre>
     *
     * <code>optional string userPwd = 2;</code>
     * @param value The userPwd to set.
     * @return This builder for chaining.
     */
    public Builder setUserPwd(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      userPwd_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户密码
     * </pre>
     *
     * <code>optional string userPwd = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserPwd() {
      userPwd_ = getDefaultInstance().getUserPwd();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户密码
     * </pre>
     *
     * <code>optional string userPwd = 2;</code>
     * @param value The bytes for userPwd to set.
     * @return This builder for chaining.
     */
    public Builder setUserPwdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      userPwd_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:po.LoginReq)
  }

  // @@protoc_insertion_point(class_scope:po.LoginReq)
  private static final po.LoginReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new po.LoginReq();
  }

  public static po.LoginReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LoginReq>
      PARSER = new com.google.protobuf.AbstractParser<LoginReq>() {
    @java.lang.Override
    public LoginReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<LoginReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LoginReq> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public po.LoginReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

