// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: base.proto
// Protobuf Java Version: 4.33.2

package po;

/**
 * <pre>
 * 消息类型
 * </pre>
 *
 * Protobuf enum {@code po.MsgType}
 */
@com.google.protobuf.Generated
public enum MsgType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * 默认
   * </pre>
   *
   * <code>TMT_DEFAULT = 0;</code>
   */
  TMT_DEFAULT(0),
  /**
   * <pre>
   * 测试请求体
   * </pre>
   *
   * <code>TMT_TEST = 1;</code>
   */
  TMT_TEST(1),
  /**
   * <pre>
   * 测试返回体
   * </pre>
   *
   * <code>TMT_TEST_RESP = 2;</code>
   */
  TMT_TEST_RESP(2),
  /**
   * <pre>
   * 登录请求
   * </pre>
   *
   * <code>TMT_LoginReq = 3;</code>
   */
  TMT_LoginReq(3),
  /**
   * <pre>
   * 登录返回
   * </pre>
   *
   * <code>TMT_LoginRsp = 4;</code>
   */
  TMT_LoginRsp(4),
  /**
   * <pre>
   * 注册请求
   * </pre>
   *
   * <code>TMT_RegisterReq = 5;</code>
   */
  TMT_RegisterReq(5),
  /**
   * <pre>
   * 注册返回
   * </pre>
   *
   * <code>TMT_RegisterRsp = 6;</code>
   */
  TMT_RegisterRsp(6),
  /**
   * <pre>
   * 修改用户信息（管理员）
   * </pre>
   *
   * <code>TMT_UpdateUserInfoReq = 7;</code>
   */
  TMT_UpdateUserInfoReq(7),
  /**
   * <pre>
   * 修改用户信息（管理员） - 回执
   * </pre>
   *
   * <code>TMT_UpdateUserInfoRsp = 8;</code>
   */
  TMT_UpdateUserInfoRsp(8),
  /**
   * <pre>
   * 发布公告（管理员）
   * </pre>
   *
   * <code>TMT_CreateNoticeReq = 9;</code>
   */
  TMT_CreateNoticeReq(9),
  /**
   * <pre>
   * 发布公告（管理员） - 回执
   * </pre>
   *
   * <code>TMT_CreateNoticeRsp = 10;</code>
   */
  TMT_CreateNoticeRsp(10),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "MsgType");
  }
  /**
   * <pre>
   * 默认
   * </pre>
   *
   * <code>TMT_DEFAULT = 0;</code>
   */
  public static final int TMT_DEFAULT_VALUE = 0;
  /**
   * <pre>
   * 测试请求体
   * </pre>
   *
   * <code>TMT_TEST = 1;</code>
   */
  public static final int TMT_TEST_VALUE = 1;
  /**
   * <pre>
   * 测试返回体
   * </pre>
   *
   * <code>TMT_TEST_RESP = 2;</code>
   */
  public static final int TMT_TEST_RESP_VALUE = 2;
  /**
   * <pre>
   * 登录请求
   * </pre>
   *
   * <code>TMT_LoginReq = 3;</code>
   */
  public static final int TMT_LoginReq_VALUE = 3;
  /**
   * <pre>
   * 登录返回
   * </pre>
   *
   * <code>TMT_LoginRsp = 4;</code>
   */
  public static final int TMT_LoginRsp_VALUE = 4;
  /**
   * <pre>
   * 注册请求
   * </pre>
   *
   * <code>TMT_RegisterReq = 5;</code>
   */
  public static final int TMT_RegisterReq_VALUE = 5;
  /**
   * <pre>
   * 注册返回
   * </pre>
   *
   * <code>TMT_RegisterRsp = 6;</code>
   */
  public static final int TMT_RegisterRsp_VALUE = 6;
  /**
   * <pre>
   * 修改用户信息（管理员）
   * </pre>
   *
   * <code>TMT_UpdateUserInfoReq = 7;</code>
   */
  public static final int TMT_UpdateUserInfoReq_VALUE = 7;
  /**
   * <pre>
   * 修改用户信息（管理员） - 回执
   * </pre>
   *
   * <code>TMT_UpdateUserInfoRsp = 8;</code>
   */
  public static final int TMT_UpdateUserInfoRsp_VALUE = 8;
  /**
   * <pre>
   * 发布公告（管理员）
   * </pre>
   *
   * <code>TMT_CreateNoticeReq = 9;</code>
   */
  public static final int TMT_CreateNoticeReq_VALUE = 9;
  /**
   * <pre>
   * 发布公告（管理员） - 回执
   * </pre>
   *
   * <code>TMT_CreateNoticeRsp = 10;</code>
   */
  public static final int TMT_CreateNoticeRsp_VALUE = 10;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static MsgType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static MsgType forNumber(int value) {
    switch (value) {
      case 0: return TMT_DEFAULT;
      case 1: return TMT_TEST;
      case 2: return TMT_TEST_RESP;
      case 3: return TMT_LoginReq;
      case 4: return TMT_LoginRsp;
      case 5: return TMT_RegisterReq;
      case 6: return TMT_RegisterRsp;
      case 7: return TMT_UpdateUserInfoReq;
      case 8: return TMT_UpdateUserInfoRsp;
      case 9: return TMT_CreateNoticeReq;
      case 10: return TMT_CreateNoticeRsp;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      MsgType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
          public MsgType findValueByNumber(int number) {
            return MsgType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return po.BaseProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final MsgType[] VALUES = values();

  public static MsgType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private MsgType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:po.MsgType)
}

