// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: entity.proto
// Protobuf Java Version: 4.33.2

package po;

@com.google.protobuf.Generated
public interface NoticeInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:po.NoticeInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 公告idE
   * </pre>
   *
   * <code>optional int64 noticeId = 1;</code>
   * @return Whether the noticeId field is set.
   */
  boolean hasNoticeId();
  /**
   * <pre>
   * 公告idE
   * </pre>
   *
   * <code>optional int64 noticeId = 1;</code>
   * @return The noticeId.
   */
  long getNoticeId();

  /**
   * <pre>
   * 公告类型
   * </pre>
   *
   * <code>optional .po.TNoticeType noticeType = 2;</code>
   * @return Whether the noticeType field is set.
   */
  boolean hasNoticeType();
  /**
   * <pre>
   * 公告类型
   * </pre>
   *
   * <code>optional .po.TNoticeType noticeType = 2;</code>
   * @return The enum numeric value on the wire for noticeType.
   */
  int getNoticeTypeValue();
  /**
   * <pre>
   * 公告类型
   * </pre>
   *
   * <code>optional .po.TNoticeType noticeType = 2;</code>
   * @return The noticeType.
   */
  po.TNoticeType getNoticeType();

  /**
   * <pre>
   * 公告发布时间，MS时间戳
   * </pre>
   *
   * <code>optional int64 noticeCreateTime = 3;</code>
   * @return Whether the noticeCreateTime field is set.
   */
  boolean hasNoticeCreateTime();
  /**
   * <pre>
   * 公告发布时间，MS时间戳
   * </pre>
   *
   * <code>optional int64 noticeCreateTime = 3;</code>
   * @return The noticeCreateTime.
   */
  long getNoticeCreateTime();

  /**
   * <pre>
   * 公告标题
   * </pre>
   *
   * <code>optional string noticeTitle = 4;</code>
   * @return Whether the noticeTitle field is set.
   */
  boolean hasNoticeTitle();
  /**
   * <pre>
   * 公告标题
   * </pre>
   *
   * <code>optional string noticeTitle = 4;</code>
   * @return The noticeTitle.
   */
  java.lang.String getNoticeTitle();
  /**
   * <pre>
   * 公告标题
   * </pre>
   *
   * <code>optional string noticeTitle = 4;</code>
   * @return The bytes for noticeTitle.
   */
  com.google.protobuf.ByteString
      getNoticeTitleBytes();

  /**
   * <pre>
   * 公告正文
   * </pre>
   *
   * <code>optional string noticeContext = 5;</code>
   * @return Whether the noticeContext field is set.
   */
  boolean hasNoticeContext();
  /**
   * <pre>
   * 公告正文
   * </pre>
   *
   * <code>optional string noticeContext = 5;</code>
   * @return The noticeContext.
   */
  java.lang.String getNoticeContext();
  /**
   * <pre>
   * 公告正文
   * </pre>
   *
   * <code>optional string noticeContext = 5;</code>
   * @return The bytes for noticeContext.
   */
  com.google.protobuf.ByteString
      getNoticeContextBytes();

  /**
   * <pre>
   * 发布者电话
   * </pre>
   *
   * <code>optional int32 writerTel = 6;</code>
   * @return Whether the writerTel field is set.
   */
  boolean hasWriterTel();
  /**
   * <pre>
   * 发布者电话
   * </pre>
   *
   * <code>optional int32 writerTel = 6;</code>
   * @return The writerTel.
   */
  int getWriterTel();

  /**
   * <pre>
   * 发布者姓名
   * </pre>
   *
   * <code>optional string writerName = 7;</code>
   * @return Whether the writerName field is set.
   */
  boolean hasWriterName();
  /**
   * <pre>
   * 发布者姓名
   * </pre>
   *
   * <code>optional string writerName = 7;</code>
   * @return The writerName.
   */
  java.lang.String getWriterName();
  /**
   * <pre>
   * 发布者姓名
   * </pre>
   *
   * <code>optional string writerName = 7;</code>
   * @return The bytes for writerName.
   */
  com.google.protobuf.ByteString
      getWriterNameBytes();

  /**
   * <pre>
   * 是否置顶
   * </pre>
   *
   * <code>optional bool isTop = 8;</code>
   * @return Whether the isTop field is set.
   */
  boolean hasIsTop();
  /**
   * <pre>
   * 是否置顶
   * </pre>
   *
   * <code>optional bool isTop = 8;</code>
   * @return The isTop.
   */
  boolean getIsTop();

  /**
   * <pre>
   * 是否需要确认阅读
   * </pre>
   *
   * <code>optional bool isAcceptRead = 9;</code>
   * @return Whether the isAcceptRead field is set.
   */
  boolean hasIsAcceptRead();
  /**
   * <pre>
   * 是否需要确认阅读
   * </pre>
   *
   * <code>optional bool isAcceptRead = 9;</code>
   * @return The isAcceptRead.
   */
  boolean getIsAcceptRead();

  /**
   * <pre>
   * 公告附件-直接就是二进制文件
   * </pre>
   *
   * <code>repeated bytes noticeAtt = 10;</code>
   * @return A list containing the noticeAtt.
   */
  java.util.List<com.google.protobuf.ByteString> getNoticeAttList();
  /**
   * <pre>
   * 公告附件-直接就是二进制文件
   * </pre>
   *
   * <code>repeated bytes noticeAtt = 10;</code>
   * @return The count of noticeAtt.
   */
  int getNoticeAttCount();
  /**
   * <pre>
   * 公告附件-直接就是二进制文件
   * </pre>
   *
   * <code>repeated bytes noticeAtt = 10;</code>
   * @param index The index of the element to return.
   * @return The noticeAtt at the given index.
   */
  com.google.protobuf.ByteString getNoticeAtt(int index);
}
