// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: entity.proto
// Protobuf Java Version: 4.33.2

package po;

@com.google.protobuf.Generated
public interface PeopleUpdateApplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:po.PeopleUpdateApply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 自增唯一id
   * </pre>
   *
   * <code>optional int32 applyId = 1;</code>
   * @return Whether the applyId field is set.
   */
  boolean hasApplyId();
  /**
   * <pre>
   * 自增唯一id
   * </pre>
   *
   * <code>optional int32 applyId = 1;</code>
   * @return The applyId.
   */
  int getApplyId();

  /**
   * <pre>
   * 申请人电话
   * </pre>
   *
   * <code>optional int32 applyUserId = 2;</code>
   * @return Whether the applyUserId field is set.
   */
  boolean hasApplyUserId();
  /**
   * <pre>
   * 申请人电话
   * </pre>
   *
   * <code>optional int32 applyUserId = 2;</code>
   * @return The applyUserId.
   */
  int getApplyUserId();

  /**
   * <pre>
   * 申请时间
   * </pre>
   *
   * <code>optional int64 applyCreateTime = 3;</code>
   * @return Whether the applyCreateTime field is set.
   */
  boolean hasApplyCreateTime();
  /**
   * <pre>
   * 申请时间
   * </pre>
   *
   * <code>optional int64 applyCreateTime = 3;</code>
   * @return The applyCreateTime.
   */
  long getApplyCreateTime();

  /**
   * <pre>
   * PeopleInfo的序列化后内容
   * </pre>
   *
   * <code>optional bytes newPeople = 4;</code>
   * @return Whether the newPeople field is set.
   */
  boolean hasNewPeople();
  /**
   * <pre>
   * PeopleInfo的序列化后内容
   * </pre>
   *
   * <code>optional bytes newPeople = 4;</code>
   * @return The newPeople.
   */
  com.google.protobuf.ByteString getNewPeople();
}
