// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: entity.proto
// Protobuf Java Version: 4.33.2

package po;

@com.google.protobuf.Generated
public interface QuestionInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:po.QuestionInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 自增唯一id
   * </pre>
   *
   * <code>optional int32 questionId = 1;</code>
   * @return Whether the questionId field is set.
   */
  boolean hasQuestionId();
  /**
   * <pre>
   * 自增唯一id
   * </pre>
   *
   * <code>optional int32 questionId = 1;</code>
   * @return The questionId.
   */
  int getQuestionId();

  /**
   * <pre>
   * 问题类型
   * </pre>
   *
   * <code>optional .po.QuestionType questionType = 2;</code>
   * @return Whether the questionType field is set.
   */
  boolean hasQuestionType();
  /**
   * <pre>
   * 问题类型
   * </pre>
   *
   * <code>optional .po.QuestionType questionType = 2;</code>
   * @return The enum numeric value on the wire for questionType.
   */
  int getQuestionTypeValue();
  /**
   * <pre>
   * 问题类型
   * </pre>
   *
   * <code>optional .po.QuestionType questionType = 2;</code>
   * @return The questionType.
   */
  po.QuestionType getQuestionType();

  /**
   * <pre>
   * 问题详细描述
   * </pre>
   *
   * <code>optional string questionCtx = 3;</code>
   * @return Whether the questionCtx field is set.
   */
  boolean hasQuestionCtx();
  /**
   * <pre>
   * 问题详细描述
   * </pre>
   *
   * <code>optional string questionCtx = 3;</code>
   * @return The questionCtx.
   */
  java.lang.String getQuestionCtx();
  /**
   * <pre>
   * 问题详细描述
   * </pre>
   *
   * <code>optional string questionCtx = 3;</code>
   * @return The bytes for questionCtx.
   */
  com.google.protobuf.ByteString
      getQuestionCtxBytes();

  /**
   * <pre>
   * 问题上传附件
   * </pre>
   *
   * <code>optional bytes questPhoto = 4;</code>
   * @return Whether the questPhoto field is set.
   */
  boolean hasQuestPhoto();
  /**
   * <pre>
   * 问题上传附件
   * </pre>
   *
   * <code>optional bytes questPhoto = 4;</code>
   * @return The questPhoto.
   */
  com.google.protobuf.ByteString getQuestPhoto();

  /**
   * <pre>
   * 问题提出者电话
   * </pre>
   *
   * <code>optional int64 questionWriterTel = 5;</code>
   * @return Whether the questionWriterTel field is set.
   */
  boolean hasQuestionWriterTel();
  /**
   * <pre>
   * 问题提出者电话
   * </pre>
   *
   * <code>optional int64 questionWriterTel = 5;</code>
   * @return The questionWriterTel.
   */
  long getQuestionWriterTel();

  /**
   * <pre>
   * 问题节点
   * </pre>
   *
   * <code>optional .po.QuestionNodeType nodeType = 6;</code>
   * @return Whether the nodeType field is set.
   */
  boolean hasNodeType();
  /**
   * <pre>
   * 问题节点
   * </pre>
   *
   * <code>optional .po.QuestionNodeType nodeType = 6;</code>
   * @return The enum numeric value on the wire for nodeType.
   */
  int getNodeTypeValue();
  /**
   * <pre>
   * 问题节点
   * </pre>
   *
   * <code>optional .po.QuestionNodeType nodeType = 6;</code>
   * @return The nodeType.
   */
  po.QuestionNodeType getNodeType();

  /**
   * <pre>
   * 指定处理人电话
   * </pre>
   *
   * <code>optional int64 choiceUser = 7;</code>
   * @return Whether the choiceUser field is set.
   */
  boolean hasChoiceUser();
  /**
   * <pre>
   * 指定处理人电话
   * </pre>
   *
   * <code>optional int64 choiceUser = 7;</code>
   * @return The choiceUser.
   */
  long getChoiceUser();

  /**
   * <pre>
   * 问题时间
   * </pre>
   *
   * <code>optional int64 questionTime = 8;</code>
   * @return Whether the questionTime field is set.
   */
  boolean hasQuestionTime();
  /**
   * <pre>
   * 问题时间
   * </pre>
   *
   * <code>optional int64 questionTime = 8;</code>
   * @return The questionTime.
   */
  long getQuestionTime();
}
