// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: entity.proto
// Protobuf Java Version: 4.33.2

package po;

/**
 * <pre>
 * 问题处理节点
 * </pre>
 *
 * Protobuf enum {@code po.QuestionNodeType}
 */
@com.google.protobuf.Generated
public enum QuestionNodeType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * 待处理
   * </pre>
   *
   * <code>TQNT_PRE = 0;</code>
   */
  TQNT_PRE(0),
  /**
   * <pre>
   * 处理中
   * </pre>
   *
   * <code>TQNT_MID = 1;</code>
   */
  TQNT_MID(1),
  /**
   * <pre>
   * 已处理
   * </pre>
   *
   * <code>TQNT_TAIL = 2;</code>
   */
  TQNT_TAIL(2),
  /**
   * <pre>
   * 问题不处理
   * </pre>
   *
   * <code>TQNT_CLOSE = 3;</code>
   */
  TQNT_CLOSE(3),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "QuestionNodeType");
  }
  /**
   * <pre>
   * 待处理
   * </pre>
   *
   * <code>TQNT_PRE = 0;</code>
   */
  public static final int TQNT_PRE_VALUE = 0;
  /**
   * <pre>
   * 处理中
   * </pre>
   *
   * <code>TQNT_MID = 1;</code>
   */
  public static final int TQNT_MID_VALUE = 1;
  /**
   * <pre>
   * 已处理
   * </pre>
   *
   * <code>TQNT_TAIL = 2;</code>
   */
  public static final int TQNT_TAIL_VALUE = 2;
  /**
   * <pre>
   * 问题不处理
   * </pre>
   *
   * <code>TQNT_CLOSE = 3;</code>
   */
  public static final int TQNT_CLOSE_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static QuestionNodeType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static QuestionNodeType forNumber(int value) {
    switch (value) {
      case 0: return TQNT_PRE;
      case 1: return TQNT_MID;
      case 2: return TQNT_TAIL;
      case 3: return TQNT_CLOSE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<QuestionNodeType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      QuestionNodeType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<QuestionNodeType>() {
          public QuestionNodeType findValueByNumber(int number) {
            return QuestionNodeType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return po.EntityProto.getDescriptor().getEnumTypes().get(4);
  }

  private static final QuestionNodeType[] VALUES = values();

  public static QuestionNodeType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private QuestionNodeType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:po.QuestionNodeType)
}

