// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: entity.proto
// Protobuf Java Version: 4.33.2

package po;

/**
 * <pre>
 * 问题类型
 * </pre>
 *
 * Protobuf enum {@code po.QuestionType}
 */
@com.google.protobuf.Generated
public enum QuestionType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * 卫生环境
   * </pre>
   *
   * <code>TQT_WSHJ = 0;</code>
   */
  TQT_WSHJ(0),
  /**
   * <pre>
   * 邻里纠纷
   * </pre>
   *
   * <code>TQT_LLJF = 1;</code>
   */
  TQT_LLJF(1),
  /**
   * <pre>
   * 基础设施损坏
   * </pre>
   *
   * <code>TQT_JCSS = 2;</code>
   */
  TQT_JCSS(2),
  /**
   * <pre>
   * 干部作风
   * </pre>
   *
   * <code>TQT_GBZF = 3;</code>
   */
  TQT_GBZF(3),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "QuestionType");
  }
  /**
   * <pre>
   * 卫生环境
   * </pre>
   *
   * <code>TQT_WSHJ = 0;</code>
   */
  public static final int TQT_WSHJ_VALUE = 0;
  /**
   * <pre>
   * 邻里纠纷
   * </pre>
   *
   * <code>TQT_LLJF = 1;</code>
   */
  public static final int TQT_LLJF_VALUE = 1;
  /**
   * <pre>
   * 基础设施损坏
   * </pre>
   *
   * <code>TQT_JCSS = 2;</code>
   */
  public static final int TQT_JCSS_VALUE = 2;
  /**
   * <pre>
   * 干部作风
   * </pre>
   *
   * <code>TQT_GBZF = 3;</code>
   */
  public static final int TQT_GBZF_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static QuestionType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static QuestionType forNumber(int value) {
    switch (value) {
      case 0: return TQT_WSHJ;
      case 1: return TQT_LLJF;
      case 2: return TQT_JCSS;
      case 3: return TQT_GBZF;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<QuestionType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      QuestionType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<QuestionType>() {
          public QuestionType findValueByNumber(int number) {
            return QuestionType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return po.EntityProto.getDescriptor().getEnumTypes().get(5);
  }

  private static final QuestionType[] VALUES = values();

  public static QuestionType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private QuestionType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:po.QuestionType)
}

