// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: entity.proto
// Protobuf Java Version: 4.33.2

package po;

@com.google.protobuf.Generated
public interface QuestionHandlingInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:po.QuestionHandlingInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 自增唯一id
   * </pre>
   *
   * <code>optional int32 handlingId = 1;</code>
   * @return Whether the handlingId field is set.
   */
  boolean hasHandlingId();
  /**
   * <pre>
   * 自增唯一id
   * </pre>
   *
   * <code>optional int32 handlingId = 1;</code>
   * @return The handlingId.
   */
  int getHandlingId();

  /**
   * <pre>
   * 事务Id
   * </pre>
   *
   * <code>optional int32 questId = 2;</code>
   * @return Whether the questId field is set.
   */
  boolean hasQuestId();
  /**
   * <pre>
   * 事务Id
   * </pre>
   *
   * <code>optional int32 questId = 2;</code>
   * @return The questId.
   */
  int getQuestId();

  /**
   * <pre>
   * 处理结果
   * </pre>
   *
   * <code>optional .po.QuestionHandlingType handlingType = 3;</code>
   * @return Whether the handlingType field is set.
   */
  boolean hasHandlingType();
  /**
   * <pre>
   * 处理结果
   * </pre>
   *
   * <code>optional .po.QuestionHandlingType handlingType = 3;</code>
   * @return The enum numeric value on the wire for handlingType.
   */
  int getHandlingTypeValue();
  /**
   * <pre>
   * 处理结果
   * </pre>
   *
   * <code>optional .po.QuestionHandlingType handlingType = 3;</code>
   * @return The handlingType.
   */
  po.QuestionHandlingType getHandlingType();

  /**
   * <pre>
   * 处理人
   * </pre>
   *
   * <code>optional int32 handlingUserTel = 4;</code>
   * @return Whether the handlingUserTel field is set.
   */
  boolean hasHandlingUserTel();
  /**
   * <pre>
   * 处理人
   * </pre>
   *
   * <code>optional int32 handlingUserTel = 4;</code>
   * @return The handlingUserTel.
   */
  int getHandlingUserTel();

  /**
   * <pre>
   * 处理凭证
   * </pre>
   *
   * <code>repeated bytes handlingCtx = 5;</code>
   * @return A list containing the handlingCtx.
   */
  java.util.List<com.google.protobuf.ByteString> getHandlingCtxList();
  /**
   * <pre>
   * 处理凭证
   * </pre>
   *
   * <code>repeated bytes handlingCtx = 5;</code>
   * @return The count of handlingCtx.
   */
  int getHandlingCtxCount();
  /**
   * <pre>
   * 处理凭证
   * </pre>
   *
   * <code>repeated bytes handlingCtx = 5;</code>
   * @param index The index of the element to return.
   * @return The handlingCtx at the given index.
   */
  com.google.protobuf.ByteString getHandlingCtx(int index);

  /**
   * <pre>
   * 处理时间 MS
   * </pre>
   *
   * <code>optional int64 handlingTime = 6;</code>
   * @return Whether the handlingTime field is set.
   */
  boolean hasHandlingTime();
  /**
   * <pre>
   * 处理时间 MS
   * </pre>
   *
   * <code>optional int64 handlingTime = 6;</code>
   * @return The handlingTime.
   */
  long getHandlingTime();
}
