// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protocol.proto
// Protobuf Java Version: 4.33.2

package po;

@com.google.protobuf.Generated
public interface RequestTestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:po.RequestTest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string hello = 1;</code>
   * @return Whether the hello field is set.
   */
  boolean hasHello();
  /**
   * <code>optional string hello = 1;</code>
   * @return The hello.
   */
  java.lang.String getHello();
  /**
   * <code>optional string hello = 1;</code>
   * @return The bytes for hello.
   */
  com.google.protobuf.ByteString
      getHelloBytes();
}
