// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protocol.proto
// Protobuf Java Version: 4.33.2

package po;

/**
 * <pre>
 * 返回编码
 * </pre>
 *
 * Protobuf enum {@code po.RespCode}
 */
@com.google.protobuf.Generated
public enum RespCode
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * 成功
   * </pre>
   *
   * <code>TRC_OK = 0;</code>
   */
  TRC_OK(0),
  /**
   * <pre>
   * 错误
   * </pre>
   *
   * <code>TRC_ERR = 1;</code>
   */
  TRC_ERR(1),
  /**
   * <pre>
   * TOKEN不存在
   * </pre>
   *
   * <code>TRC_TOKEN_NOT_EXIST = 2;</code>
   */
  TRC_TOKEN_NOT_EXIST(2),
  /**
   * <pre>
   * TOKEN失效
   * </pre>
   *
   * <code>TRC_TOKEN_INVALID = 3;</code>
   */
  TRC_TOKEN_INVALID(3),
  /**
   * <pre>
   * 解析协议失败
   * </pre>
   *
   * <code>TRC_PARSE_PROTOCOL_ERR = 4;</code>
   */
  TRC_PARSE_PROTOCOL_ERR(4),
  /**
   * <pre>
   * 请求体为空
   * </pre>
   *
   * <code>TRC_REQUEST_BODY_NULL = 5;</code>
   */
  TRC_REQUEST_BODY_NULL(5),
  /**
   * <pre>
   * 用户不存在
   * </pre>
   *
   * <code>TRC_USER_NOT_EXIST = 6;</code>
   */
  TRC_USER_NOT_EXIST(6),
  /**
   * <pre>
   * 密码错误
   * </pre>
   *
   * <code>TRC_PASSWORD_ERR = 7;</code>
   */
  TRC_PASSWORD_ERR(7),
  /**
   * <pre>
   * 数据没找到
   * </pre>
   *
   * <code>TRC_DB_DATA_NOT_FOUND = 8;</code>
   */
  TRC_DB_DATA_NOT_FOUND(8),
  /**
   * <pre>
   * 数据操作异常
   * </pre>
   *
   * <code>TRC_DB_ERROR = 9;</code>
   */
  TRC_DB_ERROR(9),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "RespCode");
  }
  /**
   * <pre>
   * 成功
   * </pre>
   *
   * <code>TRC_OK = 0;</code>
   */
  public static final int TRC_OK_VALUE = 0;
  /**
   * <pre>
   * 错误
   * </pre>
   *
   * <code>TRC_ERR = 1;</code>
   */
  public static final int TRC_ERR_VALUE = 1;
  /**
   * <pre>
   * TOKEN不存在
   * </pre>
   *
   * <code>TRC_TOKEN_NOT_EXIST = 2;</code>
   */
  public static final int TRC_TOKEN_NOT_EXIST_VALUE = 2;
  /**
   * <pre>
   * TOKEN失效
   * </pre>
   *
   * <code>TRC_TOKEN_INVALID = 3;</code>
   */
  public static final int TRC_TOKEN_INVALID_VALUE = 3;
  /**
   * <pre>
   * 解析协议失败
   * </pre>
   *
   * <code>TRC_PARSE_PROTOCOL_ERR = 4;</code>
   */
  public static final int TRC_PARSE_PROTOCOL_ERR_VALUE = 4;
  /**
   * <pre>
   * 请求体为空
   * </pre>
   *
   * <code>TRC_REQUEST_BODY_NULL = 5;</code>
   */
  public static final int TRC_REQUEST_BODY_NULL_VALUE = 5;
  /**
   * <pre>
   * 用户不存在
   * </pre>
   *
   * <code>TRC_USER_NOT_EXIST = 6;</code>
   */
  public static final int TRC_USER_NOT_EXIST_VALUE = 6;
  /**
   * <pre>
   * 密码错误
   * </pre>
   *
   * <code>TRC_PASSWORD_ERR = 7;</code>
   */
  public static final int TRC_PASSWORD_ERR_VALUE = 7;
  /**
   * <pre>
   * 数据没找到
   * </pre>
   *
   * <code>TRC_DB_DATA_NOT_FOUND = 8;</code>
   */
  public static final int TRC_DB_DATA_NOT_FOUND_VALUE = 8;
  /**
   * <pre>
   * 数据操作异常
   * </pre>
   *
   * <code>TRC_DB_ERROR = 9;</code>
   */
  public static final int TRC_DB_ERROR_VALUE = 9;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static RespCode valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static RespCode forNumber(int value) {
    switch (value) {
      case 0: return TRC_OK;
      case 1: return TRC_ERR;
      case 2: return TRC_TOKEN_NOT_EXIST;
      case 3: return TRC_TOKEN_INVALID;
      case 4: return TRC_PARSE_PROTOCOL_ERR;
      case 5: return TRC_REQUEST_BODY_NULL;
      case 6: return TRC_USER_NOT_EXIST;
      case 7: return TRC_PASSWORD_ERR;
      case 8: return TRC_DB_DATA_NOT_FOUND;
      case 9: return TRC_DB_ERROR;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<RespCode>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      RespCode> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<RespCode>() {
          public RespCode findValueByNumber(int number) {
            return RespCode.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return po.ProtocolProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final RespCode[] VALUES = values();

  public static RespCode valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private RespCode(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:po.RespCode)
}

