// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protocol.proto
// Protobuf Java Version: 4.33.2

package po;

/**
 * <pre>
 * 返回编码
 * </pre>
 *
 * Protobuf enum {@code po.RespCode}
 */
@com.google.protobuf.Generated
public enum RespCode
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * 成功
   * </pre>
   *
   * <code>TRC_OK = 0;</code>
   */
  TRC_OK(0),
  /**
   * <pre>
   * 错误
   * </pre>
   *
   * <code>TRC_ERR = 1;</code>
   */
  TRC_ERR(1),
  /**
   * <pre>
   * TOKEN不存在
   * </pre>
   *
   * <code>TRC_TOKEN_NOT_EXIST = 2;</code>
   */
  TRC_TOKEN_NOT_EXIST(2),
  /**
   * <pre>
   * TOKEN失效
   * </pre>
   *
   * <code>TRC_TOKEN_INVALID = 3;</code>
   */
  TRC_TOKEN_INVALID(3),
  /**
   * <pre>
   * 解析协议失败
   * </pre>
   *
   * <code>TRC_PARSE_PROTOCOL_ERR = 4;</code>
   */
  TRC_PARSE_PROTOCOL_ERR(4),
  /**
   * <pre>
   * 请求体为空
   * </pre>
   *
   * <code>TRC_REQUEST_BODY_NULL = 5;</code>
   */
  TRC_REQUEST_BODY_NULL(5),
  /**
   * <pre>
   * 参数为空
   * </pre>
   *
   * <code>TRC_PARAM_NULL = 6;</code>
   */
  TRC_PARAM_NULL(6),
  /**
   * <pre>
   * 更新服务未启动
   * </pre>
   *
   * <code>TRC_UPDATE_SERVICE_NOT_FOUND = 7;</code>
   */
  TRC_UPDATE_SERVICE_NOT_FOUND(7),
  /**
   * <pre>
   * 服务未启动
   * </pre>
   *
   * <code>TRC_SERVICE_UNAVAILABLE = 8;</code>
   */
  TRC_SERVICE_UNAVAILABLE(8),
  /**
   * <pre>
   * 数据没找到
   * </pre>
   *
   * <code>TRC_DB_DATA_NOT_FOUND = 100;</code>
   */
  TRC_DB_DATA_NOT_FOUND(100),
  /**
   * <pre>
   * 数据操作异常
   * </pre>
   *
   * <code>TRC_DB_ERROR = 101;</code>
   */
  TRC_DB_ERROR(101),
  /**
   * <pre>
   * 操作Redis异常
   * </pre>
   *
   * <code>TRC_REDIS_ERROR = 102;</code>
   */
  TRC_REDIS_ERROR(102),
  /**
   * <pre>
   * 用户不存在
   * </pre>
   *
   * <code>TRC_USER_NOT_EXIST = 201;</code>
   */
  TRC_USER_NOT_EXIST(201),
  /**
   * <pre>
   * 用户已存在
   * </pre>
   *
   * <code>TRC_USER_EXIST = 202;</code>
   */
  TRC_USER_EXIST(202),
  /**
   * <pre>
   * 密码错误
   * </pre>
   *
   * <code>TRC_PASSWORD_ERR = 203;</code>
   */
  TRC_PASSWORD_ERR(203),
  /**
   * <pre>
   * 用户权限不足
   * </pre>
   *
   * <code>TRC_USER_POWER_NOT_ENOUGH = 204;</code>
   */
  TRC_USER_POWER_NOT_ENOUGH(204),
  /**
   * <pre>
   * 用户被冻结
   * </pre>
   *
   * <code>TRC_USER_IS_BAN = 205;</code>
   */
  TRC_USER_IS_BAN(205),
  /**
   * <pre>
   * 公告不存在
   * </pre>
   *
   * <code>TRC_NOTICE_NOT_EXIST = 301;</code>
   */
  TRC_NOTICE_NOT_EXIST(301),
  /**
   * <pre>
   * 此公告无需确认
   * </pre>
   *
   * <code>TRC_NOTICE_CAN_NOT_ACCEPT = 302;</code>
   */
  TRC_NOTICE_CAN_NOT_ACCEPT(302),
  /**
   * <pre>
   * 此公告已取人
   * </pre>
   *
   * <code>TRC_NOTICE_IS_ACCEPT = 303;</code>
   */
  TRC_NOTICE_IS_ACCEPT(303),
  /**
   * <pre>
   * 问题不存在
   * </pre>
   *
   * <code>TRC_QUESTION_NOT_EXIST = 401;</code>
   */
  TRC_QUESTION_NOT_EXIST(401),
  /**
   * <pre>
   * 问题已经在处理了
   * </pre>
   *
   * <code>TRC_QUESTION_IS_IN_OPT = 402;</code>
   */
  TRC_QUESTION_IS_IN_OPT(402),
  /**
   * <pre>
   * 问题无修改
   * </pre>
   *
   * <code>TRC_QUESTION_NOT_UPDATE = 403;</code>
   */
  TRC_QUESTION_NOT_UPDATE(403),
  /**
   * <pre>
   * 学习信息不存在
   * </pre>
   *
   * <code>TRC_STUDY_NOT_EXIST = 501;</code>
   */
  TRC_STUDY_NOT_EXIST(501),
  /**
   * <pre>
   * 学习信息已关注
   * </pre>
   *
   * <code>TRC_STUDY_IS_STAR = 502;</code>
   */
  TRC_STUDY_IS_STAR(502),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "RespCode");
  }
  /**
   * <pre>
   * 成功
   * </pre>
   *
   * <code>TRC_OK = 0;</code>
   */
  public static final int TRC_OK_VALUE = 0;
  /**
   * <pre>
   * 错误
   * </pre>
   *
   * <code>TRC_ERR = 1;</code>
   */
  public static final int TRC_ERR_VALUE = 1;
  /**
   * <pre>
   * TOKEN不存在
   * </pre>
   *
   * <code>TRC_TOKEN_NOT_EXIST = 2;</code>
   */
  public static final int TRC_TOKEN_NOT_EXIST_VALUE = 2;
  /**
   * <pre>
   * TOKEN失效
   * </pre>
   *
   * <code>TRC_TOKEN_INVALID = 3;</code>
   */
  public static final int TRC_TOKEN_INVALID_VALUE = 3;
  /**
   * <pre>
   * 解析协议失败
   * </pre>
   *
   * <code>TRC_PARSE_PROTOCOL_ERR = 4;</code>
   */
  public static final int TRC_PARSE_PROTOCOL_ERR_VALUE = 4;
  /**
   * <pre>
   * 请求体为空
   * </pre>
   *
   * <code>TRC_REQUEST_BODY_NULL = 5;</code>
   */
  public static final int TRC_REQUEST_BODY_NULL_VALUE = 5;
  /**
   * <pre>
   * 参数为空
   * </pre>
   *
   * <code>TRC_PARAM_NULL = 6;</code>
   */
  public static final int TRC_PARAM_NULL_VALUE = 6;
  /**
   * <pre>
   * 更新服务未启动
   * </pre>
   *
   * <code>TRC_UPDATE_SERVICE_NOT_FOUND = 7;</code>
   */
  public static final int TRC_UPDATE_SERVICE_NOT_FOUND_VALUE = 7;
  /**
   * <pre>
   * 服务未启动
   * </pre>
   *
   * <code>TRC_SERVICE_UNAVAILABLE = 8;</code>
   */
  public static final int TRC_SERVICE_UNAVAILABLE_VALUE = 8;
  /**
   * <pre>
   * 数据没找到
   * </pre>
   *
   * <code>TRC_DB_DATA_NOT_FOUND = 100;</code>
   */
  public static final int TRC_DB_DATA_NOT_FOUND_VALUE = 100;
  /**
   * <pre>
   * 数据操作异常
   * </pre>
   *
   * <code>TRC_DB_ERROR = 101;</code>
   */
  public static final int TRC_DB_ERROR_VALUE = 101;
  /**
   * <pre>
   * 操作Redis异常
   * </pre>
   *
   * <code>TRC_REDIS_ERROR = 102;</code>
   */
  public static final int TRC_REDIS_ERROR_VALUE = 102;
  /**
   * <pre>
   * 用户不存在
   * </pre>
   *
   * <code>TRC_USER_NOT_EXIST = 201;</code>
   */
  public static final int TRC_USER_NOT_EXIST_VALUE = 201;
  /**
   * <pre>
   * 用户已存在
   * </pre>
   *
   * <code>TRC_USER_EXIST = 202;</code>
   */
  public static final int TRC_USER_EXIST_VALUE = 202;
  /**
   * <pre>
   * 密码错误
   * </pre>
   *
   * <code>TRC_PASSWORD_ERR = 203;</code>
   */
  public static final int TRC_PASSWORD_ERR_VALUE = 203;
  /**
   * <pre>
   * 用户权限不足
   * </pre>
   *
   * <code>TRC_USER_POWER_NOT_ENOUGH = 204;</code>
   */
  public static final int TRC_USER_POWER_NOT_ENOUGH_VALUE = 204;
  /**
   * <pre>
   * 用户被冻结
   * </pre>
   *
   * <code>TRC_USER_IS_BAN = 205;</code>
   */
  public static final int TRC_USER_IS_BAN_VALUE = 205;
  /**
   * <pre>
   * 公告不存在
   * </pre>
   *
   * <code>TRC_NOTICE_NOT_EXIST = 301;</code>
   */
  public static final int TRC_NOTICE_NOT_EXIST_VALUE = 301;
  /**
   * <pre>
   * 此公告无需确认
   * </pre>
   *
   * <code>TRC_NOTICE_CAN_NOT_ACCEPT = 302;</code>
   */
  public static final int TRC_NOTICE_CAN_NOT_ACCEPT_VALUE = 302;
  /**
   * <pre>
   * 此公告已取人
   * </pre>
   *
   * <code>TRC_NOTICE_IS_ACCEPT = 303;</code>
   */
  public static final int TRC_NOTICE_IS_ACCEPT_VALUE = 303;
  /**
   * <pre>
   * 问题不存在
   * </pre>
   *
   * <code>TRC_QUESTION_NOT_EXIST = 401;</code>
   */
  public static final int TRC_QUESTION_NOT_EXIST_VALUE = 401;
  /**
   * <pre>
   * 问题已经在处理了
   * </pre>
   *
   * <code>TRC_QUESTION_IS_IN_OPT = 402;</code>
   */
  public static final int TRC_QUESTION_IS_IN_OPT_VALUE = 402;
  /**
   * <pre>
   * 问题无修改
   * </pre>
   *
   * <code>TRC_QUESTION_NOT_UPDATE = 403;</code>
   */
  public static final int TRC_QUESTION_NOT_UPDATE_VALUE = 403;
  /**
   * <pre>
   * 学习信息不存在
   * </pre>
   *
   * <code>TRC_STUDY_NOT_EXIST = 501;</code>
   */
  public static final int TRC_STUDY_NOT_EXIST_VALUE = 501;
  /**
   * <pre>
   * 学习信息已关注
   * </pre>
   *
   * <code>TRC_STUDY_IS_STAR = 502;</code>
   */
  public static final int TRC_STUDY_IS_STAR_VALUE = 502;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static RespCode valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static RespCode forNumber(int value) {
    switch (value) {
      case 0: return TRC_OK;
      case 1: return TRC_ERR;
      case 2: return TRC_TOKEN_NOT_EXIST;
      case 3: return TRC_TOKEN_INVALID;
      case 4: return TRC_PARSE_PROTOCOL_ERR;
      case 5: return TRC_REQUEST_BODY_NULL;
      case 6: return TRC_PARAM_NULL;
      case 7: return TRC_UPDATE_SERVICE_NOT_FOUND;
      case 8: return TRC_SERVICE_UNAVAILABLE;
      case 100: return TRC_DB_DATA_NOT_FOUND;
      case 101: return TRC_DB_ERROR;
      case 102: return TRC_REDIS_ERROR;
      case 201: return TRC_USER_NOT_EXIST;
      case 202: return TRC_USER_EXIST;
      case 203: return TRC_PASSWORD_ERR;
      case 204: return TRC_USER_POWER_NOT_ENOUGH;
      case 205: return TRC_USER_IS_BAN;
      case 301: return TRC_NOTICE_NOT_EXIST;
      case 302: return TRC_NOTICE_CAN_NOT_ACCEPT;
      case 303: return TRC_NOTICE_IS_ACCEPT;
      case 401: return TRC_QUESTION_NOT_EXIST;
      case 402: return TRC_QUESTION_IS_IN_OPT;
      case 403: return TRC_QUESTION_NOT_UPDATE;
      case 501: return TRC_STUDY_NOT_EXIST;
      case 502: return TRC_STUDY_IS_STAR;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<RespCode>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      RespCode> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<RespCode>() {
          public RespCode findValueByNumber(int number) {
            return RespCode.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return po.ProtocolProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final RespCode[] VALUES = values();

  public static RespCode valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private RespCode(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:po.RespCode)
}

