// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protocol.proto
// Protobuf Java Version: 4.33.2

package po;

@com.google.protobuf.Generated
public interface StarStudyReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:po.StarStudyReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * id
   * </pre>
   *
   * <code>optional int32 studyId = 1;</code>
   * @return Whether the studyId field is set.
   */
  boolean hasStudyId();
  /**
   * <pre>
   * id
   * </pre>
   *
   * <code>optional int32 studyId = 1;</code>
   * @return The studyId.
   */
  int getStudyId();
}
