// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: entity.proto
// Protobuf Java Version: 4.33.2

package po;

/**
 * <pre>
 * 学习模块
 * </pre>
 *
 * Protobuf type {@code po.StudyInfo}
 */
@com.google.protobuf.Generated
public final class StudyInfo extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:po.StudyInfo)
    StudyInfoOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "StudyInfo");
  }
  // Use StudyInfo.newBuilder() to construct.
  private StudyInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private StudyInfo() {
    studyType_ = 0;
    studyTitle_ = "";
    studyTip_ = "";
    studyContent_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return po.EntityProto.internal_static_po_StudyInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return po.EntityProto.internal_static_po_StudyInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            po.StudyInfo.class, po.StudyInfo.Builder.class);
  }

  private int bitField0_;
  public static final int STUDYID_FIELD_NUMBER = 1;
  private int studyId_ = 0;
  /**
   * <pre>
   * 自增唯一id
   * </pre>
   *
   * <code>optional int32 studyId = 1;</code>
   * @return Whether the studyId field is set.
   */
  @java.lang.Override
  public boolean hasStudyId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * 自增唯一id
   * </pre>
   *
   * <code>optional int32 studyId = 1;</code>
   * @return The studyId.
   */
  @java.lang.Override
  public int getStudyId() {
    return studyId_;
  }

  public static final int STUDYTYPE_FIELD_NUMBER = 2;
  private int studyType_ = 0;
  /**
   * <pre>
   * 学习内容类型
   * </pre>
   *
   * <code>optional .po.StudyType studyType = 2;</code>
   * @return Whether the studyType field is set.
   */
  @java.lang.Override public boolean hasStudyType() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * 学习内容类型
   * </pre>
   *
   * <code>optional .po.StudyType studyType = 2;</code>
   * @return The enum numeric value on the wire for studyType.
   */
  @java.lang.Override public int getStudyTypeValue() {
    return studyType_;
  }
  /**
   * <pre>
   * 学习内容类型
   * </pre>
   *
   * <code>optional .po.StudyType studyType = 2;</code>
   * @return The studyType.
   */
  @java.lang.Override public po.StudyType getStudyType() {
    po.StudyType result = po.StudyType.forNumber(studyType_);
    return result == null ? po.StudyType.UNRECOGNIZED : result;
  }

  public static final int STUDYCREATETIME_FIELD_NUMBER = 3;
  private long studyCreateTime_ = 0L;
  /**
   * <pre>
   * 学习内容创建时间
   * </pre>
   *
   * <code>optional int64 studyCreateTime = 3;</code>
   * @return Whether the studyCreateTime field is set.
   */
  @java.lang.Override
  public boolean hasStudyCreateTime() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * 学习内容创建时间
   * </pre>
   *
   * <code>optional int64 studyCreateTime = 3;</code>
   * @return The studyCreateTime.
   */
  @java.lang.Override
  public long getStudyCreateTime() {
    return studyCreateTime_;
  }

  public static final int STUDYTITLE_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object studyTitle_ = "";
  /**
   * <pre>
   * 学习标题
   * </pre>
   *
   * <code>optional string studyTitle = 4;</code>
   * @return Whether the studyTitle field is set.
   */
  @java.lang.Override
  public boolean hasStudyTitle() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <pre>
   * 学习标题
   * </pre>
   *
   * <code>optional string studyTitle = 4;</code>
   * @return The studyTitle.
   */
  @java.lang.Override
  public java.lang.String getStudyTitle() {
    java.lang.Object ref = studyTitle_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      studyTitle_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 学习标题
   * </pre>
   *
   * <code>optional string studyTitle = 4;</code>
   * @return The bytes for studyTitle.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStudyTitleBytes() {
    java.lang.Object ref = studyTitle_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      studyTitle_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STUDYTIP_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object studyTip_ = "";
  /**
   * <pre>
   * 学习内容简介
   * </pre>
   *
   * <code>optional string studyTip = 5;</code>
   * @return Whether the studyTip field is set.
   */
  @java.lang.Override
  public boolean hasStudyTip() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <pre>
   * 学习内容简介
   * </pre>
   *
   * <code>optional string studyTip = 5;</code>
   * @return The studyTip.
   */
  @java.lang.Override
  public java.lang.String getStudyTip() {
    java.lang.Object ref = studyTip_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      studyTip_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 学习内容简介
   * </pre>
   *
   * <code>optional string studyTip = 5;</code>
   * @return The bytes for studyTip.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStudyTipBytes() {
    java.lang.Object ref = studyTip_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      studyTip_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STUDYCONTENT_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object studyContent_ = "";
  /**
   * <pre>
   * 学习内容
   * </pre>
   *
   * <code>optional string studyContent = 6;</code>
   * @return Whether the studyContent field is set.
   */
  @java.lang.Override
  public boolean hasStudyContent() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <pre>
   * 学习内容
   * </pre>
   *
   * <code>optional string studyContent = 6;</code>
   * @return The studyContent.
   */
  @java.lang.Override
  public java.lang.String getStudyContent() {
    java.lang.Object ref = studyContent_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      studyContent_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 学习内容
   * </pre>
   *
   * <code>optional string studyContent = 6;</code>
   * @return The bytes for studyContent.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStudyContentBytes() {
    java.lang.Object ref = studyContent_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      studyContent_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISOPEN_FIELD_NUMBER = 7;
  private boolean isOpen_ = false;
  /**
   * <pre>
   * 是否公开
   * </pre>
   *
   * <code>optional bool isOpen = 7;</code>
   * @return Whether the isOpen field is set.
   */
  @java.lang.Override
  public boolean hasIsOpen() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <pre>
   * 是否公开
   * </pre>
   *
   * <code>optional bool isOpen = 7;</code>
   * @return The isOpen.
   */
  @java.lang.Override
  public boolean getIsOpen() {
    return isOpen_;
  }

  public static final int ISTOP_FIELD_NUMBER = 8;
  private boolean isTop_ = false;
  /**
   * <pre>
   * 是否首页展示
   * </pre>
   *
   * <code>optional bool isTop = 8;</code>
   * @return Whether the isTop field is set.
   */
  @java.lang.Override
  public boolean hasIsTop() {
    return ((bitField0_ & 0x00000080) != 0);
  }
  /**
   * <pre>
   * 是否首页展示
   * </pre>
   *
   * <code>optional bool isTop = 8;</code>
   * @return The isTop.
   */
  @java.lang.Override
  public boolean getIsTop() {
    return isTop_;
  }

  public static final int READCOUNT_FIELD_NUMBER = 9;
  private int readCount_ = 0;
  /**
   * <pre>
   * 阅读次数
   * </pre>
   *
   * <code>optional int32 readCount = 9;</code>
   * @return Whether the readCount field is set.
   */
  @java.lang.Override
  public boolean hasReadCount() {
    return ((bitField0_ & 0x00000100) != 0);
  }
  /**
   * <pre>
   * 阅读次数
   * </pre>
   *
   * <code>optional int32 readCount = 9;</code>
   * @return The readCount.
   */
  @java.lang.Override
  public int getReadCount() {
    return readCount_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt32(1, studyId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeEnum(2, studyType_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeInt64(3, studyCreateTime_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, studyTitle_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, studyTip_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, studyContent_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      output.writeBool(7, isOpen_);
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      output.writeBool(8, isTop_);
    }
    if (((bitField0_ & 0x00000100) != 0)) {
      output.writeInt32(9, readCount_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, studyId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, studyType_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, studyCreateTime_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, studyTitle_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, studyTip_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, studyContent_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, isOpen_);
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, isTop_);
    }
    if (((bitField0_ & 0x00000100) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, readCount_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof po.StudyInfo)) {
      return super.equals(obj);
    }
    po.StudyInfo other = (po.StudyInfo) obj;

    if (hasStudyId() != other.hasStudyId()) return false;
    if (hasStudyId()) {
      if (getStudyId()
          != other.getStudyId()) return false;
    }
    if (hasStudyType() != other.hasStudyType()) return false;
    if (hasStudyType()) {
      if (studyType_ != other.studyType_) return false;
    }
    if (hasStudyCreateTime() != other.hasStudyCreateTime()) return false;
    if (hasStudyCreateTime()) {
      if (getStudyCreateTime()
          != other.getStudyCreateTime()) return false;
    }
    if (hasStudyTitle() != other.hasStudyTitle()) return false;
    if (hasStudyTitle()) {
      if (!getStudyTitle()
          .equals(other.getStudyTitle())) return false;
    }
    if (hasStudyTip() != other.hasStudyTip()) return false;
    if (hasStudyTip()) {
      if (!getStudyTip()
          .equals(other.getStudyTip())) return false;
    }
    if (hasStudyContent() != other.hasStudyContent()) return false;
    if (hasStudyContent()) {
      if (!getStudyContent()
          .equals(other.getStudyContent())) return false;
    }
    if (hasIsOpen() != other.hasIsOpen()) return false;
    if (hasIsOpen()) {
      if (getIsOpen()
          != other.getIsOpen()) return false;
    }
    if (hasIsTop() != other.hasIsTop()) return false;
    if (hasIsTop()) {
      if (getIsTop()
          != other.getIsTop()) return false;
    }
    if (hasReadCount() != other.hasReadCount()) return false;
    if (hasReadCount()) {
      if (getReadCount()
          != other.getReadCount()) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasStudyId()) {
      hash = (37 * hash) + STUDYID_FIELD_NUMBER;
      hash = (53 * hash) + getStudyId();
    }
    if (hasStudyType()) {
      hash = (37 * hash) + STUDYTYPE_FIELD_NUMBER;
      hash = (53 * hash) + studyType_;
    }
    if (hasStudyCreateTime()) {
      hash = (37 * hash) + STUDYCREATETIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStudyCreateTime());
    }
    if (hasStudyTitle()) {
      hash = (37 * hash) + STUDYTITLE_FIELD_NUMBER;
      hash = (53 * hash) + getStudyTitle().hashCode();
    }
    if (hasStudyTip()) {
      hash = (37 * hash) + STUDYTIP_FIELD_NUMBER;
      hash = (53 * hash) + getStudyTip().hashCode();
    }
    if (hasStudyContent()) {
      hash = (37 * hash) + STUDYCONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getStudyContent().hashCode();
    }
    if (hasIsOpen()) {
      hash = (37 * hash) + ISOPEN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsOpen());
    }
    if (hasIsTop()) {
      hash = (37 * hash) + ISTOP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsTop());
    }
    if (hasReadCount()) {
      hash = (37 * hash) + READCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getReadCount();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static po.StudyInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static po.StudyInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static po.StudyInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static po.StudyInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static po.StudyInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static po.StudyInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static po.StudyInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static po.StudyInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static po.StudyInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static po.StudyInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static po.StudyInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static po.StudyInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(po.StudyInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 学习模块
   * </pre>
   *
   * Protobuf type {@code po.StudyInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:po.StudyInfo)
      po.StudyInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return po.EntityProto.internal_static_po_StudyInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return po.EntityProto.internal_static_po_StudyInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              po.StudyInfo.class, po.StudyInfo.Builder.class);
    }

    // Construct using po.StudyInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      studyId_ = 0;
      studyType_ = 0;
      studyCreateTime_ = 0L;
      studyTitle_ = "";
      studyTip_ = "";
      studyContent_ = "";
      isOpen_ = false;
      isTop_ = false;
      readCount_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return po.EntityProto.internal_static_po_StudyInfo_descriptor;
    }

    @java.lang.Override
    public po.StudyInfo getDefaultInstanceForType() {
      return po.StudyInfo.getDefaultInstance();
    }

    @java.lang.Override
    public po.StudyInfo build() {
      po.StudyInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public po.StudyInfo buildPartial() {
      po.StudyInfo result = new po.StudyInfo(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(po.StudyInfo result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.studyId_ = studyId_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.studyType_ = studyType_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.studyCreateTime_ = studyCreateTime_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.studyTitle_ = studyTitle_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.studyTip_ = studyTip_;
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.studyContent_ = studyContent_;
        to_bitField0_ |= 0x00000020;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.isOpen_ = isOpen_;
        to_bitField0_ |= 0x00000040;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.isTop_ = isTop_;
        to_bitField0_ |= 0x00000080;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.readCount_ = readCount_;
        to_bitField0_ |= 0x00000100;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof po.StudyInfo) {
        return mergeFrom((po.StudyInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(po.StudyInfo other) {
      if (other == po.StudyInfo.getDefaultInstance()) return this;
      if (other.hasStudyId()) {
        setStudyId(other.getStudyId());
      }
      if (other.hasStudyType()) {
        setStudyTypeValue(other.getStudyTypeValue());
      }
      if (other.hasStudyCreateTime()) {
        setStudyCreateTime(other.getStudyCreateTime());
      }
      if (other.hasStudyTitle()) {
        studyTitle_ = other.studyTitle_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.hasStudyTip()) {
        studyTip_ = other.studyTip_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.hasStudyContent()) {
        studyContent_ = other.studyContent_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (other.hasIsOpen()) {
        setIsOpen(other.getIsOpen());
      }
      if (other.hasIsTop()) {
        setIsTop(other.getIsTop());
      }
      if (other.hasReadCount()) {
        setReadCount(other.getReadCount());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              studyId_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              studyType_ = input.readEnum();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              studyCreateTime_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              studyTitle_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              studyTip_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              studyContent_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 56: {
              isOpen_ = input.readBool();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              isTop_ = input.readBool();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 72: {
              readCount_ = input.readInt32();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int studyId_ ;
    /**
     * <pre>
     * 自增唯一id
     * </pre>
     *
     * <code>optional int32 studyId = 1;</code>
     * @return Whether the studyId field is set.
     */
    @java.lang.Override
    public boolean hasStudyId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * 自增唯一id
     * </pre>
     *
     * <code>optional int32 studyId = 1;</code>
     * @return The studyId.
     */
    @java.lang.Override
    public int getStudyId() {
      return studyId_;
    }
    /**
     * <pre>
     * 自增唯一id
     * </pre>
     *
     * <code>optional int32 studyId = 1;</code>
     * @param value The studyId to set.
     * @return This builder for chaining.
     */
    public Builder setStudyId(int value) {

      studyId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 自增唯一id
     * </pre>
     *
     * <code>optional int32 studyId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStudyId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      studyId_ = 0;
      onChanged();
      return this;
    }

    private int studyType_ = 0;
    /**
     * <pre>
     * 学习内容类型
     * </pre>
     *
     * <code>optional .po.StudyType studyType = 2;</code>
     * @return Whether the studyType field is set.
     */
    @java.lang.Override public boolean hasStudyType() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * 学习内容类型
     * </pre>
     *
     * <code>optional .po.StudyType studyType = 2;</code>
     * @return The enum numeric value on the wire for studyType.
     */
    @java.lang.Override public int getStudyTypeValue() {
      return studyType_;
    }
    /**
     * <pre>
     * 学习内容类型
     * </pre>
     *
     * <code>optional .po.StudyType studyType = 2;</code>
     * @param value The enum numeric value on the wire for studyType to set.
     * @return This builder for chaining.
     */
    public Builder setStudyTypeValue(int value) {
      studyType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 学习内容类型
     * </pre>
     *
     * <code>optional .po.StudyType studyType = 2;</code>
     * @return The studyType.
     */
    @java.lang.Override
    public po.StudyType getStudyType() {
      po.StudyType result = po.StudyType.forNumber(studyType_);
      return result == null ? po.StudyType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 学习内容类型
     * </pre>
     *
     * <code>optional .po.StudyType studyType = 2;</code>
     * @param value The studyType to set.
     * @return This builder for chaining.
     */
    public Builder setStudyType(po.StudyType value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000002;
      studyType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 学习内容类型
     * </pre>
     *
     * <code>optional .po.StudyType studyType = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStudyType() {
      bitField0_ = (bitField0_ & ~0x00000002);
      studyType_ = 0;
      onChanged();
      return this;
    }

    private long studyCreateTime_ ;
    /**
     * <pre>
     * 学习内容创建时间
     * </pre>
     *
     * <code>optional int64 studyCreateTime = 3;</code>
     * @return Whether the studyCreateTime field is set.
     */
    @java.lang.Override
    public boolean hasStudyCreateTime() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * 学习内容创建时间
     * </pre>
     *
     * <code>optional int64 studyCreateTime = 3;</code>
     * @return The studyCreateTime.
     */
    @java.lang.Override
    public long getStudyCreateTime() {
      return studyCreateTime_;
    }
    /**
     * <pre>
     * 学习内容创建时间
     * </pre>
     *
     * <code>optional int64 studyCreateTime = 3;</code>
     * @param value The studyCreateTime to set.
     * @return This builder for chaining.
     */
    public Builder setStudyCreateTime(long value) {

      studyCreateTime_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 学习内容创建时间
     * </pre>
     *
     * <code>optional int64 studyCreateTime = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearStudyCreateTime() {
      bitField0_ = (bitField0_ & ~0x00000004);
      studyCreateTime_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object studyTitle_ = "";
    /**
     * <pre>
     * 学习标题
     * </pre>
     *
     * <code>optional string studyTitle = 4;</code>
     * @return Whether the studyTitle field is set.
     */
    public boolean hasStudyTitle() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * 学习标题
     * </pre>
     *
     * <code>optional string studyTitle = 4;</code>
     * @return The studyTitle.
     */
    public java.lang.String getStudyTitle() {
      java.lang.Object ref = studyTitle_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        studyTitle_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 学习标题
     * </pre>
     *
     * <code>optional string studyTitle = 4;</code>
     * @return The bytes for studyTitle.
     */
    public com.google.protobuf.ByteString
        getStudyTitleBytes() {
      java.lang.Object ref = studyTitle_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        studyTitle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 学习标题
     * </pre>
     *
     * <code>optional string studyTitle = 4;</code>
     * @param value The studyTitle to set.
     * @return This builder for chaining.
     */
    public Builder setStudyTitle(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      studyTitle_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 学习标题
     * </pre>
     *
     * <code>optional string studyTitle = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearStudyTitle() {
      studyTitle_ = getDefaultInstance().getStudyTitle();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 学习标题
     * </pre>
     *
     * <code>optional string studyTitle = 4;</code>
     * @param value The bytes for studyTitle to set.
     * @return This builder for chaining.
     */
    public Builder setStudyTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      studyTitle_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object studyTip_ = "";
    /**
     * <pre>
     * 学习内容简介
     * </pre>
     *
     * <code>optional string studyTip = 5;</code>
     * @return Whether the studyTip field is set.
     */
    public boolean hasStudyTip() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * 学习内容简介
     * </pre>
     *
     * <code>optional string studyTip = 5;</code>
     * @return The studyTip.
     */
    public java.lang.String getStudyTip() {
      java.lang.Object ref = studyTip_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        studyTip_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 学习内容简介
     * </pre>
     *
     * <code>optional string studyTip = 5;</code>
     * @return The bytes for studyTip.
     */
    public com.google.protobuf.ByteString
        getStudyTipBytes() {
      java.lang.Object ref = studyTip_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        studyTip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 学习内容简介
     * </pre>
     *
     * <code>optional string studyTip = 5;</code>
     * @param value The studyTip to set.
     * @return This builder for chaining.
     */
    public Builder setStudyTip(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      studyTip_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 学习内容简介
     * </pre>
     *
     * <code>optional string studyTip = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearStudyTip() {
      studyTip_ = getDefaultInstance().getStudyTip();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 学习内容简介
     * </pre>
     *
     * <code>optional string studyTip = 5;</code>
     * @param value The bytes for studyTip to set.
     * @return This builder for chaining.
     */
    public Builder setStudyTipBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      studyTip_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object studyContent_ = "";
    /**
     * <pre>
     * 学习内容
     * </pre>
     *
     * <code>optional string studyContent = 6;</code>
     * @return Whether the studyContent field is set.
     */
    public boolean hasStudyContent() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     * 学习内容
     * </pre>
     *
     * <code>optional string studyContent = 6;</code>
     * @return The studyContent.
     */
    public java.lang.String getStudyContent() {
      java.lang.Object ref = studyContent_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        studyContent_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 学习内容
     * </pre>
     *
     * <code>optional string studyContent = 6;</code>
     * @return The bytes for studyContent.
     */
    public com.google.protobuf.ByteString
        getStudyContentBytes() {
      java.lang.Object ref = studyContent_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        studyContent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 学习内容
     * </pre>
     *
     * <code>optional string studyContent = 6;</code>
     * @param value The studyContent to set.
     * @return This builder for chaining.
     */
    public Builder setStudyContent(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      studyContent_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 学习内容
     * </pre>
     *
     * <code>optional string studyContent = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearStudyContent() {
      studyContent_ = getDefaultInstance().getStudyContent();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 学习内容
     * </pre>
     *
     * <code>optional string studyContent = 6;</code>
     * @param value The bytes for studyContent to set.
     * @return This builder for chaining.
     */
    public Builder setStudyContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      studyContent_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private boolean isOpen_ ;
    /**
     * <pre>
     * 是否公开
     * </pre>
     *
     * <code>optional bool isOpen = 7;</code>
     * @return Whether the isOpen field is set.
     */
    @java.lang.Override
    public boolean hasIsOpen() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <pre>
     * 是否公开
     * </pre>
     *
     * <code>optional bool isOpen = 7;</code>
     * @return The isOpen.
     */
    @java.lang.Override
    public boolean getIsOpen() {
      return isOpen_;
    }
    /**
     * <pre>
     * 是否公开
     * </pre>
     *
     * <code>optional bool isOpen = 7;</code>
     * @param value The isOpen to set.
     * @return This builder for chaining.
     */
    public Builder setIsOpen(boolean value) {

      isOpen_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 是否公开
     * </pre>
     *
     * <code>optional bool isOpen = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsOpen() {
      bitField0_ = (bitField0_ & ~0x00000040);
      isOpen_ = false;
      onChanged();
      return this;
    }

    private boolean isTop_ ;
    /**
     * <pre>
     * 是否首页展示
     * </pre>
     *
     * <code>optional bool isTop = 8;</code>
     * @return Whether the isTop field is set.
     */
    @java.lang.Override
    public boolean hasIsTop() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <pre>
     * 是否首页展示
     * </pre>
     *
     * <code>optional bool isTop = 8;</code>
     * @return The isTop.
     */
    @java.lang.Override
    public boolean getIsTop() {
      return isTop_;
    }
    /**
     * <pre>
     * 是否首页展示
     * </pre>
     *
     * <code>optional bool isTop = 8;</code>
     * @param value The isTop to set.
     * @return This builder for chaining.
     */
    public Builder setIsTop(boolean value) {

      isTop_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 是否首页展示
     * </pre>
     *
     * <code>optional bool isTop = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsTop() {
      bitField0_ = (bitField0_ & ~0x00000080);
      isTop_ = false;
      onChanged();
      return this;
    }

    private int readCount_ ;
    /**
     * <pre>
     * 阅读次数
     * </pre>
     *
     * <code>optional int32 readCount = 9;</code>
     * @return Whether the readCount field is set.
     */
    @java.lang.Override
    public boolean hasReadCount() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <pre>
     * 阅读次数
     * </pre>
     *
     * <code>optional int32 readCount = 9;</code>
     * @return The readCount.
     */
    @java.lang.Override
    public int getReadCount() {
      return readCount_;
    }
    /**
     * <pre>
     * 阅读次数
     * </pre>
     *
     * <code>optional int32 readCount = 9;</code>
     * @param value The readCount to set.
     * @return This builder for chaining.
     */
    public Builder setReadCount(int value) {

      readCount_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 阅读次数
     * </pre>
     *
     * <code>optional int32 readCount = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearReadCount() {
      bitField0_ = (bitField0_ & ~0x00000100);
      readCount_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:po.StudyInfo)
  }

  // @@protoc_insertion_point(class_scope:po.StudyInfo)
  private static final po.StudyInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new po.StudyInfo();
  }

  public static po.StudyInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StudyInfo>
      PARSER = new com.google.protobuf.AbstractParser<StudyInfo>() {
    @java.lang.Override
    public StudyInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<StudyInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StudyInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public po.StudyInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

