// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: entity.proto
// Protobuf Java Version: 4.33.2

package po;

/**
 * <pre>
 * 公告类型
 * </pre>
 *
 * Protobuf enum {@code po.TNoticeType}
 */
@com.google.protobuf.Generated
public enum TNoticeType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * 通知
   * </pre>
   *
   * <code>TNT_TZ = 0;</code>
   */
  TNT_TZ(0),
  /**
   * <pre>
   * 招聘
   * </pre>
   *
   * <code>TNT_ZP = 1;</code>
   */
  TNT_ZP(1),
  /**
   * <pre>
   * 活动
   * </pre>
   *
   * <code>TNT_HD = 2;</code>
   */
  TNT_HD(2),
  /**
   * <pre>
   * 政府宣传
   * </pre>
   *
   * <code>TNT_ZFXC = 3;</code>
   */
  TNT_ZFXC(3),
  /**
   * <pre>
   * 公开政务
   * </pre>
   *
   * <code>TNT_GKZW = 4;</code>
   */
  TNT_GKZW(4),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "TNoticeType");
  }
  /**
   * <pre>
   * 通知
   * </pre>
   *
   * <code>TNT_TZ = 0;</code>
   */
  public static final int TNT_TZ_VALUE = 0;
  /**
   * <pre>
   * 招聘
   * </pre>
   *
   * <code>TNT_ZP = 1;</code>
   */
  public static final int TNT_ZP_VALUE = 1;
  /**
   * <pre>
   * 活动
   * </pre>
   *
   * <code>TNT_HD = 2;</code>
   */
  public static final int TNT_HD_VALUE = 2;
  /**
   * <pre>
   * 政府宣传
   * </pre>
   *
   * <code>TNT_ZFXC = 3;</code>
   */
  public static final int TNT_ZFXC_VALUE = 3;
  /**
   * <pre>
   * 公开政务
   * </pre>
   *
   * <code>TNT_GKZW = 4;</code>
   */
  public static final int TNT_GKZW_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static TNoticeType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static TNoticeType forNumber(int value) {
    switch (value) {
      case 0: return TNT_TZ;
      case 1: return TNT_ZP;
      case 2: return TNT_HD;
      case 3: return TNT_ZFXC;
      case 4: return TNT_GKZW;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<TNoticeType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      TNoticeType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<TNoticeType>() {
          public TNoticeType findValueByNumber(int number) {
            return TNoticeType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return po.EntityProto.getDescriptor().getEnumTypes().get(2);
  }

  private static final TNoticeType[] VALUES = values();

  public static TNoticeType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private TNoticeType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:po.TNoticeType)
}

