// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: entity.proto
// Protobuf Java Version: 4.33.2

package po;

/**
 * <pre>
 * 修改记录内容
 * </pre>
 *
 * Protobuf enum {@code po.TUpdateInfoType}
 */
@com.google.protobuf.Generated
public enum TUpdateInfoType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * 公告
   * </pre>
   *
   * <code>TUIT_NOTICE = 0;</code>
   */
  TUIT_NOTICE(0),
  /**
   * <pre>
   * 用户信息
   * </pre>
   *
   * <code>TUIT_USER = 1;</code>
   */
  TUIT_USER(1),
  /**
   * <pre>
   * 人员信息
   * </pre>
   *
   * <code>TUIT_PEOPLE = 2;</code>
   */
  TUIT_PEOPLE(2),
  /**
   * <pre>
   * 问题信息
   * </pre>
   *
   * <code>TUIT_QUESTION = 3;</code>
   */
  TUIT_QUESTION(3),
  /**
   * <pre>
   * 学习信息
   * </pre>
   *
   * <code>TUIT_STUDY = 4;</code>
   */
  TUIT_STUDY(4),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "TUpdateInfoType");
  }
  /**
   * <pre>
   * 公告
   * </pre>
   *
   * <code>TUIT_NOTICE = 0;</code>
   */
  public static final int TUIT_NOTICE_VALUE = 0;
  /**
   * <pre>
   * 用户信息
   * </pre>
   *
   * <code>TUIT_USER = 1;</code>
   */
  public static final int TUIT_USER_VALUE = 1;
  /**
   * <pre>
   * 人员信息
   * </pre>
   *
   * <code>TUIT_PEOPLE = 2;</code>
   */
  public static final int TUIT_PEOPLE_VALUE = 2;
  /**
   * <pre>
   * 问题信息
   * </pre>
   *
   * <code>TUIT_QUESTION = 3;</code>
   */
  public static final int TUIT_QUESTION_VALUE = 3;
  /**
   * <pre>
   * 学习信息
   * </pre>
   *
   * <code>TUIT_STUDY = 4;</code>
   */
  public static final int TUIT_STUDY_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static TUpdateInfoType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static TUpdateInfoType forNumber(int value) {
    switch (value) {
      case 0: return TUIT_NOTICE;
      case 1: return TUIT_USER;
      case 2: return TUIT_PEOPLE;
      case 3: return TUIT_QUESTION;
      case 4: return TUIT_STUDY;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<TUpdateInfoType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      TUpdateInfoType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<TUpdateInfoType>() {
          public TUpdateInfoType findValueByNumber(int number) {
            return TUpdateInfoType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return po.EntityProto.getDescriptor().getEnumTypes().get(3);
  }

  private static final TUpdateInfoType[] VALUES = values();

  public static TUpdateInfoType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private TUpdateInfoType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:po.TUpdateInfoType)
}

