// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: entity.proto
// Protobuf Java Version: 4.33.2

package po;

/**
 * <pre>
 * 用户权限类型
 * </pre>
 *
 * Protobuf enum {@code po.TUserPower}
 */
@com.google.protobuf.Generated
public enum TUserPower
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * 村民
   * </pre>
   *
   * <code>TUP_CM = 0;</code>
   */
  TUP_CM(0),
  /**
   * <pre>
   * 村干部
   * </pre>
   *
   * <code>TUP_CGM = 1;</code>
   */
  TUP_CGM(1),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "TUserPower");
  }
  /**
   * <pre>
   * 村民
   * </pre>
   *
   * <code>TUP_CM = 0;</code>
   */
  public static final int TUP_CM_VALUE = 0;
  /**
   * <pre>
   * 村干部
   * </pre>
   *
   * <code>TUP_CGM = 1;</code>
   */
  public static final int TUP_CGM_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static TUserPower valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static TUserPower forNumber(int value) {
    switch (value) {
      case 0: return TUP_CM;
      case 1: return TUP_CGM;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<TUserPower>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      TUserPower> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<TUserPower>() {
          public TUserPower findValueByNumber(int number) {
            return TUserPower.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return po.EntityProto.getDescriptor().getEnumTypes().get(1);
  }

  private static final TUserPower[] VALUES = values();

  public static TUserPower valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private TUserPower(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:po.TUserPower)
}

