// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: entity.proto
// Protobuf Java Version: 4.33.2

package po;

/**
 * <pre>
 * 修改记录
 * </pre>
 *
 * Protobuf type {@code po.UpdateInfo}
 */
@com.google.protobuf.Generated
public final class UpdateInfo extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:po.UpdateInfo)
    UpdateInfoOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "UpdateInfo");
  }
  // Use UpdateInfo.newBuilder() to construct.
  private UpdateInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private UpdateInfo() {
    infoType_ = 0;
    beforeMsg_ = com.google.protobuf.ByteString.EMPTY;
    afterMsg_ = com.google.protobuf.ByteString.EMPTY;
    updateName_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return po.EntityProto.internal_static_po_UpdateInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return po.EntityProto.internal_static_po_UpdateInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            po.UpdateInfo.class, po.UpdateInfo.Builder.class);
  }

  private int bitField0_;
  public static final int UPDATEID_FIELD_NUMBER = 1;
  private int updateId_ = 0;
  /**
   * <pre>
   * 自增唯一id
   * </pre>
   *
   * <code>optional int32 updateId = 1;</code>
   * @return Whether the updateId field is set.
   */
  @java.lang.Override
  public boolean hasUpdateId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * 自增唯一id
   * </pre>
   *
   * <code>optional int32 updateId = 1;</code>
   * @return The updateId.
   */
  @java.lang.Override
  public int getUpdateId() {
    return updateId_;
  }

  public static final int INFOID_FIELD_NUMBER = 2;
  private long infoId_ = 0L;
  /**
   * <pre>
   * 修改内容唯一ID
   * </pre>
   *
   * <code>optional int64 infoId = 2;</code>
   * @return Whether the infoId field is set.
   */
  @java.lang.Override
  public boolean hasInfoId() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * 修改内容唯一ID
   * </pre>
   *
   * <code>optional int64 infoId = 2;</code>
   * @return The infoId.
   */
  @java.lang.Override
  public long getInfoId() {
    return infoId_;
  }

  public static final int INFOTYPE_FIELD_NUMBER = 3;
  private int infoType_ = 0;
  /**
   * <pre>
   * 修改内容类型
   * </pre>
   *
   * <code>optional .po.TUpdateInfoType infoType = 3;</code>
   * @return Whether the infoType field is set.
   */
  @java.lang.Override public boolean hasInfoType() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * 修改内容类型
   * </pre>
   *
   * <code>optional .po.TUpdateInfoType infoType = 3;</code>
   * @return The enum numeric value on the wire for infoType.
   */
  @java.lang.Override public int getInfoTypeValue() {
    return infoType_;
  }
  /**
   * <pre>
   * 修改内容类型
   * </pre>
   *
   * <code>optional .po.TUpdateInfoType infoType = 3;</code>
   * @return The infoType.
   */
  @java.lang.Override public po.TUpdateInfoType getInfoType() {
    po.TUpdateInfoType result = po.TUpdateInfoType.forNumber(infoType_);
    return result == null ? po.TUpdateInfoType.UNRECOGNIZED : result;
  }

  public static final int BEFOREMSG_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString beforeMsg_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * 修改前protobuf序列化信息
   * </pre>
   *
   * <code>optional bytes beforeMsg = 4;</code>
   * @return Whether the beforeMsg field is set.
   */
  @java.lang.Override
  public boolean hasBeforeMsg() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <pre>
   * 修改前protobuf序列化信息
   * </pre>
   *
   * <code>optional bytes beforeMsg = 4;</code>
   * @return The beforeMsg.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getBeforeMsg() {
    return beforeMsg_;
  }

  public static final int AFTERMSG_FIELD_NUMBER = 5;
  private com.google.protobuf.ByteString afterMsg_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * 修改后protobuf序列化信息
   * </pre>
   *
   * <code>optional bytes afterMsg = 5;</code>
   * @return Whether the afterMsg field is set.
   */
  @java.lang.Override
  public boolean hasAfterMsg() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <pre>
   * 修改后protobuf序列化信息
   * </pre>
   *
   * <code>optional bytes afterMsg = 5;</code>
   * @return The afterMsg.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getAfterMsg() {
    return afterMsg_;
  }

  public static final int UPDATETIME_FIELD_NUMBER = 6;
  private long updateTime_ = 0L;
  /**
   * <pre>
   * 修改时间
   * </pre>
   *
   * <code>optional int64 updateTime = 6;</code>
   * @return Whether the updateTime field is set.
   */
  @java.lang.Override
  public boolean hasUpdateTime() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <pre>
   * 修改时间
   * </pre>
   *
   * <code>optional int64 updateTime = 6;</code>
   * @return The updateTime.
   */
  @java.lang.Override
  public long getUpdateTime() {
    return updateTime_;
  }

  public static final int UPDATEUSERTEL_FIELD_NUMBER = 7;
  private int updateUserTel_ = 0;
  /**
   * <pre>
   * 修改人电话
   * </pre>
   *
   * <code>optional int32 updateUserTel = 7;</code>
   * @return Whether the updateUserTel field is set.
   */
  @java.lang.Override
  public boolean hasUpdateUserTel() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <pre>
   * 修改人电话
   * </pre>
   *
   * <code>optional int32 updateUserTel = 7;</code>
   * @return The updateUserTel.
   */
  @java.lang.Override
  public int getUpdateUserTel() {
    return updateUserTel_;
  }

  public static final int UPDATENAME_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object updateName_ = "";
  /**
   * <pre>
   * 修改人姓名
   * </pre>
   *
   * <code>optional string updateName = 8;</code>
   * @return Whether the updateName field is set.
   */
  @java.lang.Override
  public boolean hasUpdateName() {
    return ((bitField0_ & 0x00000080) != 0);
  }
  /**
   * <pre>
   * 修改人姓名
   * </pre>
   *
   * <code>optional string updateName = 8;</code>
   * @return The updateName.
   */
  @java.lang.Override
  public java.lang.String getUpdateName() {
    java.lang.Object ref = updateName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      updateName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 修改人姓名
   * </pre>
   *
   * <code>optional string updateName = 8;</code>
   * @return The bytes for updateName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUpdateNameBytes() {
    java.lang.Object ref = updateName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      updateName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt32(1, updateId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt64(2, infoId_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeEnum(3, infoType_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeBytes(4, beforeMsg_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeBytes(5, afterMsg_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeInt64(6, updateTime_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      output.writeInt32(7, updateUserTel_);
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 8, updateName_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, updateId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, infoId_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, infoType_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, beforeMsg_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(5, afterMsg_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, updateTime_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, updateUserTel_);
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(8, updateName_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof po.UpdateInfo)) {
      return super.equals(obj);
    }
    po.UpdateInfo other = (po.UpdateInfo) obj;

    if (hasUpdateId() != other.hasUpdateId()) return false;
    if (hasUpdateId()) {
      if (getUpdateId()
          != other.getUpdateId()) return false;
    }
    if (hasInfoId() != other.hasInfoId()) return false;
    if (hasInfoId()) {
      if (getInfoId()
          != other.getInfoId()) return false;
    }
    if (hasInfoType() != other.hasInfoType()) return false;
    if (hasInfoType()) {
      if (infoType_ != other.infoType_) return false;
    }
    if (hasBeforeMsg() != other.hasBeforeMsg()) return false;
    if (hasBeforeMsg()) {
      if (!getBeforeMsg()
          .equals(other.getBeforeMsg())) return false;
    }
    if (hasAfterMsg() != other.hasAfterMsg()) return false;
    if (hasAfterMsg()) {
      if (!getAfterMsg()
          .equals(other.getAfterMsg())) return false;
    }
    if (hasUpdateTime() != other.hasUpdateTime()) return false;
    if (hasUpdateTime()) {
      if (getUpdateTime()
          != other.getUpdateTime()) return false;
    }
    if (hasUpdateUserTel() != other.hasUpdateUserTel()) return false;
    if (hasUpdateUserTel()) {
      if (getUpdateUserTel()
          != other.getUpdateUserTel()) return false;
    }
    if (hasUpdateName() != other.hasUpdateName()) return false;
    if (hasUpdateName()) {
      if (!getUpdateName()
          .equals(other.getUpdateName())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasUpdateId()) {
      hash = (37 * hash) + UPDATEID_FIELD_NUMBER;
      hash = (53 * hash) + getUpdateId();
    }
    if (hasInfoId()) {
      hash = (37 * hash) + INFOID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getInfoId());
    }
    if (hasInfoType()) {
      hash = (37 * hash) + INFOTYPE_FIELD_NUMBER;
      hash = (53 * hash) + infoType_;
    }
    if (hasBeforeMsg()) {
      hash = (37 * hash) + BEFOREMSG_FIELD_NUMBER;
      hash = (53 * hash) + getBeforeMsg().hashCode();
    }
    if (hasAfterMsg()) {
      hash = (37 * hash) + AFTERMSG_FIELD_NUMBER;
      hash = (53 * hash) + getAfterMsg().hashCode();
    }
    if (hasUpdateTime()) {
      hash = (37 * hash) + UPDATETIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUpdateTime());
    }
    if (hasUpdateUserTel()) {
      hash = (37 * hash) + UPDATEUSERTEL_FIELD_NUMBER;
      hash = (53 * hash) + getUpdateUserTel();
    }
    if (hasUpdateName()) {
      hash = (37 * hash) + UPDATENAME_FIELD_NUMBER;
      hash = (53 * hash) + getUpdateName().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static po.UpdateInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static po.UpdateInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static po.UpdateInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static po.UpdateInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static po.UpdateInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static po.UpdateInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static po.UpdateInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static po.UpdateInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static po.UpdateInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static po.UpdateInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static po.UpdateInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static po.UpdateInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(po.UpdateInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 修改记录
   * </pre>
   *
   * Protobuf type {@code po.UpdateInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:po.UpdateInfo)
      po.UpdateInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return po.EntityProto.internal_static_po_UpdateInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return po.EntityProto.internal_static_po_UpdateInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              po.UpdateInfo.class, po.UpdateInfo.Builder.class);
    }

    // Construct using po.UpdateInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      updateId_ = 0;
      infoId_ = 0L;
      infoType_ = 0;
      beforeMsg_ = com.google.protobuf.ByteString.EMPTY;
      afterMsg_ = com.google.protobuf.ByteString.EMPTY;
      updateTime_ = 0L;
      updateUserTel_ = 0;
      updateName_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return po.EntityProto.internal_static_po_UpdateInfo_descriptor;
    }

    @java.lang.Override
    public po.UpdateInfo getDefaultInstanceForType() {
      return po.UpdateInfo.getDefaultInstance();
    }

    @java.lang.Override
    public po.UpdateInfo build() {
      po.UpdateInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public po.UpdateInfo buildPartial() {
      po.UpdateInfo result = new po.UpdateInfo(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(po.UpdateInfo result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.updateId_ = updateId_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.infoId_ = infoId_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.infoType_ = infoType_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.beforeMsg_ = beforeMsg_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.afterMsg_ = afterMsg_;
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.updateTime_ = updateTime_;
        to_bitField0_ |= 0x00000020;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.updateUserTel_ = updateUserTel_;
        to_bitField0_ |= 0x00000040;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.updateName_ = updateName_;
        to_bitField0_ |= 0x00000080;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof po.UpdateInfo) {
        return mergeFrom((po.UpdateInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(po.UpdateInfo other) {
      if (other == po.UpdateInfo.getDefaultInstance()) return this;
      if (other.hasUpdateId()) {
        setUpdateId(other.getUpdateId());
      }
      if (other.hasInfoId()) {
        setInfoId(other.getInfoId());
      }
      if (other.hasInfoType()) {
        setInfoTypeValue(other.getInfoTypeValue());
      }
      if (other.hasBeforeMsg()) {
        setBeforeMsg(other.getBeforeMsg());
      }
      if (other.hasAfterMsg()) {
        setAfterMsg(other.getAfterMsg());
      }
      if (other.hasUpdateTime()) {
        setUpdateTime(other.getUpdateTime());
      }
      if (other.hasUpdateUserTel()) {
        setUpdateUserTel(other.getUpdateUserTel());
      }
      if (other.hasUpdateName()) {
        updateName_ = other.updateName_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              updateId_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              infoId_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              infoType_ = input.readEnum();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              beforeMsg_ = input.readBytes();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              afterMsg_ = input.readBytes();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 48: {
              updateTime_ = input.readInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              updateUserTel_ = input.readInt32();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 66: {
              updateName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int updateId_ ;
    /**
     * <pre>
     * 自增唯一id
     * </pre>
     *
     * <code>optional int32 updateId = 1;</code>
     * @return Whether the updateId field is set.
     */
    @java.lang.Override
    public boolean hasUpdateId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * 自增唯一id
     * </pre>
     *
     * <code>optional int32 updateId = 1;</code>
     * @return The updateId.
     */
    @java.lang.Override
    public int getUpdateId() {
      return updateId_;
    }
    /**
     * <pre>
     * 自增唯一id
     * </pre>
     *
     * <code>optional int32 updateId = 1;</code>
     * @param value The updateId to set.
     * @return This builder for chaining.
     */
    public Builder setUpdateId(int value) {

      updateId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 自增唯一id
     * </pre>
     *
     * <code>optional int32 updateId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUpdateId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      updateId_ = 0;
      onChanged();
      return this;
    }

    private long infoId_ ;
    /**
     * <pre>
     * 修改内容唯一ID
     * </pre>
     *
     * <code>optional int64 infoId = 2;</code>
     * @return Whether the infoId field is set.
     */
    @java.lang.Override
    public boolean hasInfoId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * 修改内容唯一ID
     * </pre>
     *
     * <code>optional int64 infoId = 2;</code>
     * @return The infoId.
     */
    @java.lang.Override
    public long getInfoId() {
      return infoId_;
    }
    /**
     * <pre>
     * 修改内容唯一ID
     * </pre>
     *
     * <code>optional int64 infoId = 2;</code>
     * @param value The infoId to set.
     * @return This builder for chaining.
     */
    public Builder setInfoId(long value) {

      infoId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 修改内容唯一ID
     * </pre>
     *
     * <code>optional int64 infoId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearInfoId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      infoId_ = 0L;
      onChanged();
      return this;
    }

    private int infoType_ = 0;
    /**
     * <pre>
     * 修改内容类型
     * </pre>
     *
     * <code>optional .po.TUpdateInfoType infoType = 3;</code>
     * @return Whether the infoType field is set.
     */
    @java.lang.Override public boolean hasInfoType() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * 修改内容类型
     * </pre>
     *
     * <code>optional .po.TUpdateInfoType infoType = 3;</code>
     * @return The enum numeric value on the wire for infoType.
     */
    @java.lang.Override public int getInfoTypeValue() {
      return infoType_;
    }
    /**
     * <pre>
     * 修改内容类型
     * </pre>
     *
     * <code>optional .po.TUpdateInfoType infoType = 3;</code>
     * @param value The enum numeric value on the wire for infoType to set.
     * @return This builder for chaining.
     */
    public Builder setInfoTypeValue(int value) {
      infoType_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 修改内容类型
     * </pre>
     *
     * <code>optional .po.TUpdateInfoType infoType = 3;</code>
     * @return The infoType.
     */
    @java.lang.Override
    public po.TUpdateInfoType getInfoType() {
      po.TUpdateInfoType result = po.TUpdateInfoType.forNumber(infoType_);
      return result == null ? po.TUpdateInfoType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 修改内容类型
     * </pre>
     *
     * <code>optional .po.TUpdateInfoType infoType = 3;</code>
     * @param value The infoType to set.
     * @return This builder for chaining.
     */
    public Builder setInfoType(po.TUpdateInfoType value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000004;
      infoType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 修改内容类型
     * </pre>
     *
     * <code>optional .po.TUpdateInfoType infoType = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearInfoType() {
      bitField0_ = (bitField0_ & ~0x00000004);
      infoType_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString beforeMsg_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * 修改前protobuf序列化信息
     * </pre>
     *
     * <code>optional bytes beforeMsg = 4;</code>
     * @return Whether the beforeMsg field is set.
     */
    @java.lang.Override
    public boolean hasBeforeMsg() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * 修改前protobuf序列化信息
     * </pre>
     *
     * <code>optional bytes beforeMsg = 4;</code>
     * @return The beforeMsg.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getBeforeMsg() {
      return beforeMsg_;
    }
    /**
     * <pre>
     * 修改前protobuf序列化信息
     * </pre>
     *
     * <code>optional bytes beforeMsg = 4;</code>
     * @param value The beforeMsg to set.
     * @return This builder for chaining.
     */
    public Builder setBeforeMsg(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      beforeMsg_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 修改前protobuf序列化信息
     * </pre>
     *
     * <code>optional bytes beforeMsg = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearBeforeMsg() {
      bitField0_ = (bitField0_ & ~0x00000008);
      beforeMsg_ = getDefaultInstance().getBeforeMsg();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString afterMsg_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * 修改后protobuf序列化信息
     * </pre>
     *
     * <code>optional bytes afterMsg = 5;</code>
     * @return Whether the afterMsg field is set.
     */
    @java.lang.Override
    public boolean hasAfterMsg() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * 修改后protobuf序列化信息
     * </pre>
     *
     * <code>optional bytes afterMsg = 5;</code>
     * @return The afterMsg.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getAfterMsg() {
      return afterMsg_;
    }
    /**
     * <pre>
     * 修改后protobuf序列化信息
     * </pre>
     *
     * <code>optional bytes afterMsg = 5;</code>
     * @param value The afterMsg to set.
     * @return This builder for chaining.
     */
    public Builder setAfterMsg(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      afterMsg_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 修改后protobuf序列化信息
     * </pre>
     *
     * <code>optional bytes afterMsg = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearAfterMsg() {
      bitField0_ = (bitField0_ & ~0x00000010);
      afterMsg_ = getDefaultInstance().getAfterMsg();
      onChanged();
      return this;
    }

    private long updateTime_ ;
    /**
     * <pre>
     * 修改时间
     * </pre>
     *
     * <code>optional int64 updateTime = 6;</code>
     * @return Whether the updateTime field is set.
     */
    @java.lang.Override
    public boolean hasUpdateTime() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     * 修改时间
     * </pre>
     *
     * <code>optional int64 updateTime = 6;</code>
     * @return The updateTime.
     */
    @java.lang.Override
    public long getUpdateTime() {
      return updateTime_;
    }
    /**
     * <pre>
     * 修改时间
     * </pre>
     *
     * <code>optional int64 updateTime = 6;</code>
     * @param value The updateTime to set.
     * @return This builder for chaining.
     */
    public Builder setUpdateTime(long value) {

      updateTime_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 修改时间
     * </pre>
     *
     * <code>optional int64 updateTime = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearUpdateTime() {
      bitField0_ = (bitField0_ & ~0x00000020);
      updateTime_ = 0L;
      onChanged();
      return this;
    }

    private int updateUserTel_ ;
    /**
     * <pre>
     * 修改人电话
     * </pre>
     *
     * <code>optional int32 updateUserTel = 7;</code>
     * @return Whether the updateUserTel field is set.
     */
    @java.lang.Override
    public boolean hasUpdateUserTel() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <pre>
     * 修改人电话
     * </pre>
     *
     * <code>optional int32 updateUserTel = 7;</code>
     * @return The updateUserTel.
     */
    @java.lang.Override
    public int getUpdateUserTel() {
      return updateUserTel_;
    }
    /**
     * <pre>
     * 修改人电话
     * </pre>
     *
     * <code>optional int32 updateUserTel = 7;</code>
     * @param value The updateUserTel to set.
     * @return This builder for chaining.
     */
    public Builder setUpdateUserTel(int value) {

      updateUserTel_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 修改人电话
     * </pre>
     *
     * <code>optional int32 updateUserTel = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearUpdateUserTel() {
      bitField0_ = (bitField0_ & ~0x00000040);
      updateUserTel_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object updateName_ = "";
    /**
     * <pre>
     * 修改人姓名
     * </pre>
     *
     * <code>optional string updateName = 8;</code>
     * @return Whether the updateName field is set.
     */
    public boolean hasUpdateName() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <pre>
     * 修改人姓名
     * </pre>
     *
     * <code>optional string updateName = 8;</code>
     * @return The updateName.
     */
    public java.lang.String getUpdateName() {
      java.lang.Object ref = updateName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        updateName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 修改人姓名
     * </pre>
     *
     * <code>optional string updateName = 8;</code>
     * @return The bytes for updateName.
     */
    public com.google.protobuf.ByteString
        getUpdateNameBytes() {
      java.lang.Object ref = updateName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        updateName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 修改人姓名
     * </pre>
     *
     * <code>optional string updateName = 8;</code>
     * @param value The updateName to set.
     * @return This builder for chaining.
     */
    public Builder setUpdateName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      updateName_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 修改人姓名
     * </pre>
     *
     * <code>optional string updateName = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearUpdateName() {
      updateName_ = getDefaultInstance().getUpdateName();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 修改人姓名
     * </pre>
     *
     * <code>optional string updateName = 8;</code>
     * @param value The bytes for updateName to set.
     * @return This builder for chaining.
     */
    public Builder setUpdateNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      updateName_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:po.UpdateInfo)
  }

  // @@protoc_insertion_point(class_scope:po.UpdateInfo)
  private static final po.UpdateInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new po.UpdateInfo();
  }

  public static po.UpdateInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdateInfo>
      PARSER = new com.google.protobuf.AbstractParser<UpdateInfo>() {
    @java.lang.Override
    public UpdateInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UpdateInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UpdateInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public po.UpdateInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

