// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protocol.proto
// Protobuf Java Version: 4.33.2

package po;

/**
 * <pre>
 * 修改学习资料（管理员）
 * </pre>
 *
 * Protobuf type {@code po.UpdateStudyReq}
 */
@com.google.protobuf.Generated
public final class UpdateStudyReq extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:po.UpdateStudyReq)
    UpdateStudyReqOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "UpdateStudyReq");
  }
  // Use UpdateStudyReq.newBuilder() to construct.
  private UpdateStudyReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private UpdateStudyReq() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return po.ProtocolProto.internal_static_po_UpdateStudyReq_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return po.ProtocolProto.internal_static_po_UpdateStudyReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            po.UpdateStudyReq.class, po.UpdateStudyReq.Builder.class);
  }

  private int bitField0_;
  public static final int ISDEL_FIELD_NUMBER = 1;
  private boolean isDel_ = false;
  /**
   * <pre>
   * 是否删除
   * </pre>
   *
   * <code>optional bool isDel = 1;</code>
   * @return Whether the isDel field is set.
   */
  @java.lang.Override
  public boolean hasIsDel() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * 是否删除
   * </pre>
   *
   * <code>optional bool isDel = 1;</code>
   * @return The isDel.
   */
  @java.lang.Override
  public boolean getIsDel() {
    return isDel_;
  }

  public static final int STUDYINFO_FIELD_NUMBER = 2;
  private po.StudyInfo studyInfo_;
  /**
   * <pre>
   * 学习信息
   * </pre>
   *
   * <code>optional .po.StudyInfo studyInfo = 2;</code>
   * @return Whether the studyInfo field is set.
   */
  @java.lang.Override
  public boolean hasStudyInfo() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * 学习信息
   * </pre>
   *
   * <code>optional .po.StudyInfo studyInfo = 2;</code>
   * @return The studyInfo.
   */
  @java.lang.Override
  public po.StudyInfo getStudyInfo() {
    return studyInfo_ == null ? po.StudyInfo.getDefaultInstance() : studyInfo_;
  }
  /**
   * <pre>
   * 学习信息
   * </pre>
   *
   * <code>optional .po.StudyInfo studyInfo = 2;</code>
   */
  @java.lang.Override
  public po.StudyInfoOrBuilder getStudyInfoOrBuilder() {
    return studyInfo_ == null ? po.StudyInfo.getDefaultInstance() : studyInfo_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeBool(1, isDel_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getStudyInfo());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, isDel_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getStudyInfo());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof po.UpdateStudyReq)) {
      return super.equals(obj);
    }
    po.UpdateStudyReq other = (po.UpdateStudyReq) obj;

    if (hasIsDel() != other.hasIsDel()) return false;
    if (hasIsDel()) {
      if (getIsDel()
          != other.getIsDel()) return false;
    }
    if (hasStudyInfo() != other.hasStudyInfo()) return false;
    if (hasStudyInfo()) {
      if (!getStudyInfo()
          .equals(other.getStudyInfo())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasIsDel()) {
      hash = (37 * hash) + ISDEL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsDel());
    }
    if (hasStudyInfo()) {
      hash = (37 * hash) + STUDYINFO_FIELD_NUMBER;
      hash = (53 * hash) + getStudyInfo().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static po.UpdateStudyReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static po.UpdateStudyReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static po.UpdateStudyReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static po.UpdateStudyReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static po.UpdateStudyReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static po.UpdateStudyReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static po.UpdateStudyReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static po.UpdateStudyReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static po.UpdateStudyReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static po.UpdateStudyReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static po.UpdateStudyReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static po.UpdateStudyReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(po.UpdateStudyReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 修改学习资料（管理员）
   * </pre>
   *
   * Protobuf type {@code po.UpdateStudyReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:po.UpdateStudyReq)
      po.UpdateStudyReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return po.ProtocolProto.internal_static_po_UpdateStudyReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return po.ProtocolProto.internal_static_po_UpdateStudyReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              po.UpdateStudyReq.class, po.UpdateStudyReq.Builder.class);
    }

    // Construct using po.UpdateStudyReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetStudyInfoFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      isDel_ = false;
      studyInfo_ = null;
      if (studyInfoBuilder_ != null) {
        studyInfoBuilder_.dispose();
        studyInfoBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return po.ProtocolProto.internal_static_po_UpdateStudyReq_descriptor;
    }

    @java.lang.Override
    public po.UpdateStudyReq getDefaultInstanceForType() {
      return po.UpdateStudyReq.getDefaultInstance();
    }

    @java.lang.Override
    public po.UpdateStudyReq build() {
      po.UpdateStudyReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public po.UpdateStudyReq buildPartial() {
      po.UpdateStudyReq result = new po.UpdateStudyReq(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(po.UpdateStudyReq result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.isDel_ = isDel_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.studyInfo_ = studyInfoBuilder_ == null
            ? studyInfo_
            : studyInfoBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof po.UpdateStudyReq) {
        return mergeFrom((po.UpdateStudyReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(po.UpdateStudyReq other) {
      if (other == po.UpdateStudyReq.getDefaultInstance()) return this;
      if (other.hasIsDel()) {
        setIsDel(other.getIsDel());
      }
      if (other.hasStudyInfo()) {
        mergeStudyInfo(other.getStudyInfo());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              isDel_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  internalGetStudyInfoFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean isDel_ ;
    /**
     * <pre>
     * 是否删除
     * </pre>
     *
     * <code>optional bool isDel = 1;</code>
     * @return Whether the isDel field is set.
     */
    @java.lang.Override
    public boolean hasIsDel() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * 是否删除
     * </pre>
     *
     * <code>optional bool isDel = 1;</code>
     * @return The isDel.
     */
    @java.lang.Override
    public boolean getIsDel() {
      return isDel_;
    }
    /**
     * <pre>
     * 是否删除
     * </pre>
     *
     * <code>optional bool isDel = 1;</code>
     * @param value The isDel to set.
     * @return This builder for chaining.
     */
    public Builder setIsDel(boolean value) {

      isDel_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 是否删除
     * </pre>
     *
     * <code>optional bool isDel = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsDel() {
      bitField0_ = (bitField0_ & ~0x00000001);
      isDel_ = false;
      onChanged();
      return this;
    }

    private po.StudyInfo studyInfo_;
    private com.google.protobuf.SingleFieldBuilder<
        po.StudyInfo, po.StudyInfo.Builder, po.StudyInfoOrBuilder> studyInfoBuilder_;
    /**
     * <pre>
     * 学习信息
     * </pre>
     *
     * <code>optional .po.StudyInfo studyInfo = 2;</code>
     * @return Whether the studyInfo field is set.
     */
    public boolean hasStudyInfo() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * 学习信息
     * </pre>
     *
     * <code>optional .po.StudyInfo studyInfo = 2;</code>
     * @return The studyInfo.
     */
    public po.StudyInfo getStudyInfo() {
      if (studyInfoBuilder_ == null) {
        return studyInfo_ == null ? po.StudyInfo.getDefaultInstance() : studyInfo_;
      } else {
        return studyInfoBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 学习信息
     * </pre>
     *
     * <code>optional .po.StudyInfo studyInfo = 2;</code>
     */
    public Builder setStudyInfo(po.StudyInfo value) {
      if (studyInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        studyInfo_ = value;
      } else {
        studyInfoBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 学习信息
     * </pre>
     *
     * <code>optional .po.StudyInfo studyInfo = 2;</code>
     */
    public Builder setStudyInfo(
        po.StudyInfo.Builder builderForValue) {
      if (studyInfoBuilder_ == null) {
        studyInfo_ = builderForValue.build();
      } else {
        studyInfoBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 学习信息
     * </pre>
     *
     * <code>optional .po.StudyInfo studyInfo = 2;</code>
     */
    public Builder mergeStudyInfo(po.StudyInfo value) {
      if (studyInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          studyInfo_ != null &&
          studyInfo_ != po.StudyInfo.getDefaultInstance()) {
          getStudyInfoBuilder().mergeFrom(value);
        } else {
          studyInfo_ = value;
        }
      } else {
        studyInfoBuilder_.mergeFrom(value);
      }
      if (studyInfo_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * 学习信息
     * </pre>
     *
     * <code>optional .po.StudyInfo studyInfo = 2;</code>
     */
    public Builder clearStudyInfo() {
      bitField0_ = (bitField0_ & ~0x00000002);
      studyInfo_ = null;
      if (studyInfoBuilder_ != null) {
        studyInfoBuilder_.dispose();
        studyInfoBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 学习信息
     * </pre>
     *
     * <code>optional .po.StudyInfo studyInfo = 2;</code>
     */
    public po.StudyInfo.Builder getStudyInfoBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetStudyInfoFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 学习信息
     * </pre>
     *
     * <code>optional .po.StudyInfo studyInfo = 2;</code>
     */
    public po.StudyInfoOrBuilder getStudyInfoOrBuilder() {
      if (studyInfoBuilder_ != null) {
        return studyInfoBuilder_.getMessageOrBuilder();
      } else {
        return studyInfo_ == null ?
            po.StudyInfo.getDefaultInstance() : studyInfo_;
      }
    }
    /**
     * <pre>
     * 学习信息
     * </pre>
     *
     * <code>optional .po.StudyInfo studyInfo = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        po.StudyInfo, po.StudyInfo.Builder, po.StudyInfoOrBuilder> 
        internalGetStudyInfoFieldBuilder() {
      if (studyInfoBuilder_ == null) {
        studyInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            po.StudyInfo, po.StudyInfo.Builder, po.StudyInfoOrBuilder>(
                getStudyInfo(),
                getParentForChildren(),
                isClean());
        studyInfo_ = null;
      }
      return studyInfoBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:po.UpdateStudyReq)
  }

  // @@protoc_insertion_point(class_scope:po.UpdateStudyReq)
  private static final po.UpdateStudyReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new po.UpdateStudyReq();
  }

  public static po.UpdateStudyReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdateStudyReq>
      PARSER = new com.google.protobuf.AbstractParser<UpdateStudyReq>() {
    @java.lang.Override
    public UpdateStudyReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UpdateStudyReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UpdateStudyReq> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public po.UpdateStudyReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

