// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protocol.proto
// Protobuf Java Version: 4.33.2

package po;

@com.google.protobuf.Generated
public interface UpdateNoticeRspOrBuilder extends
    // @@protoc_insertion_point(interface_extends:po.UpdateNoticeRsp)
    com.google.protobuf.MessageOrBuilder {
}
