// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protocol.proto
// Protobuf Java Version: 4.33.2

package po;

/**
 * <pre>
 * 修改用户信息（管理员）
 * </pre>
 *
 * Protobuf type {@code po.UpdateUserInfoReq}
 */
@com.google.protobuf.Generated
public final class UpdateUserInfoReq extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:po.UpdateUserInfoReq)
    UpdateUserInfoReqOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "UpdateUserInfoReq");
  }
  // Use UpdateUserInfoReq.newBuilder() to construct.
  private UpdateUserInfoReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private UpdateUserInfoReq() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return po.ProtocolProto.internal_static_po_UpdateUserInfoReq_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return po.ProtocolProto.internal_static_po_UpdateUserInfoReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            po.UpdateUserInfoReq.class, po.UpdateUserInfoReq.Builder.class);
  }

  private int bitField0_;
  public static final int ISDEL_FIELD_NUMBER = 1;
  private boolean isDel_ = false;
  /**
   * <pre>
   * 是否删除
   * </pre>
   *
   * <code>optional bool isDel = 1;</code>
   * @return Whether the isDel field is set.
   */
  @java.lang.Override
  public boolean hasIsDel() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * 是否删除
   * </pre>
   *
   * <code>optional bool isDel = 1;</code>
   * @return The isDel.
   */
  @java.lang.Override
  public boolean getIsDel() {
    return isDel_;
  }

  public static final int USERINFO_FIELD_NUMBER = 2;
  private po.UserInfo userInfo_;
  /**
   * <pre>
   * 用户信息
   * </pre>
   *
   * <code>optional .po.UserInfo userInfo = 2;</code>
   * @return Whether the userInfo field is set.
   */
  @java.lang.Override
  public boolean hasUserInfo() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * 用户信息
   * </pre>
   *
   * <code>optional .po.UserInfo userInfo = 2;</code>
   * @return The userInfo.
   */
  @java.lang.Override
  public po.UserInfo getUserInfo() {
    return userInfo_ == null ? po.UserInfo.getDefaultInstance() : userInfo_;
  }
  /**
   * <pre>
   * 用户信息
   * </pre>
   *
   * <code>optional .po.UserInfo userInfo = 2;</code>
   */
  @java.lang.Override
  public po.UserInfoOrBuilder getUserInfoOrBuilder() {
    return userInfo_ == null ? po.UserInfo.getDefaultInstance() : userInfo_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeBool(1, isDel_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getUserInfo());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, isDel_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getUserInfo());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof po.UpdateUserInfoReq)) {
      return super.equals(obj);
    }
    po.UpdateUserInfoReq other = (po.UpdateUserInfoReq) obj;

    if (hasIsDel() != other.hasIsDel()) return false;
    if (hasIsDel()) {
      if (getIsDel()
          != other.getIsDel()) return false;
    }
    if (hasUserInfo() != other.hasUserInfo()) return false;
    if (hasUserInfo()) {
      if (!getUserInfo()
          .equals(other.getUserInfo())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasIsDel()) {
      hash = (37 * hash) + ISDEL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsDel());
    }
    if (hasUserInfo()) {
      hash = (37 * hash) + USERINFO_FIELD_NUMBER;
      hash = (53 * hash) + getUserInfo().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static po.UpdateUserInfoReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static po.UpdateUserInfoReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static po.UpdateUserInfoReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static po.UpdateUserInfoReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static po.UpdateUserInfoReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static po.UpdateUserInfoReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static po.UpdateUserInfoReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static po.UpdateUserInfoReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static po.UpdateUserInfoReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static po.UpdateUserInfoReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static po.UpdateUserInfoReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static po.UpdateUserInfoReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(po.UpdateUserInfoReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 修改用户信息（管理员）
   * </pre>
   *
   * Protobuf type {@code po.UpdateUserInfoReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:po.UpdateUserInfoReq)
      po.UpdateUserInfoReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return po.ProtocolProto.internal_static_po_UpdateUserInfoReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return po.ProtocolProto.internal_static_po_UpdateUserInfoReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              po.UpdateUserInfoReq.class, po.UpdateUserInfoReq.Builder.class);
    }

    // Construct using po.UpdateUserInfoReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetUserInfoFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      isDel_ = false;
      userInfo_ = null;
      if (userInfoBuilder_ != null) {
        userInfoBuilder_.dispose();
        userInfoBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return po.ProtocolProto.internal_static_po_UpdateUserInfoReq_descriptor;
    }

    @java.lang.Override
    public po.UpdateUserInfoReq getDefaultInstanceForType() {
      return po.UpdateUserInfoReq.getDefaultInstance();
    }

    @java.lang.Override
    public po.UpdateUserInfoReq build() {
      po.UpdateUserInfoReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public po.UpdateUserInfoReq buildPartial() {
      po.UpdateUserInfoReq result = new po.UpdateUserInfoReq(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(po.UpdateUserInfoReq result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.isDel_ = isDel_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.userInfo_ = userInfoBuilder_ == null
            ? userInfo_
            : userInfoBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof po.UpdateUserInfoReq) {
        return mergeFrom((po.UpdateUserInfoReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(po.UpdateUserInfoReq other) {
      if (other == po.UpdateUserInfoReq.getDefaultInstance()) return this;
      if (other.hasIsDel()) {
        setIsDel(other.getIsDel());
      }
      if (other.hasUserInfo()) {
        mergeUserInfo(other.getUserInfo());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              isDel_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  internalGetUserInfoFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean isDel_ ;
    /**
     * <pre>
     * 是否删除
     * </pre>
     *
     * <code>optional bool isDel = 1;</code>
     * @return Whether the isDel field is set.
     */
    @java.lang.Override
    public boolean hasIsDel() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * 是否删除
     * </pre>
     *
     * <code>optional bool isDel = 1;</code>
     * @return The isDel.
     */
    @java.lang.Override
    public boolean getIsDel() {
      return isDel_;
    }
    /**
     * <pre>
     * 是否删除
     * </pre>
     *
     * <code>optional bool isDel = 1;</code>
     * @param value The isDel to set.
     * @return This builder for chaining.
     */
    public Builder setIsDel(boolean value) {

      isDel_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 是否删除
     * </pre>
     *
     * <code>optional bool isDel = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsDel() {
      bitField0_ = (bitField0_ & ~0x00000001);
      isDel_ = false;
      onChanged();
      return this;
    }

    private po.UserInfo userInfo_;
    private com.google.protobuf.SingleFieldBuilder<
        po.UserInfo, po.UserInfo.Builder, po.UserInfoOrBuilder> userInfoBuilder_;
    /**
     * <pre>
     * 用户信息
     * </pre>
     *
     * <code>optional .po.UserInfo userInfo = 2;</code>
     * @return Whether the userInfo field is set.
     */
    public boolean hasUserInfo() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * 用户信息
     * </pre>
     *
     * <code>optional .po.UserInfo userInfo = 2;</code>
     * @return The userInfo.
     */
    public po.UserInfo getUserInfo() {
      if (userInfoBuilder_ == null) {
        return userInfo_ == null ? po.UserInfo.getDefaultInstance() : userInfo_;
      } else {
        return userInfoBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 用户信息
     * </pre>
     *
     * <code>optional .po.UserInfo userInfo = 2;</code>
     */
    public Builder setUserInfo(po.UserInfo value) {
      if (userInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        userInfo_ = value;
      } else {
        userInfoBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户信息
     * </pre>
     *
     * <code>optional .po.UserInfo userInfo = 2;</code>
     */
    public Builder setUserInfo(
        po.UserInfo.Builder builderForValue) {
      if (userInfoBuilder_ == null) {
        userInfo_ = builderForValue.build();
      } else {
        userInfoBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户信息
     * </pre>
     *
     * <code>optional .po.UserInfo userInfo = 2;</code>
     */
    public Builder mergeUserInfo(po.UserInfo value) {
      if (userInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          userInfo_ != null &&
          userInfo_ != po.UserInfo.getDefaultInstance()) {
          getUserInfoBuilder().mergeFrom(value);
        } else {
          userInfo_ = value;
        }
      } else {
        userInfoBuilder_.mergeFrom(value);
      }
      if (userInfo_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * 用户信息
     * </pre>
     *
     * <code>optional .po.UserInfo userInfo = 2;</code>
     */
    public Builder clearUserInfo() {
      bitField0_ = (bitField0_ & ~0x00000002);
      userInfo_ = null;
      if (userInfoBuilder_ != null) {
        userInfoBuilder_.dispose();
        userInfoBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户信息
     * </pre>
     *
     * <code>optional .po.UserInfo userInfo = 2;</code>
     */
    public po.UserInfo.Builder getUserInfoBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetUserInfoFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 用户信息
     * </pre>
     *
     * <code>optional .po.UserInfo userInfo = 2;</code>
     */
    public po.UserInfoOrBuilder getUserInfoOrBuilder() {
      if (userInfoBuilder_ != null) {
        return userInfoBuilder_.getMessageOrBuilder();
      } else {
        return userInfo_ == null ?
            po.UserInfo.getDefaultInstance() : userInfo_;
      }
    }
    /**
     * <pre>
     * 用户信息
     * </pre>
     *
     * <code>optional .po.UserInfo userInfo = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        po.UserInfo, po.UserInfo.Builder, po.UserInfoOrBuilder> 
        internalGetUserInfoFieldBuilder() {
      if (userInfoBuilder_ == null) {
        userInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            po.UserInfo, po.UserInfo.Builder, po.UserInfoOrBuilder>(
                getUserInfo(),
                getParentForChildren(),
                isClean());
        userInfo_ = null;
      }
      return userInfoBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:po.UpdateUserInfoReq)
  }

  // @@protoc_insertion_point(class_scope:po.UpdateUserInfoReq)
  private static final po.UpdateUserInfoReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new po.UpdateUserInfoReq();
  }

  public static po.UpdateUserInfoReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdateUserInfoReq>
      PARSER = new com.google.protobuf.AbstractParser<UpdateUserInfoReq>() {
    @java.lang.Override
    public UpdateUserInfoReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UpdateUserInfoReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UpdateUserInfoReq> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public po.UpdateUserInfoReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

