// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: entity.proto
// Protobuf Java Version: 4.33.2

package po;

/**
 * <pre>
 * 用户阅读公告记录信息 有信息则阅读过
 * </pre>
 *
 * Protobuf type {@code po.UserReadNoticeInfo}
 */
@com.google.protobuf.Generated
public final class UserReadNoticeInfo extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:po.UserReadNoticeInfo)
    UserReadNoticeInfoOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "UserReadNoticeInfo");
  }
  // Use UserReadNoticeInfo.newBuilder() to construct.
  private UserReadNoticeInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private UserReadNoticeInfo() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return po.EntityProto.internal_static_po_UserReadNoticeInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return po.EntityProto.internal_static_po_UserReadNoticeInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            po.UserReadNoticeInfo.class, po.UserReadNoticeInfo.Builder.class);
  }

  private int bitField0_;
  public static final int READID_FIELD_NUMBER = 1;
  private int readId_ = 0;
  /**
   * <pre>
   * 自增唯一id
   * </pre>
   *
   * <code>optional int32 readId = 1;</code>
   * @return Whether the readId field is set.
   */
  @java.lang.Override
  public boolean hasReadId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * 自增唯一id
   * </pre>
   *
   * <code>optional int32 readId = 1;</code>
   * @return The readId.
   */
  @java.lang.Override
  public int getReadId() {
    return readId_;
  }

  public static final int READUSERTEL_FIELD_NUMBER = 2;
  private int readUserTel_ = 0;
  /**
   * <pre>
   * 阅读用户电话
   * </pre>
   *
   * <code>optional int32 readUserTel = 2;</code>
   * @return Whether the readUserTel field is set.
   */
  @java.lang.Override
  public boolean hasReadUserTel() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * 阅读用户电话
   * </pre>
   *
   * <code>optional int32 readUserTel = 2;</code>
   * @return The readUserTel.
   */
  @java.lang.Override
  public int getReadUserTel() {
    return readUserTel_;
  }

  public static final int READNOTICEID_FIELD_NUMBER = 3;
  private long readNoticeId_ = 0L;
  /**
   * <pre>
   * 公告唯一ID
   * </pre>
   *
   * <code>optional int64 readNoticeId = 3;</code>
   * @return Whether the readNoticeId field is set.
   */
  @java.lang.Override
  public boolean hasReadNoticeId() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * 公告唯一ID
   * </pre>
   *
   * <code>optional int64 readNoticeId = 3;</code>
   * @return The readNoticeId.
   */
  @java.lang.Override
  public long getReadNoticeId() {
    return readNoticeId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt32(1, readId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt32(2, readUserTel_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeInt64(3, readNoticeId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, readId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, readUserTel_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, readNoticeId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof po.UserReadNoticeInfo)) {
      return super.equals(obj);
    }
    po.UserReadNoticeInfo other = (po.UserReadNoticeInfo) obj;

    if (hasReadId() != other.hasReadId()) return false;
    if (hasReadId()) {
      if (getReadId()
          != other.getReadId()) return false;
    }
    if (hasReadUserTel() != other.hasReadUserTel()) return false;
    if (hasReadUserTel()) {
      if (getReadUserTel()
          != other.getReadUserTel()) return false;
    }
    if (hasReadNoticeId() != other.hasReadNoticeId()) return false;
    if (hasReadNoticeId()) {
      if (getReadNoticeId()
          != other.getReadNoticeId()) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasReadId()) {
      hash = (37 * hash) + READID_FIELD_NUMBER;
      hash = (53 * hash) + getReadId();
    }
    if (hasReadUserTel()) {
      hash = (37 * hash) + READUSERTEL_FIELD_NUMBER;
      hash = (53 * hash) + getReadUserTel();
    }
    if (hasReadNoticeId()) {
      hash = (37 * hash) + READNOTICEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getReadNoticeId());
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static po.UserReadNoticeInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static po.UserReadNoticeInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static po.UserReadNoticeInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static po.UserReadNoticeInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static po.UserReadNoticeInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static po.UserReadNoticeInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static po.UserReadNoticeInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static po.UserReadNoticeInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static po.UserReadNoticeInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static po.UserReadNoticeInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static po.UserReadNoticeInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static po.UserReadNoticeInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(po.UserReadNoticeInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 用户阅读公告记录信息 有信息则阅读过
   * </pre>
   *
   * Protobuf type {@code po.UserReadNoticeInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:po.UserReadNoticeInfo)
      po.UserReadNoticeInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return po.EntityProto.internal_static_po_UserReadNoticeInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return po.EntityProto.internal_static_po_UserReadNoticeInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              po.UserReadNoticeInfo.class, po.UserReadNoticeInfo.Builder.class);
    }

    // Construct using po.UserReadNoticeInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      readId_ = 0;
      readUserTel_ = 0;
      readNoticeId_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return po.EntityProto.internal_static_po_UserReadNoticeInfo_descriptor;
    }

    @java.lang.Override
    public po.UserReadNoticeInfo getDefaultInstanceForType() {
      return po.UserReadNoticeInfo.getDefaultInstance();
    }

    @java.lang.Override
    public po.UserReadNoticeInfo build() {
      po.UserReadNoticeInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public po.UserReadNoticeInfo buildPartial() {
      po.UserReadNoticeInfo result = new po.UserReadNoticeInfo(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(po.UserReadNoticeInfo result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.readId_ = readId_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.readUserTel_ = readUserTel_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.readNoticeId_ = readNoticeId_;
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof po.UserReadNoticeInfo) {
        return mergeFrom((po.UserReadNoticeInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(po.UserReadNoticeInfo other) {
      if (other == po.UserReadNoticeInfo.getDefaultInstance()) return this;
      if (other.hasReadId()) {
        setReadId(other.getReadId());
      }
      if (other.hasReadUserTel()) {
        setReadUserTel(other.getReadUserTel());
      }
      if (other.hasReadNoticeId()) {
        setReadNoticeId(other.getReadNoticeId());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              readId_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              readUserTel_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              readNoticeId_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int readId_ ;
    /**
     * <pre>
     * 自增唯一id
     * </pre>
     *
     * <code>optional int32 readId = 1;</code>
     * @return Whether the readId field is set.
     */
    @java.lang.Override
    public boolean hasReadId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * 自增唯一id
     * </pre>
     *
     * <code>optional int32 readId = 1;</code>
     * @return The readId.
     */
    @java.lang.Override
    public int getReadId() {
      return readId_;
    }
    /**
     * <pre>
     * 自增唯一id
     * </pre>
     *
     * <code>optional int32 readId = 1;</code>
     * @param value The readId to set.
     * @return This builder for chaining.
     */
    public Builder setReadId(int value) {

      readId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 自增唯一id
     * </pre>
     *
     * <code>optional int32 readId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearReadId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      readId_ = 0;
      onChanged();
      return this;
    }

    private int readUserTel_ ;
    /**
     * <pre>
     * 阅读用户电话
     * </pre>
     *
     * <code>optional int32 readUserTel = 2;</code>
     * @return Whether the readUserTel field is set.
     */
    @java.lang.Override
    public boolean hasReadUserTel() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * 阅读用户电话
     * </pre>
     *
     * <code>optional int32 readUserTel = 2;</code>
     * @return The readUserTel.
     */
    @java.lang.Override
    public int getReadUserTel() {
      return readUserTel_;
    }
    /**
     * <pre>
     * 阅读用户电话
     * </pre>
     *
     * <code>optional int32 readUserTel = 2;</code>
     * @param value The readUserTel to set.
     * @return This builder for chaining.
     */
    public Builder setReadUserTel(int value) {

      readUserTel_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 阅读用户电话
     * </pre>
     *
     * <code>optional int32 readUserTel = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearReadUserTel() {
      bitField0_ = (bitField0_ & ~0x00000002);
      readUserTel_ = 0;
      onChanged();
      return this;
    }

    private long readNoticeId_ ;
    /**
     * <pre>
     * 公告唯一ID
     * </pre>
     *
     * <code>optional int64 readNoticeId = 3;</code>
     * @return Whether the readNoticeId field is set.
     */
    @java.lang.Override
    public boolean hasReadNoticeId() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * 公告唯一ID
     * </pre>
     *
     * <code>optional int64 readNoticeId = 3;</code>
     * @return The readNoticeId.
     */
    @java.lang.Override
    public long getReadNoticeId() {
      return readNoticeId_;
    }
    /**
     * <pre>
     * 公告唯一ID
     * </pre>
     *
     * <code>optional int64 readNoticeId = 3;</code>
     * @param value The readNoticeId to set.
     * @return This builder for chaining.
     */
    public Builder setReadNoticeId(long value) {

      readNoticeId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 公告唯一ID
     * </pre>
     *
     * <code>optional int64 readNoticeId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearReadNoticeId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      readNoticeId_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:po.UserReadNoticeInfo)
  }

  // @@protoc_insertion_point(class_scope:po.UserReadNoticeInfo)
  private static final po.UserReadNoticeInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new po.UserReadNoticeInfo();
  }

  public static po.UserReadNoticeInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UserReadNoticeInfo>
      PARSER = new com.google.protobuf.AbstractParser<UserReadNoticeInfo>() {
    @java.lang.Override
    public UserReadNoticeInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UserReadNoticeInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UserReadNoticeInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public po.UserReadNoticeInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

