// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: entity.proto
// Protobuf Java Version: 4.33.2

package po;

/**
 * <pre>
 * 用户收藏信息
 * </pre>
 *
 * Protobuf type {@code po.UserStarStudyInfo}
 */
@com.google.protobuf.Generated
public final class UserStarStudyInfo extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:po.UserStarStudyInfo)
    UserStarStudyInfoOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "UserStarStudyInfo");
  }
  // Use UserStarStudyInfo.newBuilder() to construct.
  private UserStarStudyInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private UserStarStudyInfo() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return po.EntityProto.internal_static_po_UserStarStudyInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return po.EntityProto.internal_static_po_UserStarStudyInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            po.UserStarStudyInfo.class, po.UserStarStudyInfo.Builder.class);
  }

  private int bitField0_;
  public static final int STARID_FIELD_NUMBER = 1;
  private int starId_ = 0;
  /**
   * <pre>
   * 自增唯一id
   * </pre>
   *
   * <code>optional int32 starId = 1;</code>
   * @return Whether the starId field is set.
   */
  @java.lang.Override
  public boolean hasStarId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * 自增唯一id
   * </pre>
   *
   * <code>optional int32 starId = 1;</code>
   * @return The starId.
   */
  @java.lang.Override
  public int getStarId() {
    return starId_;
  }

  public static final int USERTEL_FIELD_NUMBER = 2;
  private int userTel_ = 0;
  /**
   * <pre>
   * 用户电话
   * </pre>
   *
   * <code>optional int32 userTel = 2;</code>
   * @return Whether the userTel field is set.
   */
  @java.lang.Override
  public boolean hasUserTel() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * 用户电话
   * </pre>
   *
   * <code>optional int32 userTel = 2;</code>
   * @return The userTel.
   */
  @java.lang.Override
  public int getUserTel() {
    return userTel_;
  }

  public static final int STUDYID_FIELD_NUMBER = 3;
  private int studyId_ = 0;
  /**
   * <pre>
   * 学习内容id
   * </pre>
   *
   * <code>optional int32 studyId = 3;</code>
   * @return Whether the studyId field is set.
   */
  @java.lang.Override
  public boolean hasStudyId() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * 学习内容id
   * </pre>
   *
   * <code>optional int32 studyId = 3;</code>
   * @return The studyId.
   */
  @java.lang.Override
  public int getStudyId() {
    return studyId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt32(1, starId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt32(2, userTel_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeInt32(3, studyId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, starId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, userTel_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, studyId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof po.UserStarStudyInfo)) {
      return super.equals(obj);
    }
    po.UserStarStudyInfo other = (po.UserStarStudyInfo) obj;

    if (hasStarId() != other.hasStarId()) return false;
    if (hasStarId()) {
      if (getStarId()
          != other.getStarId()) return false;
    }
    if (hasUserTel() != other.hasUserTel()) return false;
    if (hasUserTel()) {
      if (getUserTel()
          != other.getUserTel()) return false;
    }
    if (hasStudyId() != other.hasStudyId()) return false;
    if (hasStudyId()) {
      if (getStudyId()
          != other.getStudyId()) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasStarId()) {
      hash = (37 * hash) + STARID_FIELD_NUMBER;
      hash = (53 * hash) + getStarId();
    }
    if (hasUserTel()) {
      hash = (37 * hash) + USERTEL_FIELD_NUMBER;
      hash = (53 * hash) + getUserTel();
    }
    if (hasStudyId()) {
      hash = (37 * hash) + STUDYID_FIELD_NUMBER;
      hash = (53 * hash) + getStudyId();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static po.UserStarStudyInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static po.UserStarStudyInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static po.UserStarStudyInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static po.UserStarStudyInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static po.UserStarStudyInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static po.UserStarStudyInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static po.UserStarStudyInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static po.UserStarStudyInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static po.UserStarStudyInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static po.UserStarStudyInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static po.UserStarStudyInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static po.UserStarStudyInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(po.UserStarStudyInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 用户收藏信息
   * </pre>
   *
   * Protobuf type {@code po.UserStarStudyInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:po.UserStarStudyInfo)
      po.UserStarStudyInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return po.EntityProto.internal_static_po_UserStarStudyInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return po.EntityProto.internal_static_po_UserStarStudyInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              po.UserStarStudyInfo.class, po.UserStarStudyInfo.Builder.class);
    }

    // Construct using po.UserStarStudyInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      starId_ = 0;
      userTel_ = 0;
      studyId_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return po.EntityProto.internal_static_po_UserStarStudyInfo_descriptor;
    }

    @java.lang.Override
    public po.UserStarStudyInfo getDefaultInstanceForType() {
      return po.UserStarStudyInfo.getDefaultInstance();
    }

    @java.lang.Override
    public po.UserStarStudyInfo build() {
      po.UserStarStudyInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public po.UserStarStudyInfo buildPartial() {
      po.UserStarStudyInfo result = new po.UserStarStudyInfo(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(po.UserStarStudyInfo result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.starId_ = starId_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.userTel_ = userTel_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.studyId_ = studyId_;
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof po.UserStarStudyInfo) {
        return mergeFrom((po.UserStarStudyInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(po.UserStarStudyInfo other) {
      if (other == po.UserStarStudyInfo.getDefaultInstance()) return this;
      if (other.hasStarId()) {
        setStarId(other.getStarId());
      }
      if (other.hasUserTel()) {
        setUserTel(other.getUserTel());
      }
      if (other.hasStudyId()) {
        setStudyId(other.getStudyId());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              starId_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              userTel_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              studyId_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int starId_ ;
    /**
     * <pre>
     * 自增唯一id
     * </pre>
     *
     * <code>optional int32 starId = 1;</code>
     * @return Whether the starId field is set.
     */
    @java.lang.Override
    public boolean hasStarId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * 自增唯一id
     * </pre>
     *
     * <code>optional int32 starId = 1;</code>
     * @return The starId.
     */
    @java.lang.Override
    public int getStarId() {
      return starId_;
    }
    /**
     * <pre>
     * 自增唯一id
     * </pre>
     *
     * <code>optional int32 starId = 1;</code>
     * @param value The starId to set.
     * @return This builder for chaining.
     */
    public Builder setStarId(int value) {

      starId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 自增唯一id
     * </pre>
     *
     * <code>optional int32 starId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStarId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      starId_ = 0;
      onChanged();
      return this;
    }

    private int userTel_ ;
    /**
     * <pre>
     * 用户电话
     * </pre>
     *
     * <code>optional int32 userTel = 2;</code>
     * @return Whether the userTel field is set.
     */
    @java.lang.Override
    public boolean hasUserTel() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * 用户电话
     * </pre>
     *
     * <code>optional int32 userTel = 2;</code>
     * @return The userTel.
     */
    @java.lang.Override
    public int getUserTel() {
      return userTel_;
    }
    /**
     * <pre>
     * 用户电话
     * </pre>
     *
     * <code>optional int32 userTel = 2;</code>
     * @param value The userTel to set.
     * @return This builder for chaining.
     */
    public Builder setUserTel(int value) {

      userTel_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户电话
     * </pre>
     *
     * <code>optional int32 userTel = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserTel() {
      bitField0_ = (bitField0_ & ~0x00000002);
      userTel_ = 0;
      onChanged();
      return this;
    }

    private int studyId_ ;
    /**
     * <pre>
     * 学习内容id
     * </pre>
     *
     * <code>optional int32 studyId = 3;</code>
     * @return Whether the studyId field is set.
     */
    @java.lang.Override
    public boolean hasStudyId() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * 学习内容id
     * </pre>
     *
     * <code>optional int32 studyId = 3;</code>
     * @return The studyId.
     */
    @java.lang.Override
    public int getStudyId() {
      return studyId_;
    }
    /**
     * <pre>
     * 学习内容id
     * </pre>
     *
     * <code>optional int32 studyId = 3;</code>
     * @param value The studyId to set.
     * @return This builder for chaining.
     */
    public Builder setStudyId(int value) {

      studyId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 学习内容id
     * </pre>
     *
     * <code>optional int32 studyId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearStudyId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      studyId_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:po.UserStarStudyInfo)
  }

  // @@protoc_insertion_point(class_scope:po.UserStarStudyInfo)
  private static final po.UserStarStudyInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new po.UserStarStudyInfo();
  }

  public static po.UserStarStudyInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UserStarStudyInfo>
      PARSER = new com.google.protobuf.AbstractParser<UserStarStudyInfo>() {
    @java.lang.Override
    public UserStarStudyInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UserStarStudyInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UserStarStudyInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public po.UserStarStudyInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

