// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: entity.proto
// Protobuf Java Version: 4.33.2

package po;

/**
 * <pre>
 * 用户阅读公告记录信息 有信息则阅读过
 * </pre>
 *
 * Protobuf type {@code po.UserReadNoticeInfo}
 */
@com.google.protobuf.Generated
public final class UserReadNoticeInfo extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:po.UserReadNoticeInfo)
    UserReadNoticeInfoOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "UserReadNoticeInfo");
  }
  // Use UserReadNoticeInfo.newBuilder() to construct.
  private UserReadNoticeInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private UserReadNoticeInfo() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return po.EntityProto.internal_static_po_UserReadNoticeInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return po.EntityProto.internal_static_po_UserReadNoticeInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            po.UserReadNoticeInfo.class, po.UserReadNoticeInfo.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private int id_ = 0;
  /**
   * <pre>
   * 自增唯一id
   * </pre>
   *
   * <code>optional int32 id = 1;</code>
   * @return Whether the id field is set.
   */
  @java.lang.Override
  public boolean hasId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * 自增唯一id
   * </pre>
   *
   * <code>optional int32 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int USERTEL_FIELD_NUMBER = 2;
  private long userTel_ = 0L;
  /**
   * <pre>
   * 阅读用户电话
   * </pre>
   *
   * <code>optional int64 userTel = 2;</code>
   * @return Whether the userTel field is set.
   */
  @java.lang.Override
  public boolean hasUserTel() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * 阅读用户电话
   * </pre>
   *
   * <code>optional int64 userTel = 2;</code>
   * @return The userTel.
   */
  @java.lang.Override
  public long getUserTel() {
    return userTel_;
  }

  public static final int NOTICEID_FIELD_NUMBER = 3;
  private int noticeId_ = 0;
  /**
   * <pre>
   * 公告唯一ID
   * </pre>
   *
   * <code>optional int32 noticeId = 3;</code>
   * @return Whether the noticeId field is set.
   */
  @java.lang.Override
  public boolean hasNoticeId() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * 公告唯一ID
   * </pre>
   *
   * <code>optional int32 noticeId = 3;</code>
   * @return The noticeId.
   */
  @java.lang.Override
  public int getNoticeId() {
    return noticeId_;
  }

  public static final int READTIME_FIELD_NUMBER = 4;
  private long readTime_ = 0L;
  /**
   * <pre>
   * 阅读时间
   * </pre>
   *
   * <code>optional int64 readTime = 4;</code>
   * @return Whether the readTime field is set.
   */
  @java.lang.Override
  public boolean hasReadTime() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <pre>
   * 阅读时间
   * </pre>
   *
   * <code>optional int64 readTime = 4;</code>
   * @return The readTime.
   */
  @java.lang.Override
  public long getReadTime() {
    return readTime_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt32(1, id_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt64(2, userTel_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeInt32(3, noticeId_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeInt64(4, readTime_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, userTel_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, noticeId_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, readTime_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof po.UserReadNoticeInfo)) {
      return super.equals(obj);
    }
    po.UserReadNoticeInfo other = (po.UserReadNoticeInfo) obj;

    if (hasId() != other.hasId()) return false;
    if (hasId()) {
      if (getId()
          != other.getId()) return false;
    }
    if (hasUserTel() != other.hasUserTel()) return false;
    if (hasUserTel()) {
      if (getUserTel()
          != other.getUserTel()) return false;
    }
    if (hasNoticeId() != other.hasNoticeId()) return false;
    if (hasNoticeId()) {
      if (getNoticeId()
          != other.getNoticeId()) return false;
    }
    if (hasReadTime() != other.hasReadTime()) return false;
    if (hasReadTime()) {
      if (getReadTime()
          != other.getReadTime()) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
    }
    if (hasUserTel()) {
      hash = (37 * hash) + USERTEL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserTel());
    }
    if (hasNoticeId()) {
      hash = (37 * hash) + NOTICEID_FIELD_NUMBER;
      hash = (53 * hash) + getNoticeId();
    }
    if (hasReadTime()) {
      hash = (37 * hash) + READTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getReadTime());
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static po.UserReadNoticeInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static po.UserReadNoticeInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static po.UserReadNoticeInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static po.UserReadNoticeInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static po.UserReadNoticeInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static po.UserReadNoticeInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static po.UserReadNoticeInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static po.UserReadNoticeInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static po.UserReadNoticeInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static po.UserReadNoticeInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static po.UserReadNoticeInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static po.UserReadNoticeInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(po.UserReadNoticeInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 用户阅读公告记录信息 有信息则阅读过
   * </pre>
   *
   * Protobuf type {@code po.UserReadNoticeInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:po.UserReadNoticeInfo)
      po.UserReadNoticeInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return po.EntityProto.internal_static_po_UserReadNoticeInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return po.EntityProto.internal_static_po_UserReadNoticeInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              po.UserReadNoticeInfo.class, po.UserReadNoticeInfo.Builder.class);
    }

    // Construct using po.UserReadNoticeInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    private long userTel_ ;

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return po.EntityProto.internal_static_po_UserReadNoticeInfo_descriptor;
    }

    @java.lang.Override
    public po.UserReadNoticeInfo getDefaultInstanceForType() {
      return po.UserReadNoticeInfo.getDefaultInstance();
    }

    @java.lang.Override
    public po.UserReadNoticeInfo build() {
      po.UserReadNoticeInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public po.UserReadNoticeInfo buildPartial() {
      po.UserReadNoticeInfo result = new po.UserReadNoticeInfo(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(po.UserReadNoticeInfo result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.userTel_ = userTel_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.noticeId_ = noticeId_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.readTime_ = readTime_;
        to_bitField0_ |= 0x00000008;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof po.UserReadNoticeInfo) {
        return mergeFrom((po.UserReadNoticeInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(po.UserReadNoticeInfo other) {
      if (other == po.UserReadNoticeInfo.getDefaultInstance()) return this;
      if (other.hasId()) {
        setId(other.getId());
      }
      if (other.hasUserTel()) {
        setUserTel(other.getUserTel());
      }
      if (other.hasNoticeId()) {
        setNoticeId(other.getNoticeId());
      }
      if (other.hasReadTime()) {
        setReadTime(other.getReadTime());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = 0;
      userTel_ = 0L;
      noticeId_ = 0;
      readTime_ = 0L;
      return this;
    }
    private int bitField0_;

    private int id_ ;
    /**
     * <pre>
     * 自增唯一id
     * </pre>
     *
     * <code>optional int32 id = 1;</code>
     * @return Whether the id field is set.
     */
    @java.lang.Override
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * 自增唯一id
     * </pre>
     *
     * <code>optional int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <pre>
     * 自增唯一id
     * </pre>
     *
     * <code>optional int32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {

      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 自增唯一id
     * </pre>
     *
     * <code>optional int32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0;
      onChanged();
      return this;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              id_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              userTel_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              noticeId_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              readTime_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    /**
     * <pre>
     * 阅读用户电话
     * </pre>
     *
     * <code>optional int64 userTel = 2;</code>
     * @return Whether the userTel field is set.
     */
    @java.lang.Override
    public boolean hasUserTel() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * 阅读用户电话
     * </pre>
     *
     * <code>optional int64 userTel = 2;</code>
     * @return The userTel.
     */
    @java.lang.Override
    public long getUserTel() {
      return userTel_;
    }
    /**
     * <pre>
     * 阅读用户电话
     * </pre>
     *
     * <code>optional int64 userTel = 2;</code>
     * @param value The userTel to set.
     * @return This builder for chaining.
     */
    public Builder setUserTel(long value) {

      userTel_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 阅读用户电话
     * </pre>
     *
     * <code>optional int64 userTel = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserTel() {
      bitField0_ = (bitField0_ & ~0x00000002);
      userTel_ = 0L;
      onChanged();
      return this;
    }

    private int noticeId_ ;
    /**
     * <pre>
     * 公告唯一ID
     * </pre>
     *
     * <code>optional int32 noticeId = 3;</code>
     * @return Whether the noticeId field is set.
     */
    @java.lang.Override
    public boolean hasNoticeId() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * 公告唯一ID
     * </pre>
     *
     * <code>optional int32 noticeId = 3;</code>
     * @return The noticeId.
     */
    @java.lang.Override
    public int getNoticeId() {
      return noticeId_;
    }
    /**
     * <pre>
     * 公告唯一ID
     * </pre>
     *
     * <code>optional int32 noticeId = 3;</code>
     * @param value The noticeId to set.
     * @return This builder for chaining.
     */
    public Builder setNoticeId(int value) {

      noticeId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 公告唯一ID
     * </pre>
     *
     * <code>optional int32 noticeId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearNoticeId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      noticeId_ = 0;
      onChanged();
      return this;
    }

    private long readTime_ ;
    /**
     * <pre>
     * 阅读时间
     * </pre>
     *
     * <code>optional int64 readTime = 4;</code>
     * @return Whether the readTime field is set.
     */
    @java.lang.Override
    public boolean hasReadTime() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * 阅读时间
     * </pre>
     *
     * <code>optional int64 readTime = 4;</code>
     * @return The readTime.
     */
    @java.lang.Override
    public long getReadTime() {
      return readTime_;
    }
    /**
     * <pre>
     * 阅读时间
     * </pre>
     *
     * <code>optional int64 readTime = 4;</code>
     * @param value The readTime to set.
     * @return This builder for chaining.
     */
    public Builder setReadTime(long value) {

      readTime_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 阅读时间
     * </pre>
     *
     * <code>optional int64 readTime = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearReadTime() {
      bitField0_ = (bitField0_ & ~0x00000008);
      readTime_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:po.UserReadNoticeInfo)
  }

  // @@protoc_insertion_point(class_scope:po.UserReadNoticeInfo)
  private static final po.UserReadNoticeInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new po.UserReadNoticeInfo();
  }

  public static po.UserReadNoticeInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UserReadNoticeInfo>
      PARSER = new com.google.protobuf.AbstractParser<UserReadNoticeInfo>() {
    @java.lang.Override
    public UserReadNoticeInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UserReadNoticeInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UserReadNoticeInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public po.UserReadNoticeInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

